/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dw].[Claim]
(
[ClaimID] [binary] (32) NOT NULL,
[CompanyID] [binary] (32) NOT NULL,
[PartID] [binary] (32) NULL,
[CustomerID] [binary] (32) NULL,
[SupplierID] [binary] (32) NULL,
[WarehouseID] [binary] (32) NULL,
[StartDateID] [int] NULL,
[Company] [nvarchar] (8) NOT NULL,
[CustomerNum] [nvarchar] (50) NULL,
[SalesOrderNum] [nvarchar] (50) NULL,
[SalesOrderLine] [nvarchar] (20) NULL,
[SupplierNum] [nvarchar] (50) NULL,
[PurchaseOrderNum] [nvarchar] (50) NULL,
[PurchaseOrderLine] [nvarchar] (20) NULL,
[ClaimNum] [nvarchar] (50) NOT NULL,
[ClaimDescription] [nvarchar] (100) NULL,
[ClaimType] [nvarchar] (20) NULL,
[ClaimGroup] [nvarchar] (50) NULL,
[ClaimPriority] [nvarchar] (20) NULL,
[PartNum] [nvarchar] (50) NULL,
[ClaimHandler] [nvarchar] (50) NULL,
[CreateDate] [date] NULL,
[StartDate] [date] NULL,
[StartTime] [datetime] NULL,
[EndDate] [date] NULL,
[EndTime] [datetime] NULL,
[WarehouseCode] [nvarchar] (50) NULL,
[Comment] [nvarchar] (4000) NULL,
[is_deleted] [bit] NULL,
[ClaimResponsible] [nvarchar] (50) NULL,
[CreateTime] [datetime] NULL,
[IsActiveRecord] [bit] NULL,
[CLRes1] [nvarchar] (100) NULL,
[CLRes2] [nvarchar] (100) NULL,
[CLRes3] [nvarchar] (100) NULL,
[PartitionKey] [nvarchar] (50) NOT NULL
)
GO
ALTER TABLE [dw].[Claim] ADD CONSTRAINT [PK__Claims__7507310B6CC97501] PRIMARY KEY CLUSTERED ([ClaimID])
GO
