/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dw].[Cubes_PT_test]
(
[CubeName] [varchar] (40) NULL,
[ProcessPost] [varchar] (max) NULL
)
GO
