/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dw].[Department]
(
[PartitionKey] [varchar] (50) NOT NULL,
[Company] [nvarchar] (8) NOT NULL,
[DepartmentID] [binary] (32) NOT NULL,
[DepartmentCode] [nvarchar] (50) NULL,
[DepartmentName] [nvarchar] (100) NULL,
[DepartmentSite] [nvarchar] (50) NULL,
[Address] [nvarchar] (100) NULL,
[ZipCode] [nvarchar] (8) NULL,
[City] [nvarchar] (100) NULL,
[State] [nvarchar] (50) NULL,
[CountryCode] [nvarchar] (50) NULL,
[CountryName] [nvarchar] (50) NULL,
[DepartmentType] [nvarchar] (50) NULL,
[DepartmentDescription] [nvarchar] (1000) NULL,
[IsActiveRecord] [bit] NULL,
[DptRes1] [nvarchar] (1000) NULL,
[DptRes2] [nvarchar] (1000) NULL,
[DptRes3] [nvarchar] (1000) NULL,
[is_deleted] [bit] NULL,
[is_inferred] [bit] NULL,
[CompanyID] [binary] (32) NULL
)
GO
ALTER TABLE [dw].[Department] ADD CONSTRAINT [PK__Departme__B2079BCD8511F3DA] PRIMARY KEY CLUSTERED ([DepartmentID])
GO
