/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dw].[GeneralLedger]
(
[GeneralLedgerID] [binary] (32) NOT NULL,
[AccountID] [binary] (32) NULL,
[CustomerID] [binary] (32) NULL,
[SupplierID] [binary] (32) NULL,
[CompanyID] [binary] (32) NOT NULL,
[ProjectID] [binary] (32) NULL,
[CostUnitID] [binary] (32) NULL,
[CostBearerID] [binary] (32) NULL,
[PartitionKey] [varchar] (50) NOT NULL,
[Company] [nvarchar] (8) NULL,
[AccountNum] [nvarchar] (50) NULL,
[CostUnitNum] [nvarchar] (50) NULL,
[CostBearerNum] [nvarchar] (50) NULL,
[JournalType] [nvarchar] (50) NULL,
[JournalDate] [date] NULL,
[JournalNum] [nvarchar] (50) NULL,
[JournalLine] [nvarchar] (50) NULL,
[AccountingDate] [date] NULL,
[Description] [nvarchar] (500) NULL,
[Currency] [nvarchar] (50) NULL,
[ExchangeRate] [decimal] (18, 4) NULL,
[InvoiceAmount] [decimal] (18, 4) NULL,
[CustomerNum] [nvarchar] (50) NULL,
[SupplierNum] [nvarchar] (50) NULL,
[SalesInvoiceNum] [nvarchar] (50) NULL,
[PurchaseInvoiceNum] [nvarchar] (50) NULL,
[SupplierInvoiceNum] [nvarchar] (50) NULL,
[LinkToOriginalInvoice] [nvarchar] (500) NULL,
[DeliveryCountry] [nvarchar] (100) NULL,
[TransactionNum] [nvarchar] (50) NULL,
[VATCode] [nvarchar] (50) NULL,
[VATCodeDesc] [nvarchar] (500) NULL,
[GLRes1] [nvarchar] (100) NULL,
[GLRes2] [nvarchar] (100) NULL,
[GLRes3] [nvarchar] (100) NULL,
[InvoiceAmountLC] [decimal] (18, 4) NULL,
[is_deleted] [bit] NULL,
[IndexKey] [nvarchar] (50) NULL,
[ProjectNum] [nvarchar] (50) NULL,
[TransactionAmount] [decimal] (18, 4) NULL,
[UserIDBooked] [nvarchar] (50) NULL,
[UserIDApproved] [nvarchar] (50) NULL,
[IsManual] [bit] NULL,
[CreatedTimeStamp] [datetime] NULL,
[ModifiedTimeStamp] [datetime] NULL,
[IsActiveRecord] [bit] NULL
)
GO
ALTER TABLE [dw].[GeneralLedger] ADD CONSTRAINT [PK_GeneralLedger] PRIMARY KEY CLUSTERED ([GeneralLedgerID])
GO
