/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dw].[masterCubes]
(
[Report] [varchar] (25) NULL,
[CubeName] [varchar] (100) NULL,
[ProcessPost] [varchar] (2000) NULL,
[ReportOrder] [int] NULL,
[BusinessGroupOrder] [int] NULL
)
GO
