/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dw].[OpenBalance]
(
[OpenBalanceID] [binary] (32) NOT NULL,
[CostUnitID] [binary] (32) NULL,
[CostBearerID] [binary] (32) NULL,
[ProjectID] [binary] (32) NULL,
[CompanyID] [binary] (32) NOT NULL,
[AccountID] [binary] (32) NULL,
[PartitionKey] [varchar] (50) NOT NULL,
[Company] [nvarchar] (8) NULL,
[AccountNum] [nvarchar] (50) NULL,
[CostUnitNum] [nvarchar] (50) NULL,
[CostBearerNum] [nvarchar] (50) NULL,
[ProjectNum] [nvarchar] (50) NULL,
[JournalType] [nvarchar] (50) NULL,
[JournalDate] [date] NULL,
[AccountingDate] [date] NULL,
[Description] [nvarchar] (500) NULL,
[OpeningBalance] [decimal] (18, 4) NULL,
[Currency] [nvarchar] (50) NULL,
[ExchangeRate] [decimal] (18, 4) NULL,
[OBRes1] [nvarchar] (100) NULL,
[OBRes2] [nvarchar] (100) NULL,
[OBRes3] [nvarchar] (100) NULL,
[is_deleted] [bit] NULL,
[IsActiveRecord] [bit] NULL
)
GO
ALTER TABLE [dw].[OpenBalance] ADD CONSTRAINT [PK_OpenBalance] PRIMARY KEY CLUSTERED ([OpenBalanceID])
GO
