/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dw].[Part]
(
[PartID] [binary] (32) NOT NULL,
[PartCode] [nvarchar] (max) NULL,
[Company] [nvarchar] (8) NOT NULL,
[PartNum] [nvarchar] (100) NULL,
[PartName] [nvarchar] (200) NULL,
[PartDescription] [nvarchar] (max) NULL,
[PartDescription2] [nvarchar] (max) NULL,
[PartDescription3] [nvarchar] (max) NULL,
[ProductGroup] [nvarchar] (200) NULL,
[ProductGroup2] [nvarchar] (200) NULL,
[ProductGroup3] [nvarchar] (200) NULL,
[ProductGroup4] [nvarchar] (200) NULL,
[Brand] [nvarchar] (200) NULL,
[CommodityCode] [nvarchar] (50) NULL,
[PartReplacementNum] [nvarchar] (100) NULL,
[PartStatus] [nvarchar] (100) NULL,
[CountryOfOrigin] [nvarchar] (100) NULL,
[NetWeight] [decimal] (18, 4) NULL,
[UoM] [nvarchar] (50) NULL,
[Material] [nvarchar] (200) NULL,
[Barcode] [nvarchar] (50) NULL,
[ReOrderLevel] [decimal] (18, 4) NULL,
[PartResponsible] [nvarchar] (100) NULL,
[StartDate] [date] NULL,
[EndDate] [date] NULL,
[CompanyID] [binary] (32) NULL,
[PartitionKey] [varchar] (50) NOT NULL,
[MainSupplier] [nvarchar] (100) NULL,
[AlternativeSupplier] [nvarchar] (100) NULL,
[is_deleted] [bit] NULL,
[is_inferred] [bit] NULL,
[PARes1] [nvarchar] (100) NULL,
[PARes2] [nvarchar] (100) NULL,
[PARes3] [nvarchar] (100) NULL,
[IsActiveRecord] [bit] NULL
)
GO
ALTER TABLE [dw].[Part] ADD CONSTRAINT [PK_Part] PRIMARY KEY CLUSTERED ([PartID])
GO
CREATE NONCLUSTERED INDEX [nci_wi_Company] ON [dw].[Part] ([Company])
GO
CREATE NONCLUSTERED INDEX [nci_wi_Part] ON [dw].[Part] ([PartitionKey])
GO
