/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dw].[PriceListPurchase]
(
[PriceID] [binary] (32) NOT NULL,
[CompanyID] [binary] (32) NULL,
[CustomerID] [binary] (32) NULL,
[SupplierID] [binary] (32) NULL,
[PartID] [binary] (32) NULL,
[CustomerCode] [nvarchar] (100) NULL,
[SupplierCode] [nvarchar] (100) NULL,
[PartCode] [nvarchar] (100) NULL,
[PartitionKey] [varchar] (50) NULL,
[Company] [nvarchar] (8) NULL,
[CustomerNum] [nvarchar] (50) NULL,
[SupplierNum] [nvarchar] (50) NULL,
[PartNum] [nvarchar] (50) NULL,
[TargetMargin] [nvarchar] (50) NULL,
[Currency] [nvarchar] (50) NULL,
[Price] [nvarchar] (4000) NULL,
[DiscountPercent] [nvarchar] (4000) NULL,
[ValidFrom] [nvarchar] (50) NULL,
[ValidTo] [nvarchar] (50) NULL,
[DelivTime] [nvarchar] (50) NULL,
[DelivTimeUnit] [nvarchar] (50) NULL,
[Qty1] [nvarchar] (4000) NULL,
[Discount1] [nvarchar] (4000) NULL,
[Price1] [nvarchar] (4000) NULL,
[Qty2] [nvarchar] (4000) NULL,
[Discount2] [nvarchar] (4000) NULL,
[Price2] [nvarchar] (4000) NULL,
[CreatedDate] [date] NULL,
[Qty3] [nvarchar] (4000) NULL,
[Discount3] [nvarchar] (4000) NULL,
[Price3] [nvarchar] (4000) NULL,
[Qty4] [nvarchar] (4000) NULL,
[Discount4] [nvarchar] (4000) NULL,
[Price4] [nvarchar] (4000) NULL,
[Qty5] [nvarchar] (4000) NULL,
[Discount5] [nvarchar] (4000) NULL,
[Price5] [nvarchar] (4000) NULL,
[PriceType] [nvarchar] (50) NULL
)
GO
ALTER TABLE [dw].[PriceListPurchase] ADD CONSTRAINT [PK_PriceListPurchase] PRIMARY KEY CLUSTERED ([PriceID])
GO
