/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dw].[PurchaseInvoice]
(
[PurchaseInvoiceID] [binary] (32) NOT NULL,
[Company] [nvarchar] (8) NOT NULL,
[PurchaseOrderNum] [nvarchar] (50) NULL,
[PurchaseOrderLine] [nvarchar] (50) NULL,
[PurchaseOrderSubLine] [nvarchar] (50) NULL,
[PurchaseOrderType] [nvarchar] (50) NULL,
[PurchaseInvoiceNum] [nvarchar] (50) NOT NULL,
[PurchaseInvoiceLine] [nvarchar] (50) NULL,
[PurchaseInvoiceType] [nvarchar] (50) NULL,
[PurchaseInvoiceDate] [date] NULL,
[ActualDelivDate] [date] NULL,
[SupplierNum] [nvarchar] (50) NOT NULL,
[PartNum] [nvarchar] (50) NULL,
[PurchaseInvoiceQty] [decimal] (18, 4) NULL,
[UoM] [nvarchar] (50) NULL,
[UnitPrice] [decimal] (18, 4) NULL,
[DiscountPercent] [decimal] (18, 4) NULL,
[DiscountAmount] [decimal] (18, 4) NULL,
[TotalMiscChrg] [decimal] (18, 4) NULL,
[VATAmount] [decimal] (18, 4) NULL,
[ExchangeRate] [decimal] (18, 4) NULL,
[Currency] [nvarchar] (10) NULL,
[CreditMemo] [nvarchar] (100) NULL,
[PurchaserName] [nvarchar] (100) NULL,
[WarehouseCode] [nvarchar] (50) NULL,
[PurchaseChannel] [nvarchar] (50) NULL,
[PIRes1] [nvarchar] (100) NULL,
[PIRes2] [nvarchar] (100) NULL,
[PIRes3] [nvarchar] (100) NULL,
[PurchaseInvoiceCode] [nvarchar] (300) NULL,
[PurchaseOrderCode] [nvarchar] (300) NULL,
[PurchaseOrderNumID] [binary] (32) NULL,
[PurchaseOrderID] [binary] (32) NULL,
[SupplierID] [binary] (32) NULL,
[CompanyID] [binary] (32) NULL,
[PartID] [binary] (32) NULL,
[WarehouseID] [binary] (32) NULL,
[PurchaseInvoiceDateID] [nvarchar] (50) NULL,
[PurchaseLedgerID] [binary] (32) NULL,
[PartitionKey] [nvarchar] (50) NULL,
[Comment] [nvarchar] (500) NULL,
[is_deleted] [bit] NULL,
[PurchaseInvoiceSubLine] [nvarchar] (50) NULL,
[ActualShipDate] [date] NULL,
[ActualRecieveDate] [date] NULL,
[IsInvoiceClosed] [bit] NULL,
[IsActiveRecord] [bit] NULL,
[PIRes4] [decimal] (18, 4) NULL,
[PurchaseInvoiceAmountOC] [decimal] (18, 4) NULL
)
GO
ALTER TABLE [dw].[PurchaseInvoice] ADD CONSTRAINT [PK_PurchaseInvoice] PRIMARY KEY CLUSTERED ([PurchaseInvoiceID])
GO
CREATE NONCLUSTERED INDEX [IX_Company_PurchaseInvoiceDate] ON [dw].[PurchaseInvoice] ([Company], [PurchaseInvoiceDate] DESC)
GO
