/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dw].[SalesInvoice]
(
[SalesInvoiceID] [binary] (32) NOT NULL,
[Company] [nvarchar] (8) NOT NULL,
[SalesPersonName] [nvarchar] (100) NULL,
[CustomerNum] [nvarchar] (50) NULL,
[PartNum] [nvarchar] (50) NULL,
[PartType] [nvarchar] (50) NULL,
[SalesOrderNum] [nvarchar] (50) NULL,
[SalesOrderLine] [nvarchar] (50) NULL,
[SalesOrderSubLine] [nvarchar] (50) NULL,
[SalesOrderType] [nvarchar] (50) NULL,
[SalesInvoiceNum] [nvarchar] (50) NOT NULL,
[SalesInvoiceLine] [nvarchar] (50) NULL,
[SalesInvoiceType] [nvarchar] (50) NULL,
[SalesInvoiceDate] [date] NULL,
[ActualDelivDate] [date] NULL,
[SalesInvoiceQty] [decimal] (18, 4) NULL,
[UoM] [nvarchar] (50) NULL,
[UnitPrice] [decimal] (18, 4) NULL,
[UnitCost] [decimal] (18, 4) NULL,
[DiscountPercent] [decimal] (18, 4) NULL,
[DiscountAmount] [decimal] (18, 4) NULL,
[TotalMiscChrg] [decimal] (18, 4) NULL,
[VATAmount] [decimal] (18, 4) NULL,
[Currency] [nvarchar] (50) NULL,
[ExchangeRate] [decimal] (18, 4) NULL,
[CreditMemo] [nvarchar] (50) NULL,
[SalesChannel] [nvarchar] (50) NULL,
[Department] [nvarchar] (50) NULL,
[WarehouseCode] [nvarchar] (50) NULL,
[CostBearerNum] [nvarchar] (50) NULL,
[CostUnitNum] [nvarchar] (50) NULL,
[ReturnComment] [nvarchar] (max) NULL,
[ReturnNum] [nvarchar] (50) NULL,
[ProjectNum] [nvarchar] (50) NULL,
[IndexKey] [nvarchar] (50) NULL,
[SIRes1] [nvarchar] (100) NULL,
[SIRes2] [nvarchar] (100) NULL,
[SIRes3] [nvarchar] (100) NULL,
[SalesOrderID] [binary] (32) NULL,
[SalesLedgerID] [binary] (32) NULL,
[SalesOrderNumID] [binary] (32) NULL,
[CompanyID] [binary] (32) NULL,
[CustomerID] [binary] (32) NULL,
[PartID] [binary] (32) NULL,
[WarehouseID] [binary] (32) NULL,
[SalesOrderCode] [nvarchar] (200) NULL,
[SalesInvoiceDateID] [int] NULL,
[SalesInvoiceCode] [nvarchar] (500) NULL,
[PartitionKey] [nvarchar] (50) NOT NULL,
[CashDiscountOffered] [decimal] (18, 4) NULL CONSTRAINT [DF__SalesInvo__CashD__0371755F] DEFAULT ((0)),
[CashDiscountUsed] [decimal] (18, 4) NULL CONSTRAINT [DF__SalesInvo__CashD__04659998] DEFAULT ((0)),
[ProjectID] [binary] (32) NULL,
[DeliveryAddress] [nvarchar] (255) NULL,
[IsUpdatingStock] [nvarchar] (50) NULL,
[SIRes4] [decimal] (18, 4) NULL,
[SIRes5] [decimal] (18, 4) NULL,
[SIRes6] [decimal] (18, 4) NULL,
[is_deleted] [bit] NULL,
[DepartmentID] [binary] (32) NULL,
[SalesInvoiceSubLine] [nvarchar] (50) NULL,
[IsInvoiceClosed] [bit] NULL,
[InvoiceHandler] [nvarchar] (100) NULL,
[IsCreditMemo] [nvarchar] (50) NULL,
[DepartmentCode] [nvarchar] (50) NULL,
[DeliveryZipCode] [nvarchar] (50) NULL,
[DeliveryCity] [nvarchar] (50) NULL,
[DeliveryCountry] [nvarchar] (50) NULL,
[IsActiveRecord] [bit] NULL
)
GO
ALTER TABLE [dw].[SalesInvoice] ADD CONSTRAINT [PK_SalesInvoice] PRIMARY KEY CLUSTERED ([SalesInvoiceID])
GO
CREATE NONCLUSTERED INDEX [nci_wi_Company] ON [dw].[SalesInvoice] ([Company])
GO
CREATE NONCLUSTERED INDEX [IX_Company_SalesInvoiceDate] ON [dw].[SalesInvoice] ([Company], [SalesInvoiceDate] DESC)
GO
