/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dw].[SalesLedger]
(
[SalesLedgerID] [binary] (32) NOT NULL,
[Company] [nvarchar] (8) NULL,
[CustomerNum] [nvarchar] (50) NULL,
[SalesInvoiceNum] [nvarchar] (50) NULL,
[SalesInvoiceDate] [date] NULL,
[SalesDueDate] [date] NULL,
[SalesLastPaymentDate] [date] NULL,
[InvoiceAmount] [decimal] (18, 4) NULL,
[RemainingInvoiceAmount] [decimal] (18, 4) NULL,
[ExchangeRate] [decimal] (18, 8) NULL,
[Currency] [nvarchar] (10) NULL,
[VATAmount] [decimal] (18, 4) NULL,
[VATCode] [nvarchar] (50) NULL,
[PayToName] [nvarchar] (100) NULL,
[PayToCity] [nvarchar] (50) NULL,
[PayToContact] [nvarchar] (50) NULL,
[PaymentTerms] [nvarchar] (50) NULL,
[SLRes1] [nvarchar] (100) NULL,
[SLRes2] [nvarchar] (100) NULL,
[SLRes3] [nvarchar] (100) NULL,
[SalesLedgerCode] [nvarchar] (500) NULL,
[CompanyID] [binary] (32) NOT NULL,
[PartitionKey] [varchar] (50) NOT NULL,
[PaidInvoiceAmount] [decimal] (18, 4) NULL,
[AccountingDate] [date] NULL,
[AgingPeriod] [nvarchar] (100) NULL,
[VATCodeDesc] [nvarchar] (300) NULL,
[CustomerID] [binary] (32) NULL,
[AgingSort] [int] NULL,
[LinkToOriginalInvoice] [nvarchar] (500) MASKED WITH (FUNCTION = 'default()') NULL,
[SalesPersonName] [nvarchar] (100) NULL,
[WarehouseID] [binary] (32) NULL,
[is_deleted] [bit] NULL,
[SalesOrderNum] [nvarchar] (50) NULL,
[IsInvoiceClosed] [bit] NULL,
[PaymentEvents] [int] NULL,
[IsActiveRecord] [bit] NULL
)
GO
ALTER TABLE [dw].[SalesLedger] ADD CONSTRAINT [PK_SalesLedger] PRIMARY KEY CLUSTERED ([SalesLedgerID])
GO
CREATE NONCLUSTERED INDEX [IX_Company_SalesDueDate] ON [dw].[SalesLedger] ([Company], [SalesDueDate] DESC)
GO
CREATE NONCLUSTERED INDEX [IX_Company_SalesInvoiceDate] ON [dw].[SalesLedger] ([Company], [SalesInvoiceDate] DESC)
GO
