/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dw].[SalesOrderLog]
(
[SalesOrderLogID] [binary] (32) NOT NULL,
[CompanyID] [binary] (32) NULL,
[CustomerID] [binary] (32) NULL,
[PartID] [binary] (32) NULL,
[WarehouseID] [binary] (32) NULL,
[SalesOrderDateID] [int] NOT NULL,
[PartitionKey] [varchar] (50) NULL,
[Company] [nvarchar] (8) NULL,
[CustomerNum] [nvarchar] (50) NULL,
[SalesOrderNum] [nvarchar] (50) NULL,
[SalesOrderLine] [nvarchar] (50) NULL,
[SalesOrderSubLine] [nvarchar] (50) NULL,
[SalesOrderType] [nvarchar] (50) NULL,
[SalesOrderLogType] [nvarchar] (50) NULL,
[SalesOrderDate] [date] NULL,
[SalesOrderLogDate] [date] NOT NULL,
[SalesInvoiceNum] [nvarchar] (50) NULL,
[SalesOrderQty] [decimal] (18, 4) NULL,
[UoM] [nvarchar] (50) NULL,
[UnitPrice] [decimal] (18, 4) NULL,
[UnitCost] [decimal] (18, 4) NULL,
[Currency] [nvarchar] (50) NULL,
[ExchangeRate] [decimal] (18, 4) NULL,
[OpenRelease] [nvarchar] (50) NULL,
[DiscountPercent] [decimal] (18, 4) NULL,
[DiscountAmount] [decimal] (18, 4) NULL,
[PartNum] [nvarchar] (50) NULL,
[PartType] [nvarchar] (100) NULL,
[SalesPersonName] [nvarchar] (100) NULL,
[Department] [nvarchar] (100) NULL,
[ReturnComment] [nvarchar] (max) NULL,
[SalesReturnInvoiceNum] [nvarchar] (50) NULL,
[CancellationCode] [nvarchar] (50) NULL,
[WarehouseCode] [nvarchar] (50) NULL,
[IndexKey] [nvarchar] (50) NOT NULL,
[SORes1] [nvarchar] (100) NULL,
[SORes2] [nvarchar] (100) NULL,
[SORes3] [nvarchar] (100) NULL,
[is_deleted] [bit] NULL
)
GO
ALTER TABLE [dw].[SalesOrderLog] ADD CONSTRAINT [PK_SalesOrderLog_1] PRIMARY KEY CLUSTERED ([SalesOrderLogID])
GO
CREATE NONCLUSTERED INDEX [IX_Company_SalesOrderLogDate] ON [dw].[SalesOrderLog] ([Company], [SalesOrderLogDate] DESC)
GO
