/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dw].[StockBalance]
(
[ItemWarehouseID] [binary] (32) NOT NULL,
[WarehouseCode] [nvarchar] (50) NOT NULL,
[Currency] [nvarchar] (10) NULL,
[Company] [nvarchar] (8) NOT NULL,
[BinNum] [nvarchar] (50) NULL,
[BatchNum] [nvarchar] (50) NULL,
[SupplierNum] [nvarchar] (50) NULL,
[PartNum] [nvarchar] (50) NULL,
[DelivTime] [smallint] NULL,
[LastStockTakeDate] [date] NULL,
[LastStdCostCalDate] [date] NULL,
[SafetyStock] [decimal] (18, 4) NULL,
[MaxStockQty] [decimal] (18, 4) NULL,
[StockBalance] [decimal] (18, 4) NULL,
[StockValue] [decimal] (18, 4) NULL,
[ReserveQty] [decimal] (18, 4) NULL,
[BackOrderQty] [decimal] (18, 4) NULL,
[OrderQty] [decimal] (18, 4) NULL,
[StockTakeDiff] [decimal] (18, 4) NULL,
[ReOrderLevel] [decimal] (18, 4) NULL,
[OptimalOrderQty] [decimal] (18, 4) NULL,
[AvgCost] [decimal] (18, 4) NULL CONSTRAINT [DF__StockBala__AvgCo__32DFF7D2] DEFAULT ((0)),
[ItemWarehouseCode] [nvarchar] (200) NULL,
[SBRes1] [nvarchar] (100) NULL,
[SBRes2] [nvarchar] (100) NULL,
[SBRes3] [nvarchar] (100) NULL,
[CompanyID] [binary] (32) NULL,
[SupplierID] [binary] (32) NULL,
[PartID] [binary] (32) NULL,
[WarehouseID] [binary] (32) NULL,
[PartitionKey] [nvarchar] (50) NOT NULL,
[is_deleted] [bit] NULL,
[ExchangeRate] [decimal] (18, 4) NULL,
[SalesRemainingQty] [decimal] (18, 4) NULL,
[PurchaseRemainingqty] [decimal] (18, 4) NULL,
[IsActiveRecord] [bit] NULL,
[is_inferred] [bit] NULL
)
GO
ALTER TABLE [dw].[StockBalance] ADD CONSTRAINT [PK_StockBalance] PRIMARY KEY CLUSTERED ([ItemWarehouseID])
GO
