/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dw].[StockTransaction]
(
[StockTransactionID] [binary] (32) NOT NULL,
[Company] [nvarchar] (8) NOT NULL,
[WarehouseCode] [nvarchar] (50) NULL,
[TransactionCode] [nvarchar] (50) NULL,
[TransactionDescription] [nvarchar] (max) NULL,
[IssuerReceiverNum] [nvarchar] (50) NULL,
[OrderNum] [nvarchar] (50) NULL,
[OrderLine] [nvarchar] (50) NULL,
[InvoiceNum] [nvarchar] (50) NULL,
[InvoiceLine] [nvarchar] (50) NULL,
[PartNum] [nvarchar] (50) NOT NULL,
[BinNum] [nvarchar] (50) NULL,
[BatchNum] [nvarchar] (50) NULL,
[TransactionDate] [date] NULL,
[TransactionTime] [nvarchar] (10) NULL,
[TransactionQty] [decimal] (18, 4) NULL,
[TransactionValue] [decimal] (18, 4) NULL,
[CostPrice] [decimal] (18, 4) NULL,
[SalesUnitPrice] [decimal] (18, 4) NULL,
[Currency] [nvarchar] (10) NULL,
[Reference] [nvarchar] (50) NULL,
[AdjustmentDate] [date] NULL,
[STRes1] [nvarchar] (100) NULL,
[STRes2] [nvarchar] (100) NULL,
[STRes3] [nvarchar] (100) NULL,
[CompanyID] [binary] (32) NULL,
[PartID] [binary] (32) NULL,
[WarehouseID] [binary] (32) NULL,
[PurchaseInvoiceID] [binary] (32) NULL,
[PurchaseOrderNumID] [binary] (32) NULL,
[SalesOrderNumID] [binary] (32) NULL,
[SalesInvoiceID] [binary] (32) NULL,
[CustomerID] [binary] (32) NULL,
[SupplierID] [binary] (32) NULL,
[CurrencyID] [binary] (32) NULL,
[PartitionKey] [nvarchar] (50) NOT NULL,
[IndexKey] [nvarchar] (50) NULL,
[InternalExternal] [nvarchar] (50) NULL,
[is_deleted] [bit] NULL,
[IsInternalTransaction] [bit] NULL,
[CustomerNum] [nvarchar] (50) NULL,
[SupplierNum] [nvarchar] (50) NULL,
[SalesOrderNum] [nvarchar] (50) NULL,
[SalesOrderLine] [nvarchar] (50) NULL,
[PurchaseOrderNum] [nvarchar] (50) NULL,
[PurchaseOrderLine] [nvarchar] (50) NULL,
[SalesInvoiceNum] [nvarchar] (50) NULL,
[SalesInvoiceLine] [nvarchar] (50) NULL,
[PurchaseInvoiceNum] [nvarchar] (50) NULL,
[PurchaseInvoiceLine] [nvarchar] (50) NULL,
[ExchangeRate] [decimal] (18, 4) NULL,
[IsActiveRecord] [bit] NULL
)
GO
ALTER TABLE [dw].[StockTransaction] ADD CONSTRAINT [PK_StockTransaction] PRIMARY KEY CLUSTERED ([StockTransactionID])
GO
CREATE NONCLUSTERED INDEX [nci_wi_Company] ON [dw].[StockTransaction] ([Company])
GO
CREATE NONCLUSTERED INDEX [IX_Company_TransactionDate] ON [dw].[StockTransaction] ([Company], [TransactionDate] DESC)
GO
CREATE NONCLUSTERED INDEX [nci_wi_StockTransaction] ON [dw].[StockTransaction] ([PartitionKey])
GO
