/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dw].[SupplierAgreement]
(
[SupplierAgreementID] [binary] (32) NOT NULL,
[Company] [nvarchar] (8) NOT NULL,
[SupplierNum] [nvarchar] (50) NOT NULL,
[PartNum] [nvarchar] (50) NOT NULL,
[AgreementCode] [nvarchar] (50) NULL,
[AgreementDescription] [nvarchar] (max) NULL,
[DiscountPercent] [decimal] (18, 4) NULL,
[UnitPrice] [decimal] (18, 4) NULL,
[UoM] [nvarchar] (50) NULL,
[AgreementQty] [decimal] (18, 4) NULL,
[FulfilledQty] [decimal] (18, 4) NULL,
[RemainingQty] [decimal] (18, 4) NULL,
[Currency] [nvarchar] (10) NULL,
[DelivTime] [smallint] NULL,
[AgreementStart] [date] NULL,
[AgreementEnd] [date] NULL,
[SupplierTerms] [nvarchar] (50) NULL,
[SARes1] [nvarchar] (100) NULL,
[SARes2] [nvarchar] (100) NULL,
[SARes3] [nvarchar] (100) NULL,
[CompanyID] [binary] (32) NULL,
[SupplierID] [binary] (32) NULL,
[CurrencyID] [binary] (32) NULL,
[PartID] [binary] (32) NULL,
[PartitionKey] [nvarchar] (50) NOT NULL,
[is_deleted] [bit] NULL,
[is_inferred] [bit] NULL,
[AgreementResponsible] [nvarchar] (100) NULL,
[IsActiveRecord] [bit] NULL
)
GO
ALTER TABLE [dw].[SupplierAgreement] ADD CONSTRAINT [PK_SupplierAgreement] PRIMARY KEY NONCLUSTERED ([SupplierAgreementID])
GO
