/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dw].[Warehouse]
(
[WarehouseID] [binary] (32) NOT NULL,
[Company] [nvarchar] (50) NOT NULL,
[WarehouseCode] [nvarchar] (50) NULL,
[WarehouseName] [nvarchar] (100) NULL,
[WarehouseDistrict] [nvarchar] (100) NULL,
[WarehouseAddress] [nvarchar] (200) NULL,
[WarehouseDescription] [nvarchar] (max) NULL,
[WarehouseType] [nvarchar] (50) NULL,
[WarehouseCountry] [nvarchar] (100) NULL,
[WarehouseSite] [nvarchar] (100) NULL,
[PartitionKey] [nvarchar] (50) NULL,
[is_deleted] [bit] NULL,
[is_inferred] [bit] NULL,
[IsActiveRecord] [bit] NULL,
[WhRes1] [nvarchar] (100) NULL,
[WhRes2] [nvarchar] (100) NULL,
[WhRes3] [nvarchar] (100) NULL,
[ZipCode] [nvarchar] (8) NULL,
[City] [nvarchar] (100) NULL,
[State] [nvarchar] (50) NULL,
[CountryCode] [nvarchar] (50) NULL
)
GO
ALTER TABLE [dw].[Warehouse] ADD CONSTRAINT [PK_Warehouse] PRIMARY KEY NONCLUSTERED ([WarehouseID])
GO
