/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[AllDates]
(
[DateID] [int] NOT NULL,
[Date] [date] NOT NULL,
[WeekDayNo] [int] NOT NULL,
[DateCounter] [bigint] NOT NULL,
[YearMonthCounter] [bigint] NOT NULL,
[YearQuarterCounter] [bigint] NOT NULL
)
GO
