/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[AxInterFinansCustomer]
(
[Prop0] [int] NULL,
[email] [nvarchar] (max) NULL,
[address1] [nvarchar] (max) NULL,
[address2] [nvarchar] (max) NULL,
[Land] [nvarchar] (50) NULL,
[OU] [nvarchar] (50) NULL,
[MD] [nvarchar] (50) NULL,
[Created] [date] NULL
)
GO
