/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[AzureSQLMaintenanceLog]
(
[id] [bigint] NOT NULL IDENTITY(1, 1),
[OperationTime] [datetime2] NULL,
[command] [varchar] (4000) NULL,
[ExtraInfo] [varchar] (4000) NULL,
[StartTime] [datetime2] NULL,
[EndTime] [datetime2] NULL,
[StatusMessage] [varchar] (1000) NULL
)
GO
ALTER TABLE [dbo].[AzureSQLMaintenanceLog] ADD CONSTRAINT [PK__AzureSQL__3213E83F1D80957F] PRIMARY KEY CLUSTERED ([id])
GO
