/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[Calculations]
(
[Col1] [nvarchar] (max) NULL,
[Col2] [nvarchar] (max) NULL,
[Col3] [nvarchar] (max) NULL,
[Col4] [nvarchar] (max) NULL,
[Col5] [nvarchar] (max) NULL
)
GO
