/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[Company]
(
[Company] [nvarchar] (8) NOT NULL,
[CompanyName] [nvarchar] (max) NULL,
[CompanyLegalName] [nvarchar] (max) NULL,
[CompanyERPGroup] [nvarchar] (50) NULL,
[CompanyGroup] [nvarchar] (50) NULL,
[CompanyOwnerGroup] [nvarchar] (50) NULL,
[BusinessArea] [nvarchar] (50) NULL,
[Division] [nvarchar] (50) NULL,
[Country] [nvarchar] (150) NULL,
[Currency] [nvarchar] (50) NULL,
[CompanyShortO365] [nvarchar] (50) NULL,
[CompanyShort] [nvarchar] (50) NULL,
[CompanyShortAD] [nvarchar] (50) NULL,
[CompanyCode] [nvarchar] (50) NULL,
[FromPeriod] [nvarchar] (8) NULL,
[Status] [nvarchar] (50) NULL,
[DateAdd] [date] NULL,
[ValidatedSales] [nvarchar] (50) NULL,
[ValidatedPurchase] [nvarchar] (50) NULL,
[Comments] [nvarchar] (max) NULL,
[CompanyLogo] [nvarchar] (max) NULL
)
GO
ALTER TABLE [dbo].[Company] ADD CONSTRAINT [PK_Company] PRIMARY KEY CLUSTERED ([Company])
GO
