/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[Country]
(
[CountryName] [nvarchar] (80) NULL,
[CountryNameFormer] [varchar] (50) NULL,
[ISOAlpha3Code] [varchar] (3) NULL,
[ISOAlpha2Code] [varchar] (2) NULL,
[M49Code] [varchar] (20) NULL,
[Continent] [varchar] (30) NULL,
[Region] [varchar] (40) NULL,
[Region2] [varchar] (50) NULL,
[RiskLevel] [varchar] (20) NULL,
[EUMember] [bit] NULL,
[CurrencyDescription] [varchar] (50) NULL,
[CurencyCode] [varchar] (5) NULL,
[CurrencyDescription2] [varchar] (25) NULL,
[CurrencyCode2] [varchar] (8) NULL,
[CurrencyDescription3] [varchar] (25) NULL,
[CurrencyCode3] [varchar] (8) NULL
)
GO
