/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[DnB_Customer]
(
[CustomerID] [binary] (32) NOT NULL,
[Company] [nvarchar] (8) NOT NULL,
[CustomerNum] [nvarchar] (50) NOT NULL,
[MainCustomerName] [nvarchar] (100) NULL,
[CustomerName] [nvarchar] (100) NULL,
[AddressLine1] [nvarchar] (100) NULL,
[AddressLine2] [nvarchar] (100) NULL,
[AddressLine3] [nvarchar] (100) NULL,
[TelephoneNum1] [nvarchar] (50) NULL,
[TelephoneNum2] [nvarchar] (50) NULL,
[Email] [nvarchar] (100) NULL,
[ZipCode] [nvarchar] (50) NULL,
[City] [nvarchar] (50) NULL,
[State] [nvarchar] (50) NULL,
[SalesDistrict] [nvarchar] (50) NULL,
[CountryName] [nvarchar] (50) NULL,
[Division] [nvarchar] (50) NULL,
[CustomerIndustry] [nvarchar] (50) NULL,
[CustomerSubIndustry] [nvarchar] (50) NULL,
[AddressLine] [nvarchar] (250) NULL,
[FullAddressLine] [nvarchar] (500) NULL,
[CustomerGroup] [nvarchar] (50) NULL,
[CustomerSubGroup] [nvarchar] (50) NULL,
[SalesPersonCode] [nvarchar] (50) NULL,
[SalesPersonName] [varchar] (100) NULL,
[SalesPersonResponsible] [nvarchar] (100) NULL,
[VATNum] [nvarchar] (50) NULL,
[OrganizationNum] [nvarchar] (100) NULL,
[AccountNum] [nvarchar] (50) NULL,
[InternalExternal] [nvarchar] (50) NULL,
[CustomerScore] [nvarchar] (20) NULL,
[CustomerType] [nvarchar] (50) NULL,
[inferred_member] [bit] NULL
)
GO
ALTER TABLE [dbo].[DnB_Customer] ADD CONSTRAINT [PK_Customer] PRIMARY KEY CLUSTERED ([CustomerID])
GO
