/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[ignoreTableColumns]
(
[stageTableName] [varchar] (50) NOT NULL,
[columnName] [varchar] (50) NOT NULL
)
GO
CREATE NONCLUSTERED INDEX [IX_Company_PurchaseInvoiceDate] ON [dbo].[ignoreTableColumns] ([stageTableName])
GO
