/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[logError]
(
[id] [int] NOT NULL IDENTITY(1, 1),
[parent_id] [int] NOT NULL,
[pipelineName] [varchar] (100) NOT NULL,
[stepName] [varchar] (100) NOT NULL,
[errorName] [nvarchar] (max) NOT NULL
)
GO
ALTER TABLE [dbo].[logError] ADD CONSTRAINT [PK__logError__3213E83F3D8FDB7A] PRIMARY KEY CLUSTERED ([id])
GO
