/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[MasterSourceTable]
(
[CompanyName] [nvarchar] (30) NULL,
[CompanyApiCode] [nvarchar] (100) NULL,
[ApiCall] [nvarchar] (50) NULL,
[SourceSystemName] [nvarchar] (50) NULL,
[SourceServerName] [nvarchar] (70) NULL,
[SourceDatabaseName] [nvarchar] (30) NULL,
[SourceSchemaName] [varchar] (12) NULL,
[SourceTableName] [varchar] (60) NULL,
[SourceSelectStatement] [nvarchar] (max) NULL,
[DeltaLoadStatement] [nvarchar] (max) NULL,
[IsActive] [bit] NULL,
[BlobContainerName] [varchar] (50) NULL,
[BlobFilePath] [varchar] (50) NULL,
[BlobFileName] [varchar] (50) NULL,
[StageDatabaseName] [nvarchar] (30) NULL,
[StageSchemaName] [varchar] (12) NULL,
[StageTableName] [varchar] (60) NULL,
[StageViewName] [varchar] (60) NULL,
[SinkDatabaseName] [nvarchar] (30) NULL,
[SinkSchemaName] [varchar] (12) NULL,
[SinkTableName] [varchar] (60) NULL,
[SinkTablePK] [varchar] (25) NULL,
[SinkDynamicMapping] [nvarchar] (max) NULL
)
GO
