/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[PTSourceTables_NOMO_dev]
(
[SourceSystem] [nvarchar] (50) NULL,
[SourceSelectStatement] [nvarchar] (max) NULL,
[blobfilepath] [nvarchar] (50) NULL,
[blobfilename] [nvarchar] (50) NULL,
[Stagetablename] [nvarchar] (50) NULL,
[StoredProcedure] [nvarchar] (50) NULL,
[dwtablename] [nvarchar] (50) NULL,
[DeltaLoadStatement] [nvarchar] (max) NULL,
[DeltaLoadValue] [varchar] (50) NULL,
[DeltaLoadGetNewValue] [varchar] (max) NULL,
[isActive] [nvarchar] (50) NULL,
[dwFilterColumnName] [varchar] (50) NULL,
[dwtablename_schema] [varchar] (8) NULL,
[Company] [varchar] (20) NULL,
[sourceFilterColumnName] [nvarchar] (max) NULL,
[dailyDatePart] [varchar] (20) NULL,
[weeklyDatePart] [varchar] (20) NULL,
[dailyNumber] [varchar] (20) NULL,
[weeklyNumber] [varchar] (20) NULL
)
GO
