/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[SalesBudget_Widni]
(
[Company] [nvarchar] (8) NULL,
[YearMonth] [date] NULL,
[Year] [nvarchar] (50) NULL,
[Month] [nvarchar] (50) NULL,
[BudgetSales] [decimal] (18, 4) NULL,
[BudgetProfit] [decimal] (18, 4) NULL,
[BudgetMargin] [decimal] (18, 4) NULL,
[ProductGroup] [nvarchar] (50) NULL,
[SalesPersonName] [nvarchar] (1) NULL,
[CustomerGroup] [nvarchar] (1) NULL,
[ProductGroupKey] [nvarchar] (50) NULL,
[SalesPersonKey] [nvarchar] (1) NULL,
[CustomerKey] [nvarchar] (1) NULL
)
GO
