/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[SalesBudget_Nomo]
(
[Company] [nvarchar] (50) NULL,
[YearMonth] [date] NULL,
[CustomerNum] [nvarchar] (50) NULL,
[CustomerGroup] [nvarchar] (50) NULL,
[SalesPersonName] [nvarchar] (100) NULL,
[ProductGroup] [nvarchar] (50) NULL,
[ProjectNum] [nvarchar] (50) NULL,
[BudgetSales] [decimal] (18, 4) NULL,
[BudgetCost] [decimal] (18, 4) NULL,
[BudgetDescription] [nvarchar] (max) NULL
)
GO
