/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[SourceTables_BusinessCentral]
(
[SourceSystem] [nvarchar] (50) NULL,
[CompanyAPICode] [nvarchar] (50) NULL,
[APICall] [nvarchar] (100) NULL,
[TableLoadOrder] [int] NULL,
[DeltaLoadStatement] [nvarchar] (max) NULL,
[DeltaLoadValue] [nvarchar] (50) NULL,
[DeltaLoadGetNewValue] [nvarchar] (max) NULL,
[IsActive] [int] NULL,
[blobcontainer] [nvarchar] (100) NULL,
[blobfilepath] [nvarchar] (100) NULL,
[blobfilename] [nvarchar] (100) NULL,
[SinkDatabase] [nvarchar] (100) NULL,
[SinkTableSchema] [nvarchar] (100) NULL,
[SinkTableName] [nvarchar] (100) NULL,
[SinkDynamicMapping] [varchar] (max) NULL,
[CompanyName] [varchar] (30) NULL
)
GO
