/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[SourceTables_Sharepoint]
(
[Company] [nvarchar] (50) NULL,
[SP_relativepath] [nvarchar] (200) NULL,
[SP_filename] [nvarchar] (200) NULL,
[SP_filesheetname] [nvarchar] (200) NULL,
[TableLoadOrder] [int] NULL,
[IsActive] [int] NULL,
[DeltaLoadStatement] [nvarchar] (max) NULL,
[DeltaLoadValue] [nvarchar] (50) NULL,
[DeltaLoadGetNewValue] [nvarchar] (max) NULL,
[blobcontainer] [nvarchar] (200) NULL,
[blobfilepath] [nvarchar] (200) NULL,
[blobfilename] [nvarchar] (200) NULL,
[Stagetablename] [nvarchar] (50) NULL,
[StoredProcedure] [nvarchar] (50) NULL,
[dwtablename] [nvarchar] (50) NULL,
[SetSource_SP] [nvarchar] (200) NULL,
[dwFilterColumnName] [varchar] (50) NULL,
[dwtablename_schema] [varchar] (8) NULL
)
GO
