/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[statsBefore]
(
[ObjectSchema] [nvarchar] (128) NULL,
[ObjectName] [nvarchar] (128) NULL,
[object_id] [int] NOT NULL,
[stats_id] [int] NOT NULL,
[StatsName] [nvarchar] (128) NULL,
[last_updated] [datetime2] NULL,
[rows] [bigint] NULL,
[rows_sampled] [bigint] NULL,
[modification_counter] [bigint] NULL,
[type] [tinyint] NULL,
[type_desc] [nvarchar] (60) NULL,
[SkipStatistics] [int] NOT NULL
)
GO
