/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[table_record]
(
[name_table] [nvarchar] (32) NULL,
[type_table] [nvarchar] (32) NULL,
[inferred_status] [nvarchar] (32) NULL
)
GO
