/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[TargetProducts]
(
[ProductID] [int] NOT NULL,
[ProductName] [varchar] (50) NULL,
[Price] [decimal] (9, 2) NULL,
[company] [varchar] (10) NULL,
[fecha] [date] NULL,
[ISACTIVE] [bit] NULL
)
GO
ALTER TABLE [dbo].[TargetProducts] ADD CONSTRAINT [PK__TargetPr__B40CC6ED5B82C752] PRIMARY KEY CLUSTERED ([ProductID])
GO
