/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[test_tomas]
(
[Id] [int] NOT NULL
)
GO
ALTER TABLE [dbo].[test_tomas] ADD CONSTRAINT [PK__test_tom__3214EC072A2CCBF2] PRIMARY KEY CLUSTERED ([Id])
GO
