/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[think]
(
[PartID] [binary] (32) NULL,
[CustomerID] [binary] (32) NULL,
[WarehouseID] [binary] (32) NULL,
[company] [nvarchar] (32) NULL,
[is_inferred] [bit] NULL,
[sourceFilterColumnName] [varchar] (20) NULL,
[dailyDatePart] [varchar] (20) NULL,
[weeklyDatePart] [varchar] (20) NULL,
[dailyNumber] [varchar] (20) NULL,
[weeklyNumber] [varchar] (20) NULL
)
GO
