/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE ROLE [CoC_InternalUsers]
AUTHORIZATION [guest]
GO
ALTER ROLE [CoC_InternalUsers] ADD MEMBER [Joan_Ruiz]
GO
ALTER ROLE [CoC_InternalUsers] ADD MEMBER [joel_bjorck]
GO
