/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

ALTER ROLE [db_datareader] ADD MEMBER [sql-admin-ALL]
GO
ALTER ROLE [db_datareader] ADD MEMBER [sql-admin-AX]
GO
ALTER ROLE [db_datareader] ADD MEMBER [sql-admin-DS]
GO
ALTER ROLE [db_datareader] ADD MEMBER [sql-admin-FH]
GO
ALTER ROLE [db_datareader] ADD MEMBER [sql-admin-IN]
GO
ALTER ROLE [db_datareader] ADD MEMBER [sql-admin-LS]
GO
ALTER ROLE [db_datareader] ADD MEMBER [sql-admin-PT]
GO
ALTER ROLE [db_datareader] ADD MEMBER [sql-admin-TS]
GO
