IF OBJECT_ID('[stage].[vSKS_FI_PurchaseOrder]') IS NOT NULL
	DROP VIEW [stage].[vSKS_FI_PurchaseOrder];

GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE VIEW [stage].[vSKS_FI_PurchaseOrder] AS
WITH CTE AS (
SELECT
	  CAST( CASE WHEN EKORG IN ('FI25', 'FI26') THEN 'SCOFI'
			WHEN EKORG = 'FI20' THEN 'SMKFI'
			WHEN EKORG = 'SE10' THEN 'SKSSWE'
			END AS nvarchar(10)) AS Company
			,[PartitionKey], [EKORG], [PURCHASEORDERNUM], [PURCHASEORDERLINE], [PURCHASEORDERSUBLINE], [ORDERTYPE], [PURCHASEORDERDATE], [ORGREQDELIVDATE], [COMMITEDDELIVDATE], [DELIVDATE], [REQDELIVDATE], [INVOICENUM], [PARTNUM], [SUPPLIERNUM], [DELIVCUSTNUM], [ITEMSTATUS], [ORDEREDQTY], [RECEIVEDQTY], [INVOICEDQTY], [UNIT], [UNITPRICE], [DISCOUNTPERCENT], [DISCOUNTAMOUNT], [EXCHANGERATE], [CURRENCY], [PURCHASERNAME], [WAREHOUSECODE], [RECIEVINGNUM], [LEADTIME], [PURCHASECHANNEL], [COMMENTS], [PORES1], [PORES2], [PORES3], [MANDT], [BUKRS], [SURCHARGEAMOUNT], [ETENR], [ZZSHIPDT], [EINDT], [COMMITEDDATESKS]
FROM 
	[stage].[SKS_FI_PurchaseOrder]
	WHERE EKORG NOT IN ('FI00','SE10')
)
--ADD UPPER()TRIM()INTO PartID,CustomerID,WarehouseID 2022-12-16 VA
--ADD TRIM() UPPER() INTO SupplierID 23-01-24 VA
SELECT
	CONVERT([binary](32), HASHBYTES('SHA2_256', CONCAT(Company, '#', TRIM(PURCHASEORDERNUM), '#', TRIM(PURCHASEORDERLINE), '#', TRIM(ETENR)))) AS PurchaseOrderID 
	,CONVERT([binary](32), HASHBYTES('SHA2_256', CONCAT(Company, '#', TRIM(PURCHASEORDERNUM)))) AS PurchaseOrderNumID
	,CONVERT([binary](32), HASHBYTES('SHA2_256', CONCAT(Company, '#', TRIM(INVOICENUM)))) AS PurchaseInvoiceID
	--,CONVERT([binary](32), HASHBYTES('SHA2_256', CONCAT(Company, '#', TRIM(DELIVCUSTNUM), '#', EKORG ))) AS CustomerID
	,CONVERT([binary](32), HASHBYTES('SHA2_256',UPPER(CONCAT(TRIM(Company), '#', TRIM(DELIVCUSTNUM), '#', TRIM(EKORG))))) AS CustomerID
	,CONVERT([binary](32), HASHBYTES('SHA2_256',UPPER(CONCAT(TRIM(Company), '#', TRIM(SUPPLIERNUM), '#', TRIM(EKORG))))) AS SupplierID
	--,CONVERT([binary](32), HASHBYTES('SHA2_256', CONCAT(Company, '#', TRIM(SUPPLIERNUM), '#', EKORG ))) AS SupplierID
	,CONVERT([binary](32), HASHBYTES('SHA2_256',UPPER(CONCAT(TRIM(Company), '#', TRIM(PARTNUM), '#', TRIM(EKORG))))) AS PartID
	--,CONVERT([binary](32), HASHBYTES('SHA2_256', CONCAT(Company, '#', TRIM(PARTNUM), '#', EKORG ))) AS PartID
	,CONVERT([binary](32), HASHBYTES('SHA2_256',UPPER(CONCAT(TRIM(Company), '#', TRIM(WAREHOUSECODE))))) AS WarehouseID
	--,CONVERT([binary](32), HASHBYTES('SHA2_256', CONCAT(Company, '#', TRIM(WAREHOUSECODE)))) AS WarehouseID
	,CONVERT([binary](32), HASHBYTES('SHA2_256', Company )) AS CompanyID
	,CONVERT([binary](32), HASHBYTES('SHA2_256', TRIM(Currency))) AS CurrencyID
	,CONCAT(EKORG, '#', TRIM(SUPPLIERNUM) ,'#', PURCHASEORDERNUM, '#', PURCHASEORDERLINE, '#', TRIM(INVOICENUM)) AS PurchaseOrderCode
	,PartitionKey AS PartitionKey

	,Company AS Company
	,TRIM(PURCHASEORDERNUM) AS PurchaseOrderNum
	,TRIM(PURCHASEORDERLINE) AS PurchaseOrderLine
	,CASE WHEN  PORES3 IN ('0') THEN 'Standard'
		WHEN  PORES3 IN ('1') THEN 'Limit'
		WHEN  PORES3 IN ('2') THEN 'Consignment'
		WHEN  PORES3 IN ('3') THEN 'Subcontracting'
		WHEN  PORES3 IN ('4') THEN 'Material unknown'
		WHEN  PORES3 IN ('5') THEN 'Third-party (S)'
		WHEN  PORES3 IN ('6') THEN 'Text'
		WHEN  PORES3 IN ('7') THEN 'Stock transfer'
		WHEN  PORES3 IN ('8') THEN 'Material group'
		WHEN  PORES3 IN ('9') THEN 'Service'
		END AS PurchaseOrderSubLine
	,TRIM(ORDERTYPE) AS PurchaseOrderType
	,CASE WHEN (TRIM(ORDERTYPE) = 'ZEXP' or PORES3=5) and INVOICEDQTY >= ORDEREDQTY THEN 'Closed'
	      WHEN ORDEREDQTY - RECEIVEDQTY > 0 THEN 'Open'
		  ELSE 'Closed'
	  END AS PurchaseOrderStatus --  changed 2023-03-21 SB (requested by Katri)  IIF(ORDEREDQTY - RECEIVEDQTY > 0, 'Open','Closed')  AS PurchaseOrderStatus
	,CONVERT(date, IIF(PURCHASEORDERDATE = '00000000', '1900-01-01', PURCHASEORDERDATE)) AS PurchaseOrderDate
	,CONVERT(date, IIF(ZZSHIPDT = '00000000', '1900-01-01', ZZSHIPDT)) AS OrgReqDelivDate -- Is the requested delivery date when it should be shipped from supplier
	,CONVERT(date, IIF(COMMITEDDATESKS = '00000000', '1900-01-01', COMMITEDDATESKS)) AS CommittedDelivDate -- Is with travel
	,CONVERT(date, IIF(REQDELIVDATE = '00000000', '1900-01-01', REQDELIVDATE)) AS ActualDelivDate
	,CONVERT(date, IIF(DELIVDATE = '00000000', '1900-01-01', DELIVDATE)) AS ExpDelivDate 
	,CONVERT(date, IIF(EINDT = '00000000', '1900-01-01', EINDT)) AS ReqDelivDate -- Is the requested delivery date when it sould be delivered at sks
	,TRIM(INVOICENUM) AS PurchaseInvoiceNum
	,IIF(ISNUMERIC([PARTNUM]) = 1,CAST(CAST(trim([PARTNUM]) AS int)as nvarchar(50)),(trim([PARTNUM])))AS PartNum
	,TRIM(SUPPLIERNUM) AS SupplierNum
	,TRIM(ETENR) AS SupplierPartNum  --partial delivery number
	--,'' AS [SupplierInvoiceNum] 
	,TRIM(DELIVCUSTNUM) AS DelivCustomerNum
	,ITEMSTATUS AS PartStatus
	,ORDEREDQTY AS PurchaseOrderQty
	,IIF(PORES3 IN('5'),INVOICEDQTY,RECEIVEDQTY) AS ReceiveQty
	,INVOICEDQTY AS InvoiceQty
	--,NULL AS MinOrderQty
	,UNIT AS UoM
	,UNITPRICE AS UnitPrice
	,DISCOUNTPERCENT AS DiscountPercent
	,DISCOUNTAMOUNT AS DiscountAmount
	--,NULL AS LandedCost
	,COALESCE(1/NULLIF(EXCHANGERATE,0),1) AS ExchangeRate
	,CASE WHEN CURRENCY = '15' THEN 'EUR' WHEN CURRENCY = '2' THEN 'USD' ELSE CURRENCY END AS Currency
	,TRIM(PURCHASERNAME) AS PurchaserName
	,TRIM(WAREHOUSECODE) AS WarehouseCode
	,RECIEVINGNUM AS ReceivingNum
	,LEADTIME AS DelivTime
	,PURCHASECHANNEL AS PurchaseChannel
	,CASE WHEN PORES2 = 'R' THEN 'Return' END AS Documents
	,CASE WHEN PORES1 = 'F' THEN 'Free of charge' END AS Comments
	,PORES1 AS PORes1
	,PORES2 AS PORes2
	,PORES3 AS PORes3
	,CONVERT(date, IIF(COMMITEDDELIVDATE = '00000000', '1900-01-01', COMMITEDDELIVDATE)) AS OrgCommittedDelivDate
FROM CTE
GROUP BY
	PartitionKey, EKORG, Company, PURCHASEORDERNUM, PURCHASEORDERLINE, PURCHASEORDERSUBLINE, SUPPLIERNUM, DELIVCUSTNUM, INVOICENUM, PARTNUM, ORDERTYPE, DISCOUNTPERCENT, DISCOUNTAMOUNT, ORDEREDQTY, RECEIVEDQTY, INVOICEDQTY, EXCHANGERATE, CURRENCY, PURCHASERNAME, RECIEVINGNUM, LEADTIME, WAREHOUSECODE, PURCHASECHANNEL, PORES1, PORES2, PORES3, UNIT, UNITPRICE, ITEMSTATUS, COMMENTS, PURCHASEORDERDATE, ORGREQDELIVDATE, COMMITEDDELIVDATE, DELIVDATE, REQDELIVDATE,CTE.ZZSHIPDT, cte.COMMITEDDATESKS, cte.EINDT, cte.ETENR
  --cte.Company
	 -- ,cte.[PartitionKey]
	 -- ,cte.[EKORG]
  --    ,cte.[PURCHASEORDERNUM]
  --    ,cte.[PURCHASEORDERLINE]
  --    ,cte.[PURCHASEORDERSUBLINE]
  --    ,cte.[ORDERTYPE]
  --    ,cte.[PURCHASEORDERDATE]
  --    ,cte.[ORGREQDELIVDATE]
  --    ,cte.[COMMITEDDELIVDATE]
  --    ,cte.[DELIVDATE]
  --    ,cte.[REQDELIVDATE]
  --    ,cte.[INVOICENUM]
  --    ,cte.[PARTNUM]
  --    ,cte.[SUPPLIERNUM]
  --    ,cte.[DELIVCUSTNUM]
  --    ,cte.[ITEMSTATUS]
  --    ,cte.[ORDEREDQTY]
  --    ,cte.[RECEIVEDQTY]
  --    ,cte.[INVOICEDQTY]
  --    ,cte.[UNIT]
  --    ,cte.[UNITPRICE]
  --    ,cte.[DISCOUNTPERCENT]
  --    ,cte.[DISCOUNTAMOUNT]
  --    ,cte.[EXCHANGERATE]
  --    ,cte.[CURRENCY]
  --    ,cte.[PURCHASERNAME]
  --    ,cte.[WAREHOUSECODE]
  --    ,cte.[RECIEVINGNUM]
  --    ,cte.[LEADTIME]
  --    ,cte.[PURCHASECHANNEL]
  --    ,cte.[COMMENTS]
  --    ,cte.[PORES1]
  --    ,cte.[PORES2]
  --    ,cte.[PORES3]
  --    ,cte.[MANDT]
	 -- ,CTE.ZZSHIPDT
	 -- ,CTE.COMMITEDDATESKS
	 -- ,CTE.EINDT
GO
