IF OBJECT_ID('[stage].[vSKS_FI_OLine]') IS NOT NULL
	DROP VIEW [stage].[vSKS_FI_OLine];

GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO











CREATE VIEW [stage].[vSKS_FI_OLine] AS
--COMMENT EMPTY FIELDS // ADD TRIM()UPPER() INTO PartID,CustomerID,WarehouseID 2022-12-16 VA
--customarnum and partnum change 2023-02-15
SELECT
	CONVERT([binary](32), HASHBYTES('SHA2_256', CONCAT(COMPANY, '#', ORDERNUM, '#', ORDERLINE, '#', ORDERRELNUM, '#', TRIM([VKORG])))) AS SalesOrderID --Commented to remove duplicate rows in dw table /*'#', INVOICENUM,*/
	,CONVERT([binary](32), HASHBYTES('SHA2_256', COMPANY)) AS CompanyID
	--,CONVERT([binary](32), HASHBYTES('SHA2_256', CONCAT(COMPANY, '#', TRIM(IIF(CUSTNUM IS NULL OR CUSTNUM = '', 'MISSINGCUSTOMER', CUSTNUM)), '#', TRIM([VKORG])))) AS CustomerID
	,CONVERT([binary](32), HASHBYTES('SHA2_256', UPPER(CONCAT(TRIM(COMPANY), '#', TRIM(CUSTNUM), '#', TRIM([VKORG]))))) AS CustomerID
	--,CONVERT([binary](32), HASHBYTES('SHA2_256', CONCAT(COMPANY, '#', TRIM(IIF(PARTNUM IS NULL OR PARTNUM = '', 'MISSINGPART',  PARTNUM) ), '#', TRIM([VKORG])))) AS PartID 
	,CONVERT([binary](32), HASHBYTES('SHA2_256', UPPER(CONCAT(TRIM(COMPANY), '#', TRIM(PARTNUM), '#', TRIM([VKORG]))))) AS PartID 
	--,CONVERT([binary](32), HASHBYTES('SHA2_256', CONCAT(COMPANY, '#', TRIM(WAREHOUSECODE)))) AS WarehouseID
	,CONVERT([binary](32), HASHBYTES('SHA2_256',UPPER(CONCAT(TRIM(COMPANY), '#', TRIM(WAREHOUSECODE))))) AS WarehouseID
	,CONVERT([binary](32), HASHBYTES('SHA2_256', CONCAT(COMPANY, '#', TRIM(ORDERNUM)))) AS SalesOrderNumID
	,CONCAT(COMPANY, '#', ORDERNUM, '#', ORDERLINE, '#', INVOICENUM) AS SalesOrderCode
	,CONVERT(int, ORDERDATE) AS SalesOrderDateID 
	,CONVERT([binary](32), HASHBYTES('SHA2_256', CONCAT( Company, '#', PROJECTNUM) ))	AS ProjectID
	,PartitionKey 

	,CASE WHEN COMPANY = 'SKSSWE' THEN 'JSESKSSW' ELSE COMPANY END AS Company 
	,IIF(ISNUMERIC([CUSTNUM]) = 1,CAST(CAST(trim([CUSTNUM]) AS int)as nvarchar(50)),(trim([CUSTNUM]))) AS CustomerNum
	,trim(ORDERNUM) AS SalesOrderNum
	,ORDERLINE AS SalesOrderLine
	,ORDERSUBLINE AS SalesOrderSubLine
	,ORDERTYPE AS SalesOrderType
	--,'' AS SalesOrderCategory
	,ORDERRELNUM AS SalesOrderRelNum
	,CASE WHEN MAX(trim([ORDERDATE])) = '00000000' THEN CAST('19010101' AS date) ELSE CAST(MAX(trim([ORDERDATE])) AS date) END AS SalesOrderDate
	,CASE WHEN MIN(trim([NEEDBYDATE])) like '%.%' THEN CAST('19010101' AS date) WHEN MIN(trim([NEEDBYDATE])) = '00000000' THEN CAST('19010101' AS date) ELSE CAST(MIN(trim([NEEDBYDATE])) AS date) END AS NeedbyDate 
	,CASE WHEN MAX(trim(CONFIRMED_DEL_DATE)) = '00000000' THEN CAST('19010101' AS date) ELSE CAST(MAX(trim(CONFIRMED_DEL_DATE)) AS date) END AS ExpDelivDate
	,CAST(COALESCE(IIF(ACTUALDELIVERYDATE = '00000000', '19010101', ACTUALDELIVERYDATE), '1900-01-01') AS date) AS ActualDelivDate
	,CASE WHEN MAX(trim(CONFIRMED_DEL_DATE)) = '00000000' THEN CAST('19010101' AS date) ELSE CAST(MAX(trim(CONFIRMED_DEL_DATE)) AS date) END AS ConfirmedDelivDate
	,INVOICENUM AS SalesInvoiceNum
	,IIF(ORDERTYPE IN ('RE','G2'), -1*abs(orderqty),ORDERQTY) AS SalesOrderQty
	,DELIVQTY AS DelivQty
	,REMAININGQTY AS RemainingQty 
	--,NULL AS SalesInvoiceQty
	--,'' AS UoM
	,UNITPRICE AS UnitPrice
	,UNITCOST AS UnitCost
	,CURRENCY AS Currency
	,EXCHANGERATE AS ExchangeRate
	,SUMUNITPRICE AS SumUnitPrice
	,SUMUNITCOST AS SumUnitCost
	,CASE WHEN OPENRELEASE = '1' THEN '0' ELSE '1' END AS OpenRelease  --tested swapping the openrelease status /SM 2021-06-03
	,ABS(DISCOUNTAMOUNT) AS DiscountAmount

	,DISCOUNTPERCENT AS DiscountPercent
	,IIF(ISNUMERIC([PARTNUM]) = 1,CAST(CAST(trim([PARTNUM]) AS int)as nvarchar(50)),(trim([PARTNUM]))) AS PartNum
	--,'' AS PartType
	,PARTSTATUS AS PartStatus
	,SALESPERSON AS SalesPersonName
	,TRIM(WAREHOUSECODE) AS WarehouseCode
	--,'' AS SalesChannel
	,CASE WHEN ORDERTYPE = 'ZEDI' THEN 'EDI'
		ELSE 'Normal Order Handling' END AS AxInterSalesChannel
	,BUSINESSCHAIN AS Department
	,PROJECTNUM AS ProjectNum
	--,'' AS IndexKey
	--,'' AS Cancellation
	--,'' AS SORes1 
	,WBS_ELEMENT AS SORes2 -- 20210212
	--,'' AS SORes3
	,RETURNCOMMENT AS ReturnComment
	,SALESRETURNORDERNUM AS SalesReturnOrderNum
	,SALESRETURNINVOICENUM AS SalesReturnInvoiceNum
	--,NULL AS [TotalMiscChrg]
FROM stage.SKS_FI_OLine
WHERE [VKORG] NOT IN ('FI00','SE10')
GROUP BY
	PartitionKey, Company, CUSTNUM, ORDERNUM, ORDERLINE, ORDERSUBLINE, ORDERTYPE, ORDERRELNUM, trim([ORDERDATE]), trim([NEEDBYDATE]), trim([DELIVDATE]), INVOICENUM, ORDERQTY, DELIVQTY, REMAININGQTY, UNITPRICE, UNITCOST
	, SUMUNITPRICE, SUMUNITCOST, CURRENCY, EXCHANGERATE, OPENRELEASE, DISCOUNTAMOUNT, DISCOUNTPERCENT, PARTNUM, PARTSTATUS, SALESPERSON, RETURNCOMMENT, SALESRETURNORDERNUM, SALESRETURNINVOICENUM, TRIM(WAREHOUSECODE), SALESCHANNEL
	, BUSINESSCHAIN, VKORG, [ORDERDATE], PROJECTNUM, CONFIRMED_DEL_DATE, WBS_ELEMENT, ACTUALDELIVERYDATE
GO
