IF OBJECT_ID('[stage].[vSKS_FI_PurchaseLedger]') IS NOT NULL
	DROP VIEW [stage].[vSKS_FI_PurchaseLedger];

GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE VIEW [stage].[vSKS_FI_PurchaseLedger] AS 
--ADD UPPER() INTO SupplierID 23-01-24 VA
SELECT 
	CONVERT([binary](32), HASHBYTES('SHA2_256', CONCAT(CAST(IIF(TRIM(BUKRS) = 'FI20', 'SMKFI', (IIF(TRIM(BUKRS) in ('FI25', 'FI26'), 'SCOFI', IIF(TRIM(BUKRS) = 'SE10', 'SSWSE', TRIM(BUKRS))))) AS NVARCHAR(10)), '#', TRIM(SUPPLIERNUM), '#', TRIM(PURCHASEINVOICENUM),'#',TRIM(PURCHASEORDERNUM)))) AS PurchaseLedgerID
	,CONCAT(CAST(IIF(TRIM(BUKRS) = 'FI20', 'SMKFI', (IIF(TRIM(BUKRS) in ('FI25', 'FI26'), 'SCOFI', IIF(TRIM(BUKRS) = 'SE10', 'SSWSE', TRIM(BUKRS))))) AS NVARCHAR(10)), '#', TRIM(SUPPLIERNUM), '#', TRIM(PURCHASEINVOICENUM)) AS PurchaseLedgerCode
	,CONVERT([binary](32), HASHBYTES('SHA2_256', TRIM(CAST(IIF(TRIM(BUKRS) = 'FI20', 'SMKFI', (IIF(TRIM(BUKRS) in ('FI25', 'FI26'), 'SCOFI', IIF(TRIM(BUKRS) = 'SE10', 'SSWSE', TRIM(BUKRS))))) AS NVARCHAR(10))))) AS CompanyID
	,CONVERT([binary](32), HASHBYTES('SHA2_256', UPPER(CONCAT(CAST(IIF(TRIM(BUKRS) = 'FI20', 'SMKFI', (IIF(TRIM(BUKRS) in ('FI25', 'FI26'), 'SCOFI', IIF(TRIM(BUKRS) = 'SE10', 'SSWSE', TRIM(BUKRS))))) AS NVARCHAR(10)), '#', TRIM(SUPPLIERNUM))))) AS SupplierID
	--,CONVERT([binary](32), HASHBYTES('SHA2_256', CONCAT(CAST(IIF(TRIM(BUKRS) = 'FI20', 'SMKFI', (IIF(TRIM(BUKRS) in ('FI25', 'FI26'), 'SCOFI', IIF(TRIM(BUKRS) = 'SE10', 'SSWSE', TRIM(BUKRS))))) AS NVARCHAR(10)), '#', TRIM(SUPPLIERNUM)))) AS SupplierID
	,CONVERT([binary](32), HASHBYTES('SHA2_256', CONCAT(CAST(IIF(TRIM(BUKRS) = 'FI20', 'SMKFI', (IIF(TRIM(BUKRS) in ('FI25', 'FI26'), 'SCOFI', IIF(TRIM(BUKRS) = 'SE10', 'SSWSE', TRIM(BUKRS))))) AS NVARCHAR(10)), '#', TRIM(PURCHASEINVOICENUM)))) AS PurchaseInvoiceID
	,CONVERT([binary](32), HASHBYTES('SHA2_256', CONCAT(CAST(IIF(TRIM(BUKRS) = 'FI20', 'SMKFI', (IIF(TRIM(BUKRS) in ('FI25', 'FI26'), 'SCOFI', IIF(TRIM(BUKRS) = 'SE10', 'SSWSE', TRIM(BUKRS))))) AS NVARCHAR(10)), '#', PURCHASEORDERNUM))) AS PurchaseOrderNumID
	,CONVERT([binary](32), HASHBYTES('SHA2_256', TRIM(CURRENCY))) AS CurrencyID
	,CONVERT(int, replace(convert(date, INVOICEDATE), '-', '')) AS PurchaseInvoiceDateID
	,[PartitionKey]

	,CAST(IIF(TRIM(BUKRS) = 'FI20', 'SMKFI', (IIF(TRIM(BUKRS) in ('FI25', 'FI26'), 'SCOFI', IIF(TRIM(BUKRS) = 'SE10', 'SSWSE', TRIM(BUKRS))))) AS NVARCHAR(10)) AS [Company]
	,TRIM(SUPPLIERNUM) AS SupplierNum
	,TRIM(PURCHASEORDERNUM) AS [PurchaseOrderNum]
	,TRIM(PURCHASEINVOICENUM) AS [PurchaseInvoiceNum]
	,CONVERT(date, IIF(INVOICEDATE = '00000000', '1900-01-01', INVOICEDATE)) AS [PurchaseInvoiceDate]
	,CONVERT(date, IIF(DUEDATE = '00000000', '1900-01-01', DUEDATE)) AS PurchaseDueDate
	,IIF(LASTPAYMENTDATE = '00000000', '1900-01-01', CONVERT(date, LASTPAYMENTDATE)) AS PurchaseLastPaymentDate
	,INVOICELCYAMOUNT AS [InvoiceAmount]
	,EXCHANGERATE AS [ExchangeRate]
	,TRIM(CURRENCY) AS [Currency]
	,VATPAID AS [VATAmount]
	,VATCODE AS [VATcode]
	,PAYTONAME AS [PayToName]
	,PAYTOCITY AS [PayToCity]
	,PAYTOCONTACT AS PayToContact
	,PAYMENTTERMSCODE AS [PaymentTerms]
	,PREPAYMENTNUM AS [PrepaymentNum]
	,LASTPAYMENTNUM AS LastPaymentNum
	,INVOICECURRAMOUNT AS PLRES1
	,GJAHR AS PLRES2
	,MANDT AS PLRES3
	--,NULL AS PaidInvoiceAmount
	--,NULL AS RemainingInvoiceAmount
	--,NULL AS LinkToOriginalInvoice
	,'1900-01-01' AS AccountingDate
	--,NULL AS AgingPeriod
	--,NULL AS AgingSort
	--,NULL AS VATCodeDesc
FROM 
	[stage].[SKS_FI_PurchaseLedger]
	WHERE BUKRS NOT IN ('FI00','FI10','SE10', 'SKSSWE')
GO
