/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE USER [Joan_Ruiz] FOR LOGIN [Joan_Ruiz] WITH DEFAULT_SCHEMA=[ext]
GO
REVOKE CONNECT TO [Joan_Ruiz]
