/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE USER [JoelBjorck] FOR LOGIN [joelbjorck] WITH DEFAULT_SCHEMA=[ext]
GO
REVOKE CONNECT TO [JoelBjorck]
