/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE USER [joel_bjorck] FOR LOGIN [joel_bjorck] WITH DEFAULT_SCHEMA=[ext]
GO
REVOKE CONNECT TO [joel_bjorck]
