/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE USER [RebeckaNystrom] FOR LOGIN [RebeckaNystrom] WITH DEFAULT_SCHEMA=[ext]
GO
REVOKE CONNECT TO [RebeckaNystrom]
