/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE USER [sql-admin-TS] FOR LOGIN [sql-admin-TS] WITH DEFAULT_SCHEMA=[dm_TS]
GO
REVOKE CONNECT TO [sql-admin-TS]
