/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE USER [sql-admin-ALL] FOR LOGIN [sql-admin-ALL] WITH DEFAULT_SCHEMA=[dm_ALL]
GO
REVOKE CONNECT TO [sql-admin-ALL]
