/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [ext].[CoC_DUNS_sign]
(
[DUNS] [int] NOT NULL,
[last_modified_date] [date] NULL
)
GO
ALTER TABLE [ext].[CoC_DUNS_sign] ADD CONSTRAINT [PK__CoC_DUNS__2A5E8099DCBA8E67] PRIMARY KEY CLUSTERED ([DUNS])
GO
