/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [ext].[CoC_Local_sign]
(
[dw_id] [bigint] NOT NULL,
[is_customer] [bit] NOT NULL,
[last_modified_date] [date] NULL
)
GO
