/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [ext].[CoC_Inherited_sign]
(
[DUNS] [int] NOT NULL,
[DUNS_Inherited] [int] NOT NULL,
[last_modified_date] [date] NOT NULL
)
GO
