/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [ext].[ManualMatchLog]
(
[dw_id] [bigint] NOT NULL,
[is_customer] [bit] NOT NULL,
[duns] [int] NOT NULL,
[modified_date] [datetime] NOT NULL,
[user_name] [nvarchar] (100) NULL,
[Company] [nvarchar] (12) NOT NULL,
[previous_duns] [int] NULL
)
GO
SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO

CREATE TRIGGER [ext].[Trigger_ManualMatchLog]
    ON [ext].[ManualMatchLog]
    AFTER INSERT
    AS
    BEGIN
        UPDATE dnb
		SET 
			 dnb.DUNS = (SELECT duns FROM inserted)
			,dnb.is_monitored = null
			,dnb.manual_date = GETDATE()
		FROM dnb.DnBCustomerAndSupplier dnb
		WHERE cast(dnb.dw_id as bigint) = (SELECT dw_id FROM inserted) 
		and dnb.is_customer = (SELECT is_customer FROM inserted)
		and dnb.Company = (SELECT Company FROM inserted);
    END
GO
