/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [axbus].[IOW_PL_OLine]
(
[PartitionKey] [nvarchar] (50) NULL,
[Company] [nvarchar] (50) NOT NULL,
[CustomerNum] [nvarchar] (100) NULL,
[SalesOrderNum] [nvarchar] (100) NULL,
[SalesOrderLine] [nvarchar] (100) NULL,
[SalesOrderSubLine] [nvarchar] (100) NULL,
[SalesOrderType] [nvarchar] (max) NULL,
[SalesOrderCategory] [nvarchar] (max) NULL,
[SalesOrderStatus] [nvarchar] (max) NULL,
[SalesOrderDate] [nvarchar] (max) NULL,
[NeedbyDate] [nvarchar] (max) NULL,
[ExpDelivDate] [nvarchar] (max) NULL,
[ActualDelivDate] [nvarchar] (max) NULL,
[SalesInvoiceNum] [nvarchar] (max) NULL,
[SalesOrderQty] [nvarchar] (max) NULL,
[DelivQty] [nvarchar] (max) NULL,
[RemainingQty] [nvarchar] (max) NULL,
[InvoiceQty] [nvarchar] (max) NULL,
[UoM] [nvarchar] (max) NULL,
[UnitPrice] [nvarchar] (max) NULL,
[UnitCost] [nvarchar] (max) NULL,
[Currency] [nvarchar] (max) NULL,
[ExchangeRate] [nvarchar] (max) NULL,
[DiscountPercent] [nvarchar] (max) NULL,
[DiscountAmount] [nvarchar] (max) NULL,
[PartNum] [nvarchar] (max) NULL,
[PartType] [nvarchar] (max) NULL,
[PartStatus] [nvarchar] (max) NULL,
[OrderHandler] [nvarchar] (max) NULL,
[WarehouseCode] [nvarchar] (max) NULL,
[SalesChannel] [nvarchar] (max) NULL,
[Department] [nvarchar] (max) NULL,
[ProjectNum] [nvarchar] (max) NULL,
[Cancellation] [nvarchar] (max) NULL,
[IndexKey] [nvarchar] (max) NULL,
[SORes1] [nvarchar] (max) NULL,
[SORes2] [nvarchar] (max) NULL,
[SORes3] [nvarchar] (max) NULL,
[UnitCost2] [nvarchar] (max) NULL,
[UnitCost2Curr] [nvarchar] (max) NULL,
[ExchangeRate2] [nvarchar] (max) NULL,
[sysCurrency] [nvarchar] (max) NULL,
[CreatedTimeStamp] [nvarchar] (max) NULL,
[ModifiedTimeStamp] [nvarchar] (max) NULL
)
GO
