/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [axbus].[IOW_PL_SalesLedger]
(
[PartitionKey] [nvarchar] (50) NULL,
[Company] [nvarchar] (50) NOT NULL,
[CustomerNum] [nvarchar] (max) NULL,
[SalesInvoiceNum] [nvarchar] (max) NULL,
[SalesInvoiceDate] [nvarchar] (max) NULL,
[SalesDueDate] [nvarchar] (max) NULL,
[SalesLastPaymentDate] [nvarchar] (max) NULL,
[InvoiceAmount] [nvarchar] (max) NULL,
[PaidInvoiceAmount] [nvarchar] (max) NULL,
[RemainingInvoiceAmount] [nvarchar] (max) NULL,
[AccountingDate] [nvarchar] (max) NULL,
[Currency] [nvarchar] (max) NULL,
[VATAmount] [nvarchar] (max) NULL,
[VATCode] [nvarchar] (max) NULL,
[PayToName] [nvarchar] (max) NULL,
[PayToCity] [nvarchar] (max) NULL,
[PayToContact] [nvarchar] (max) NULL,
[ExchangeRate] [nvarchar] (max) NULL,
[AgingPeriod] [nvarchar] (max) NULL,
[AgingSort] [nvarchar] (max) NULL,
[VATCodeDesc] [nvarchar] (max) NULL,
[PaymentTerms] [nvarchar] (max) NULL,
[SLRes1] [nvarchar] (max) NULL,
[SLRes2] [nvarchar] (max) NULL,
[SLRes3] [nvarchar] (max) NULL,
[sysCurrency] [nvarchar] (max) NULL,
[CreatedTimeStamp] [nvarchar] (max) NULL,
[ModifiedTimeStamp] [nvarchar] (max) NULL
)
GO
