/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [axbus].[IOW_PL_SalesPerson]
(
[Company] [nvarchar] (50) NULL,
[SalesPersonCode] [nvarchar] (50) NULL,
[SalesPersonName] [nvarchar] (50) NULL,
[RoleType] [nvarchar] (50) NULL,
[SalesDistrict] [nvarchar] (50) NULL,
[SalesPersonResponsibleCode] [nvarchar] (50) NULL,
[SalesPersonResponsibleName] [nvarchar] (50) NULL,
[CreatedTimeStamp] [nvarchar] (50) NULL,
[ModifiedTimeStamp] [nvarchar] (50) NULL,
[IsActiveRecord] [bit] NULL,
[STRes1] [nvarchar] (50) NULL,
[STRes2] [nvarchar] (50) NULL,
[STRes3] [nvarchar] (50) NULL
)
GO
