/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [axbus].[IOW_PL_Suppliers]
(
[Company] [nvarchar] (50) NULL,
[SupplierNum] [nvarchar] (50) NULL,
[SupplierName] [nvarchar] (max) NULL,
[AddressLine1] [nvarchar] (max) NULL,
[AddressLine2] [nvarchar] (max) NULL,
[AddressLine3] [nvarchar] (50) NULL,
[TelephoneNumber1] [nvarchar] (50) NULL,
[TelephoneNumber2] [nvarchar] (50) NULL,
[Email] [nvarchar] (max) NULL,
[ZipCode] [nvarchar] (50) NULL,
[City] [nvarchar] (max) NULL,
[State] [nvarchar] (50) NULL,
[CountryCode] [nvarchar] (50) NULL,
[CountryName] [nvarchar] (50) NULL,
[SupplierGroup] [nvarchar] (100) NULL,
[SupplierIndustry] [nvarchar] (100) NULL,
[PrimaryPurchaser] [nvarchar] (100) NULL,
[SupplierResponsible] [nvarchar] (100) NULL,
[VATNum] [nvarchar] (50) NULL,
[OrgNum] [nvarchar] (50) NULL,
[AccountNum] [nvarchar] (50) NULL,
[IsAxInterInternal] [tinyint] NULL,
[CodeOfConduct] [bit] NULL,
[SupplierScore] [nvarchar] (50) NULL,
[IsMaterialSupplier] [bit] NULL,
[CreatedTimeStamp] [nvarchar] (50) NULL,
[ModifiedTimeStamp] [datetime2] NULL,
[RecordIsActive] [nvarchar] (50) NULL,
[Website] [nvarchar] (max) NULL,
[Comments] [nvarchar] (max) NULL,
[SRes1] [nvarchar] (50) NULL,
[SRes2] [nvarchar] (50) NULL,
[SRes3] [nvarchar] (50) NULL,
[SRes4] [tinyint] NULL,
[SRes5] [tinyint] NULL
)
GO
