/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [audit].[IndexMaintenance]
(
[Date] [date] NOT NULL,
[TableSchema] [varchar] (15) NOT NULL,
[TableName] [varchar] (80) NOT NULL,
[IndexName] [varchar] (100) NOT NULL,
[SecDuration] [int] NOT NULL,
[Succeeded] [bit] NOT NULL
)
GO
