/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [audit].[PipelinesActivitiesLog]
(
[PipelineRunID] [varchar] (100) NULL,
[PipelineTriggerRunID] [varchar] (100) NULL,
[Company] [varchar] (25) NULL,
[TableName] [nvarchar] (60) NULL,
[Stage] [varchar] (25) NULL,
[StartTime] [datetime] NULL,
[EndTime] [datetime] NULL,
[Status] [varchar] (25) NULL,
[ErrorMessage] [varchar] (max) NULL,
[rowsCopied] [varchar] (25) NULL,
[Date] [date] NULL,
[Period] [nvarchar] (40) NULL,
[Triggered] [bit] NULL,
[PartitionKey] [varchar] (50) NULL
)
GO
