/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [audit].[RunLog]
(
[RunLogId] [uniqueidentifier] NOT NULL CONSTRAINT [DF_RunLog_RunLogId] DEFAULT (newid()),
[PartitionKey] [varchar] (50) NULL,
[ProcName] [varchar] (100) NOT NULL,
[FromTable] [varchar] (100) NULL,
[ToTable] [varchar] (100) NULL,
[StartTime] [datetime] NOT NULL CONSTRAINT [DF_RunLog_StartTime] DEFAULT (getdate()),
[EndTime] [datetime] NOT NULL,
[DurationSeconds] AS (datediff(second,[StartTime],[EndTime])),
[RowsAffected] [int] NULL,
[StatusName] [varchar] (10) NOT NULL,
[ErrorMessage] [varchar] (max) NULL,
[MergeExecuted] [varchar] (50) NULL,
[Date] [date] NULL
)
GO
