/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [prestage].[CYE_ES_POLine]
(
[Company] [nvarchar] (8) NOT NULL,
[SupplierNum] [nvarchar] (50) NULL,
[OrderDate] [date] NULL,
[InvoiceNum] [nvarchar] (50) NULL,
[InvoiceLine] [nvarchar] (50) NULL,
[PONum] [nvarchar] (50) NULL,
[POLine] [nvarchar] (50) NULL,
[PORelNum] [nvarchar] (50) NULL,
[PartNum] [nvarchar] (50) NULL,
[Qty] [nvarchar] (50) NULL,
[UnitPrice] [nvarchar] (50) NULL,
[Indexkey] [nvarchar] (50) NULL
)
GO
