/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [prestage].[CYE_ES_OLine]
(
[Company] [nvarchar] (8) NOT NULL,
[CustNum] [nvarchar] (50) NULL,
[OrderNum] [nvarchar] (50) NULL,
[OrderLine] [nvarchar] (50) NULL,
[OrderRelNum] [nvarchar] (200) NULL,
[OrderType] [nvarchar] (50) NULL,
[OrderDate] [date] NULL,
[DelivDate] [date] NULL,
[OrderQty] [nvarchar] (50) NULL,
[DelivQty] [nvarchar] (50) NULL,
[RemainingQty] [nvarchar] (50) NULL,
[InvoiceQty] [nvarchar] (50) NULL,
[UnitPrice] [nvarchar] (50) NULL,
[UnitCost] [nvarchar] (50) NULL,
[OpenRelease] [nvarchar] (50) NULL,
[DiscountPercent] [nvarchar] (50) NULL,
[DiscountAmount] [nvarchar] (50) NULL,
[PartNum] [nvarchar] (50) NULL,
[NeedbyDate] [date] NULL,
[SalesPerson] [nvarchar] (50) NULL,
[SalesOfficeDescrip] [nvarchar] (50) NULL,
[SalesGroupCode] [nvarchar] (50) NULL,
[SalesGroupDescrip] [nvarchar] (50) NULL,
[WarehouseCode] [nvarchar] (50) NULL,
[InvoiceNum] [nvarchar] (50) NULL,
[UnitCostEK02] [nvarchar] (50) NULL
)
GO
