/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [prestage].[CYE_ES_SalesOffice]
(
[SalesOfficeCode] [nvarchar] (50) NULL,
[SalesOfficeDescrip] [nvarchar] (50) NULL
)
GO
