/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [prestage].[PIM_ALL_Product]
(
[Prop_0] [varchar] (50) NULL,
[Prop_1] [varchar] (50) NULL,
[Prop_2] [varchar] (max) NULL,
[Prop_3] [varchar] (max) NULL,
[Prop_4] [varchar] (max) NULL,
[Prop_5] [varchar] (max) NULL,
[Prop_6] [varchar] (max) NULL,
[Prop_7] [varchar] (max) NULL,
[Prop_8] [varchar] (max) NULL,
[Prop_9] [varchar] (max) NULL,
[Prop_10] [varchar] (max) NULL,
[Prop_11] [varchar] (max) NULL,
[Prop_12] [varchar] (max) NULL,
[Prop_13] [varchar] (max) NULL,
[Prop_14] [varchar] (max) NULL,
[Prop_15] [varchar] (max) NULL,
[Prop_16] [varchar] (max) NULL,
[Prop_17] [varchar] (max) NULL,
[Prop_18] [varchar] (max) NULL,
[Prop_19] [varchar] (max) NULL,
[Prop_20] [varchar] (max) NULL,
[Prop_21] [varchar] (max) NULL,
[Prop_22] [varchar] (max) NULL,
[Prop_23] [varchar] (max) NULL,
[Prop_24] [varchar] (max) NULL,
[Prop_25] [varchar] (max) NULL,
[Prop_26] [varchar] (max) NULL,
[Prop_27] [varchar] (max) NULL,
[Prop_28] [varchar] (max) NULL,
[Prop_29] [varchar] (max) NULL,
[Prop_30] [varchar] (max) NULL,
[Prop_31] [varchar] (max) NULL,
[Prop_32] [varchar] (max) NULL
)
GO
