/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [prestage].[TRA_FR_Warehouse]
(
[Prop_0] [nvarchar] (8) NOT NULL,
[Prop_1] [nvarchar] (50) NOT NULL,
[Prop_2] [nvarchar] (100) NULL,
[Prop_3] [nchar] (10) NULL,
[Prop_4] [nchar] (10) NULL,
[Prop_5] [nchar] (10) NULL,
[Prop_6] [nchar] (10) NULL,
[Prop_7] [nchar] (10) NULL,
[Prop_8] [nchar] (10) NULL,
[Prop_9] [nchar] (10) NULL
)
GO
