/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [prestage].[TRA_FR_Customer]
(
[Prop_0] [nvarchar] (8) NULL,
[Prop_1] [nvarchar] (50) NULL,
[Prop_2] [nvarchar] (max) NULL,
[Prop_3] [nvarchar] (max) NULL,
[Prop_4] [nvarchar] (max) NULL,
[Prop_5] [nvarchar] (max) NULL,
[Prop_6] [nvarchar] (max) NULL,
[Prop_7] [nvarchar] (max) NULL,
[Prop_8] [nvarchar] (max) NULL,
[Prop_9] [nvarchar] (max) NULL,
[Prop_10] [nvarchar] (max) NULL,
[Prop_11] [nvarchar] (max) NULL,
[Prop_12] [nvarchar] (max) NULL,
[Prop_13] [nvarchar] (max) NULL,
[Prop_14] [nvarchar] (max) NULL,
[Prop_15] [nvarchar] (max) NULL,
[Prop_16] [nvarchar] (max) NULL,
[Prop_17] [nvarchar] (max) NULL,
[Prop_18] [nvarchar] (max) NULL,
[Prop_19] [nvarchar] (max) NULL,
[Prop_20] [nvarchar] (max) NULL,
[Prop_21] [nvarchar] (max) NULL,
[Prop_22] [nvarchar] (max) NULL,
[Prop_23] [nvarchar] (max) NULL,
[Prop_24] [nvarchar] (max) NULL,
[Prop_25] [nvarchar] (max) NULL,
[Prop_26] [nvarchar] (max) NULL,
[Prop_27] [nvarchar] (max) NULL,
[Prop_28] [nvarchar] (max) NULL,
[Prop_29] [nvarchar] (max) NULL,
[Prop_30] [nvarchar] (max) NULL,
[Prop_31] [nvarchar] (max) NULL,
[Prop_32] [nvarchar] (max) NULL
)
GO
