/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [prestage].[TRA_FR_SOLine]
(
[Prop_0] [nvarchar] (8) NOT NULL,
[Prop_1] [nvarchar] (100) NULL,
[Prop_2] [nvarchar] (50) NULL,
[Prop_3] [nvarchar] (50) NULL,
[Prop_4] [nvarchar] (50) NULL,
[Prop_5] [nvarchar] (50) NULL,
[Prop_6] [nvarchar] (50) NULL,
[Prop_7] [nvarchar] (50) NULL,
[Prop_8] [nvarchar] (50) NULL,
[Prop_9] [nvarchar] (50) NULL,
[Prop_10] [nvarchar] (50) NULL,
[Prop_11] [nvarchar] (50) NULL,
[Prop_12] [nvarchar] (50) NULL,
[Prop_13] [nvarchar] (50) NULL,
[Prop_14] [decimal] (18, 4) NULL,
[Prop_15] [nvarchar] (50) NULL,
[Prop_16] [decimal] (18, 4) NULL,
[Prop_17] [decimal] (18, 4) NULL,
[Prop_18] [decimal] (18, 4) NULL,
[Prop_19] [decimal] (18, 4) NULL,
[Prop_20] [decimal] (18, 4) NULL,
[Prop_21] [decimal] (18, 4) NULL,
[Prop_22] [decimal] (18, 4) NULL,
[Prop_23] [decimal] (18, 4) NULL,
[Prop_24] [nvarchar] (50) NULL,
[Prop_25] [decimal] (18, 4) NULL,
[Prop_26] [nvarchar] (50) NULL,
[Prop_27] [nvarchar] (50) NULL,
[Prop_28] [nvarchar] (50) NULL,
[Prop_29] [nvarchar] (50) NULL,
[Prop_30] [nvarchar] (50) NULL,
[Prop_31] [nvarchar] (50) NULL,
[Prop_32] [nvarchar] (max) NULL,
[Prop_33] [nvarchar] (50) NULL,
[Prop_34] [nvarchar] (50) NULL,
[Prop_35] [nvarchar] (50) NULL,
[Prop_36] [nvarchar] (100) NULL,
[Prop_37] [nvarchar] (100) NULL,
[Prop_38] [nvarchar] (100) NULL,
[Prop_39] [nchar] (10) NULL
)
GO
