/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [prestage].[TRA_FR_SalesLedger]
(
[Prop_0] [nvarchar] (8) NOT NULL,
[Prop_1] [nvarchar] (100) NULL,
[Prop_2] [nvarchar] (50) NULL,
[Prop_3] [nvarchar] (50) NULL,
[Prop_4] [nvarchar] (50) NULL,
[Prop_5] [nvarchar] (50) NULL,
[Prop_6] [nvarchar] (50) NULL,
[Prop_7] [nvarchar] (50) NULL,
[Prop_8] [nvarchar] (50) NULL,
[Prop_9] [nvarchar] (50) NULL,
[Prop_10] [nvarchar] (50) NULL,
[Prop_11] [nvarchar] (50) NULL,
[Prop_12] [nvarchar] (50) NULL,
[Prop_13] [nvarchar] (50) NULL,
[Prop_14] [nvarchar] (50) NULL,
[Prop_15] [nvarchar] (50) NULL,
[Prop_16] [nvarchar] (50) NULL,
[Prop_17] [nvarchar] (50) NULL,
[Prop_18] [nvarchar] (50) NULL
)
GO
