/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dnb].[dimDUNSHierarchy]
(
[duns] [int] NOT NULL,
[L1] [int] NULL,
[L2] [int] NULL,
[L3] [int] NULL,
[L4] [int] NULL,
[L5] [int] NULL,
[L6] [int] NULL,
[L7] [int] NULL,
[L8] [int] NULL,
[L9] [int] NULL,
[L10] [int] NULL,
[L11] [int] NULL,
[L12] [int] NULL,
[L13] [int] NULL,
[L14] [int] NULL,
[L15] [int] NULL,
[L16] [int] NULL,
[L17] [int] NULL,
[L18] [int] NULL,
[L19] [int] NULL,
[L20] [int] NULL,
[L21] [int] NULL,
[L22] [int] NULL,
[L23] [int] NULL,
[L24] [int] NULL,
[last_modified_date] [date] NULL
)
GO
ALTER TABLE [dnb].[dimDUNSHierarchy] ADD CONSTRAINT [PK_duns] PRIMARY KEY CLUSTERED ([duns])
GO
