/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dnb].[dimError]
(
[errorCode] [nvarchar] (10) NOT NULL,
[errorDescription] [nvarchar] (200) NOT NULL,
[stage] [nvarchar] (15) NULL
)
GO
