/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dnb].[dimIndustryCode_3599_Hierarchy]
(
[Level_1_Code] [nvarchar] (100) NULL,
[Level_1_Description] [nvarchar] (4000) NULL,
[Level_2_Code] [nvarchar] (100) NULL,
[Level_2_Description] [nvarchar] (4000) NULL,
[Level_3_Code] [nvarchar] (100) NULL,
[Level_3_Description] [nvarchar] (4000) NULL,
[Level_4_Code] [nvarchar] (100) NULL,
[Level_4_Description] [nvarchar] (4000) NULL,
[Level_5_Code] [nvarchar] (100) NULL,
[Level_5_Description] [nvarchar] (4000) NULL
)
GO
