/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dnb].[dimMatchGradeString]
(
[Grade] [char] (1) NULL,
[Definition] [nvarchar] (80) NULL,
[Example] [nvarchar] (80) NULL,
[GradeScore] [int] NULL
)
GO
