/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dnb].[dimUnspsc]
(
[code_2] [nvarchar] (2) NOT NULL,
[code_4] [nvarchar] (4) NOT NULL,
[code_6] [nvarchar] (6) NOT NULL,
[code_8] [nvarchar] (8) NOT NULL,
[description] [nvarchar] (1000) NOT NULL
)
GO
