/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dnb].[dimUnspscHierarchy]
(
[Level_1_Code] [nvarchar] (2) NOT NULL,
[Level_1_Description] [nvarchar] (1000) NOT NULL,
[Level_2_Code] [nvarchar] (4) NULL,
[Level_2_Description] [nvarchar] (1000) NULL,
[Level_3_Code] [nvarchar] (6) NULL,
[Level_3_Description] [nvarchar] (1000) NULL,
[Level_4_Code] [nvarchar] (8) NULL,
[Level_4_Description] [nvarchar] (1000) NULL
)
GO
