/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dnb].[DnBCustomerAndSupplier]
(
[PartitionKey] [varchar] (50) NULL,
[dw_id] [binary] (32) NULL,
[is_customer] [bit] NULL,
[DUNS] [int] NULL,
[BusinessName1] [varchar] (100) NULL,
[BusinessName2] [varchar] (100) NULL,
[VisitStreetAddress] [varchar] (200) NULL,
[MailStreetAddress] [varchar] (100) NULL,
[VisitPostalCode] [varchar] (100) NULL,
[ProvinceName] [varchar] (100) NULL,
[CountryCode] [varchar] (100) NULL,
[TelephoneNumber] [varchar] (100) NULL,
[LocalRegistrationNumber] [varchar] (100) NULL,
[Email] [varchar] (100) NULL,
[lastDateDetected] [date] NULL,
[sent_date] [datetime] NULL,
[match_date] [datetime] NULL,
[enrich_date] [datetime] NULL,
[last_modified_date] [datetime] NULL,
[confidence_code] [int] NULL,
[is_monitored] [bit] NULL,
[monitor_date] [datetime] NULL,
[Company] [nvarchar] (15) NULL,
[match_status] [nvarchar] (12) NULL,
[enrich_status] [nvarchar] (12) NULL,
[error_detail] [nvarchar] (2000) NULL,
[manual_date] [datetime] NULL,
[monitor_status] [nvarchar] (12) NULL
)
GO
CREATE NONCLUSTERED INDEX [IX_DnBCustomerAndSupplier_duns] ON [dnb].[DnBCustomerAndSupplier] ([DUNS])
GO
CREATE NONCLUSTERED INDEX [IX_DnBCustomerAndSupplier_dwId-isCustomer] ON [dnb].[DnBCustomerAndSupplier] ([dw_id], [is_customer])
GO
