/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dnb].[FamilyTree]
(
[duns] [int] NULL,
[organization.corporateLinkage.familytreeRolesPlayed.description] [nvarchar] (25) NULL,
[organization.corporateLinkage.familytreeRolesPlayed.dnbCode] [int] NULL
)
GO
