/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dnb].[FilesReferenceLog]
(
[date_ref] [date] NULL,
[process] [nvarchar] (60) NULL,
[partitionKey] [bigint] NULL,
[info_in_dw] [bit] NULL
)
GO
