/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dnb].[hierarchy_test]
(
[Column1] [nvarchar] (100) NULL,
[Hierarchy_Name] [nvarchar] (100) NULL,
[Column2] [nvarchar] (100) NULL,
[Column3] [nvarchar] (100) NULL,
[Column4] [nvarchar] (100) NULL,
[Column5] [nvarchar] (100) NULL,
[Column6] [nvarchar] (100) NULL,
[Column7] [nvarchar] (100) NULL,
[Column8] [nvarchar] (100) NULL,
[Column9] [nvarchar] (100) NULL,
[Column10] [nvarchar] (100) NULL,
[Hierarchy_Level] [nvarchar] (100) NULL,
[Hierarchy_Node_desc] [nvarchar] (100) NULL
)
GO
