/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dnb].[InternalExcelCompanies]
(
[customerReference] [int] NULL,
[subsidiariesName] [nvarchar] (100) NULL,
[city] [nvarchar] (100) NULL,
[organizationNum] [nvarchar] (100) NULL,
[countryCode] [nvarchar] (100) NULL,
[DUNS] [int] NULL,
[confidenceCode] [int] NULL
)
GO
