/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dnb].[numberOfEmployees]
(
[duns] [int] NOT NULL,
[organization.numberOfEmployees.informationScopeDescription] [nvarchar] (40) NULL,
[organization.numberOfEmployees.value] [int] NULL
)
GO
