/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dnb].[TradeStyleNames]
(
[duns] [int] NULL,
[organization.tradeStyleNames.name] [nvarchar] (100) NULL,
[organization.tradeStyleNames.priority] [nvarchar] (100) NULL
)
GO
