/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[ABK_SE_Part]
(
[PartitionKey] [varchar] (50) NOT NULL,
[Company] [nvarchar] (8) NULL,
[PartNum] [nvarchar] (50) NULL,
[PartDescription] [nvarchar] (500) NULL,
[PartDescription2] [nvarchar] (100) NULL,
[PartDescription3] [nvarchar] (100) NULL,
[ProductGroup] [nvarchar] (50) NULL,
[ProductGroup2] [nvarchar] (50) NULL,
[ProductStatus] [nvarchar] (50) NULL,
[Brand] [nvarchar] (50) NULL,
[CommodityCode] [nvarchar] (14) NULL,
[PartNumReplacement] [nvarchar] (50) NULL,
[CountryOfOrigin] [nvarchar] (50) NULL,
[NetWeight] [decimal] (18, 8) NULL,
[Volume] [decimal] (18, 8) NULL,
[Material] [nvarchar] (50) NULL,
[Barcode] [nvarchar] (50) NULL,
[ReorderLevel] [decimal] (18, 8) NULL,
[PrimarySupplier] [nvarchar] (500) NULL,
[StartDate] [date] NULL,
[EndDate] [date] NULL,
[Res1_ProdCatNo] [nvarchar] (50) NULL
)
GO
