/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[ABK_SE_PurchaseLedger]
(
[PartitionKey] [nvarchar] (50) NOT NULL,
[Company] [nvarchar] (8) NOT NULL,
[SupplierNum] [nvarchar] (50) NOT NULL,
[PurchaseInvoiceNum] [nvarchar] (50) NOT NULL,
[PurchaseOrderNum] [nvarchar] (50) NULL,
[PurchaseInvoiceDate] [date] NULL,
[PurchaseDueDate] [date] NULL,
[PurchaseLastPaymentDate] [date] NULL,
[InvoiceAmount] [decimal] (18, 4) NOT NULL,
[PaidInvoiceAmount] [decimal] (18, 4) NULL,
[RemainingInvoiceAmount] [decimal] (18, 4) NULL,
[AccountingDate] [date] NULL,
[ExchangeRate] [decimal] (18, 4) NULL,
[Currency] [nvarchar] (10) NULL,
[VATAmount] [decimal] (18, 4) NULL,
[PayToName] [nvarchar] (50) NULL,
[PaymentTerms] [nvarchar] (50) NULL,
[ModifiedTimeStamp] [nvarchar] (50) NULL,
[CreatedTimeStamp] [nvarchar] (50) NULL,
[IndexKey] [nvarchar] (50) NULL
)
GO
