/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[ABK_SE_RLS]
(
[Name] [nvarchar] (200) NULL,
[Email] [nvarchar] (200) NOT NULL,
[All] [smallint] NULL,
[SalesPersonName] [nvarchar] (200) NULL
)
GO
