/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[ABK_SE_SOLine]
(
[PartitionKey] [varchar] (50) NOT NULL,
[Company] [nvarchar] (8) NOT NULL,
[SalesPerson] [nvarchar] (100) NULL,
[CustNum] [nvarchar] (50) NULL,
[ProdNo] [nvarchar] (50) NULL,
[OrderNum] [nvarchar] (50) NULL,
[OrderLine] [nvarchar] (50) NULL,
[InvoiceNum] [nvarchar] (50) NULL,
[InvoiceDate] [nvarchar] (50) NULL,
[DeliveryDate] [nvarchar] (50) NULL,
[Qty] [decimal] (18, 8) NULL,
[Unit] [nvarchar] (50) NULL,
[UnitPrice] [decimal] (18, 4) NULL,
[UnitPriceSEK] [decimal] (18, 4) NULL,
[UnitCost] [decimal] (18, 4) NULL,
[UnitCostSEK] [decimal] (18, 4) NULL,
[Descr] [nvarchar] (500) NULL,
[DiscountPercent] [decimal] (18, 4) NULL,
[DiscountPercent2] [decimal] (18, 4) NULL,
[DiscountPercent3] [decimal] (18, 4) NULL,
[Amount] [decimal] (18, 4) NULL,
[AmountSEK] [decimal] (18, 4) NULL,
[Currency] [nvarchar] (50) NULL,
[ISOCode] [nvarchar] (50) NULL,
[ExchangeRate] [nvarchar] (50) NULL,
[WarehouseCode] [nvarchar] (50) NULL,
[JNo] [nvarchar] (50) NULL,
[TrNo] [nvarchar] (50) NULL
)
GO
