/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[ABK_SE_SalesLedger]
(
[PartitionKey] [varchar] (50) NOT NULL,
[Company] [nvarchar] (8) NULL,
[CustomerID] [nvarchar] (50) NULL,
[InvoiceID] [nvarchar] (50) NULL,
[InvoDate] [date] NULL,
[DueDate] [date] NULL,
[LastPayment] [date] NULL,
[AmountSEK] [decimal] (18, 8) NULL,
[OutstandingAmountSEK] [decimal] (18, 8) NULL,
[Currency] [nvarchar] (50) NULL,
[ISOCode] [nvarchar] (50) NULL,
[ExchangeRate] [decimal] (18, 8) NULL,
[AmountCur] [decimal] (18, 8) NULL,
[OutstandingAmountCur] [decimal] (18, 8) NULL,
[VatAmSEK] [decimal] (18, 8) NULL,
[VatAmCur] [decimal] (18, 8) NULL
)
GO
