/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[ACO_UK_SOLine_Manual_Adjustment_Remove]
(
[SOPNUMBE] [nvarchar] (50) NULL,
[SOPTYPE] [nvarchar] (50) NULL,
[GLPostingdate] [nvarchar] (50) NULL,
[ItemNumber] [nvarchar] (50) NULL,
[ExtendedPrice] [nvarchar] (50) NULL,
[ExtendedCost] [nvarchar] (50) NULL,
[QUANTITY] [nvarchar] (50) NULL,
[CUSTNMBR] [nvarchar] (50) NULL
)
GO
