/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[ACO_UK_SOLine_Manual_Adjustment]
(
[PartitionKey] [varchar] (50) NULL,
[SopNumber] [nvarchar] (50) NULL,
[SOPTYPE] [nvarchar] (50) NULL,
[GLPostingDate] [nvarchar] (50) NULL,
[ItemNumber] [nvarchar] (200) NULL,
[Brand] [nvarchar] (100) NULL,
[ExtendedPrice] [nvarchar] (50) NULL,
[ExtendedCost] [nvarchar] (50) NULL,
[QUANTITY] [nvarchar] (50) NULL,
[CUSTNMBR] [nvarchar] (50) NULL,
[Item_Class] [nvarchar] (50) NULL,
[UserToEnter] [nvarchar] (50) NULL,
[Discount] [nvarchar] (50) NULL
)
GO
