/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[ARK_CZ_Part]
(
[PartitionKey] [varchar] (50) NULL,
[Company] [nvarchar] (9) NULL,
[PartNum] [nvarchar] (max) NULL,
[PartName] [nvarchar] (max) NULL,
[PartDescription] [nvarchar] (max) NULL,
[PartDescription2] [nvarchar] (max) NULL,
[ProductGroup] [nvarchar] (200) NULL,
[ProductGroup2] [nvarchar] (200) NULL,
[ProductGroup3] [nvarchar] (200) NULL,
[ProductGroup4] [nvarchar] (200) NULL,
[Brand] [nvarchar] (50) NULL,
[Model] [nvarchar] (50) NULL,
[CommodityCode] [nvarchar] (50) NULL,
[CountryOfOrigin] [nvarchar] (50) NULL,
[NetWeight] [decimal] (18, 4) NULL,
[Volume] [decimal] (18, 4) NULL,
[Material] [nvarchar] (50) NULL,
[ReorderLevel] [decimal] (18, 4) NULL,
[PartStatus] [nvarchar] (50) NULL,
[StartDate] [date] NULL,
[EndDate] [date] NULL,
[Res1] [nvarchar] (50) NULL,
[Res2] [nvarchar] (50) NULL,
[Res3] [nvarchar] (50) NULL
)
GO
