/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[ARK_CZ_RLS]
(
[PartitionKey] [varchar] (50) NOT NULL,
[email] [nvarchar] (100) NULL,
[Branch] [nvarchar] (200) NULL,
[Account] [nvarchar] (50) NULL,
[Manager] [nvarchar] (100) NULL
)
GO
