/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[ARK_PI_ProductionOrder]
(
[PartitionKey] [nvarchar] (50) NOT NULL,
[Company] [nvarchar] (50) NOT NULL,
[ProductionOrderNum] [nvarchar] (50) NOT NULL,
[ProductionOrderLineNum] [nvarchar] (50) NULL,
[ProductionOrderSubLineNum] [nvarchar] (50) NULL,
[PartNum] [nvarchar] (50) NULL,
[Version] [nvarchar] (50) NULL,
[UoM] [nvarchar] (50) NULL,
[PartType] [nvarchar] (50) NULL,
[OrderQuantity] [nvarchar] (50) NULL,
[ScrappedQty] [nvarchar] (50) NULL,
[CompletedQuantity] [nvarchar] (50) NULL,
[RemainingQty] [nvarchar] (50) NULL,
[Status] [nvarchar] (50) NULL,
[CurrentOperationStage] [nvarchar] (50) NULL,
[CurrentResourceGroup] [nvarchar] (50) NULL,
[OrderCreateDate] [nvarchar] (50) NULL,
[RequestedEndDate] [nvarchar] (50) NULL,
[PlannedStartDate] [nvarchar] (50) NULL,
[PlannedEndDate] [nvarchar] (50) NULL,
[StartDate] [nvarchar] (50) NULL,
[EndDate] [nvarchar] (50) NULL,
[OrderType] [nvarchar] (50) NULL,
[TotalHoursPlanned] [nvarchar] (50) NULL,
[TotalHoursSpent] [nvarchar] (50) NULL,
[SetupHoursSpent] [nvarchar] (50) NULL,
[MaterialCost] [nvarchar] (50) NULL,
[LabourCost] [nvarchar] (50) NULL,
[OtherCost] [nvarchar] (50) NULL,
[Currency] [nvarchar] (50) NULL,
[ExchangeRate] [nvarchar] (50) NULL,
[WarehouseCode] [nvarchar] (50) NULL,
[BinNum] [nvarchar] (50) NULL,
[CostUnit] [nvarchar] (50) NULL,
[SalesOrderNum] [nvarchar] (50) NULL,
[CustomerNum] [nvarchar] (50) NULL,
[ProductionOrderCreaterName] [nvarchar] (50) NULL,
[BatchNum] [nvarchar] (50) NULL,
[CreatedTimeStamp] [nvarchar] (50) NULL,
[ModifiedTimeStamp] [nvarchar] (50) NULL
)
GO
