/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[AXHSE_HQ_Account]
(
[AccountNum] [nvarchar] (100) NULL,
[AccountName] [nvarchar] (500) NULL,
[AccountNameEnglish] [nvarchar] (500) NULL,
[AccountGroupName] [nvarchar] (500) NULL,
[AccountType] [nvarchar] (100) NULL,
[AccountStatus] [nvarchar] (100) NULL,
[Statement] [nvarchar] (100) NULL,
[Assets] [nvarchar] (100) NULL,
[Amortization] [nvarchar] (100) NULL,
[Costs] [nvarchar] (100) NULL,
[LiabilitiesAndEquity] [nvarchar] (100) NULL,
[Revenue] [nvarchar] (100) NULL,
[CurrentAssets] [nvarchar] (100) NULL,
[CurrentLiabilities] [nvarchar] (100) NULL,
[Deprecation] [nvarchar] (100) NULL,
[Equity] [nvarchar] (100) NULL,
[Liability] [nvarchar] (100) NULL,
[Interest] [nvarchar] (100) NULL,
[Tax] [nvarchar] (100) NULL,
[Materials] [nvarchar] (100) NULL,
[Expenses] [nvarchar] (100) NULL,
[AccountReceivables] [nvarchar] (100) NULL,
[CashAndEquivalents] [nvarchar] (100) NULL,
[AccountType2] [nvarchar] (100) NULL,
[AccountType3] [nvarchar] (100) NULL,
[AccountType4] [nvarchar] (100) NULL,
[AccountType5] [nvarchar] (100) NULL,
[AccountType6] [nvarchar] (100) NULL,
[AccountType7] [nvarchar] (100) NULL,
[AccountType8] [nvarchar] (100) NULL,
[AccountType9] [nvarchar] (100) NULL,
[AccountType10] [nvarchar] (100) NULL,
[AccountGroup2] [nvarchar] (100) NULL,
[AccountGroup3] [nvarchar] (100) NULL,
[StatementNum] [nvarchar] (100) NULL
)
GO
