/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[AXHSE_HQ_OpenBalance_sharepoint]
(
[PartitionKey] [nvarchar] (50) NULL,
[Company] [nvarchar] (50) NULL,
[AccountNum] [nvarchar] (50) NULL,
[Description] [nvarchar] (50) NULL,
[Opening Balance] [nvarchar] (50) NULL,
[TransactionDate] [nvarchar] (50) NULL,
[AccountingDate] [nvarchar] (50) NULL
)
GO
