/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[AXI_HQ_Account]
(
[Company] [nvarchar] (8) NULL,
[AccountNum] [nvarchar] (50) NOT NULL,
[AccountName] [nvarchar] (100) NULL,
[AccountStatus] [nvarchar] (50) NULL,
[BalanceAccount] [nvarchar] (100) NULL,
[TransactionAccount] [nvarchar] (100) NULL,
[Assets] [nvarchar] (100) NULL,
[Costs] [nvarchar] (100) NULL,
[LiabilitiesAndEquity] [nvarchar] (100) NULL,
[Revenue] [nvarchar] (100) NULL,
[CurrentAssets] [nvarchar] (100) NULL,
[CurrentLiabilities] [nvarchar] (100) NULL,
[Depreciation] [nvarchar] (100) NULL,
[Equity] [nvarchar] (100) NULL,
[AccountReceivables] [nvarchar] (100) NULL,
[CashAndEquivalents] [nvarchar] (100) NULL,
[AccountType] [nvarchar] (50) NULL,
[AccountType2] [nvarchar] (50) NULL,
[AccountType3] [nvarchar] (50) NULL,
[AccountType4] [nvarchar] (50) NULL,
[AccountType5] [nvarchar] (100) NULL,
[AccountType6] [nvarchar] (100) NULL,
[AccountType7] [nvarchar] (100) NULL,
[AccountType8] [nvarchar] (100) NULL,
[AccountType9] [nvarchar] (100) NULL,
[AccountType10] [nvarchar] (100) NULL,
[AccountGroupNum] [nvarchar] (50) NULL,
[AccountGroupName] [nvarchar] (50) NULL,
[AccountGroup] [nvarchar] (50) NULL,
[Statement] [nvarchar] (100) NULL,
[StatementNum] [int] NULL,
[AccRes1] [nvarchar] (100) NULL,
[AccRes2] [nvarchar] (100) NULL,
[AccRes3] [nvarchar] (100) NULL
)
GO
