/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[AXI_HQ_OpenBalance]
(
[PartitionKey] [varchar] (50) NULL,
[Company] [nvarchar] (8) NOT NULL,
[AccountNum] [nvarchar] (50) NULL,
[CostUnitNum] [nvarchar] (50) NULL,
[CostBearerNum] [nvarchar] (50) NULL,
[ProjectNum] [nvarchar] (50) NULL,
[JournalType] [nvarchar] (50) NULL,
[JournalDate] [date] NULL,
[Description] [nvarchar] (500) NULL,
[OpeningBalance] [decimal] (18, 4) NULL,
[Currency] [nvarchar] (50) NULL,
[ExchangeRate] [decimal] (18, 4) NULL,
[OBRes1] [nvarchar] (100) NULL,
[OBRes2] [nvarchar] (100) NULL,
[OBRes3] [nvarchar] (100) NULL
)
GO
