/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[AXI_HQ_SalesLedger]
(
[Company] [nvarchar] (8) NOT NULL,
[CustomerNum] [nvarchar] (50) NULL,
[SalesInvoiceNum] [nvarchar] (50) NOT NULL,
[SalesInvoiceDate] [date] NULL,
[SalesDueDate] [date] NULL,
[SalesLastPaymentDate] [date] NULL,
[InvoiceAmount] [decimal] (18, 4) NULL,
[PaidInvoiceAmount] [decimal] (18, 4) NULL,
[RemainingInvoiceAmount] [decimal] (18, 4) NULL,
[ExchangeRate] [decimal] (18, 4) NULL,
[Currency] [nvarchar] (10) NULL,
[VATAmount] [decimal] (18, 4) NULL,
[VATCode] [nvarchar] (50) NULL,
[VATCodeDesc] [nvarchar] (300) NULL,
[PayToName] [nvarchar] (100) NULL,
[PayToCity] [nvarchar] (50) NULL,
[PayToContact] [nvarchar] (50) NULL,
[PaymentTerms] [nvarchar] (50) NULL,
[SLRes1] [nvarchar] (100) NULL,
[SLRes2] [nvarchar] (100) NULL,
[SLRes3] [nvarchar] (100) NULL,
[SalesLedgerCode] [nvarchar] (500) NULL,
[PartitionKey] [varchar] (50) NOT NULL,
[AccountingDate] [date] NULL,
[AgingPeriod] [nvarchar] (100) NULL,
[InvoiceAmountLC] [decimal] (18, 4) NULL,
[PaidInvoiceAmountLC] [decimal] (18, 4) NULL,
[RemainingInvoiceAmountLC] [decimal] (18, 4) NULL,
[VATAmountLC] [decimal] (18, 4) NULL
)
GO
