/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[AXI_HQ_PurchaseLedger]
(
[PartitionKey] [varchar] (50) NOT NULL,
[Company] [nvarchar] (8) NOT NULL,
[SupplierNum] [nvarchar] (50) NOT NULL,
[PurchaseInvoiceNum] [nvarchar] (50) NOT NULL,
[PurchaseInvoiceDate] [date] NULL,
[PurchaseDueDate] [date] NULL,
[PurchaseLastPaymentDate] [date] NULL,
[InvoiceAmount] [decimal] (18, 4) NULL,
[ExchangeRate] [decimal] (18, 4) NULL,
[Currency] [nvarchar] (10) NOT NULL,
[VATAmount] [decimal] (18, 4) NULL,
[VATCode] [nvarchar] (10) NULL,
[PayToName] [nvarchar] (100) NULL,
[PayToCity] [nvarchar] (50) NULL,
[PayToContact] [nvarchar] (50) NULL,
[PaymentTerms] [nvarchar] (10) NULL,
[PrePaymentNum] [nvarchar] (50) NULL,
[LastPaymentNum] [nvarchar] (50) NULL,
[PaidInvoiceAmount] [decimal] (18, 4) NULL,
[AccountingDate] [date] NULL,
[AgingPeriod] [nvarchar] (50) NULL,
[VATCodeDesc] [nvarchar] (300) NULL,
[RemainingInvoiceAmount] [decimal] (18, 4) NULL,
[PLRes1] [nvarchar] (100) NULL,
[PLRes2] [nvarchar] (100) NULL,
[PLRes3] [nvarchar] (100) NULL,
[LinkToOriginalInvoice] [nvarchar] (500) NULL,
[InvoiceAmountLC] [decimal] (18, 4) NULL,
[VATAmountLC] [decimal] (18, 4) NULL,
[PaidInvoiceAmountLC] [decimal] (18, 4) NULL,
[RemainingInvoiceAmountLC] [decimal] (18, 4) NULL
)
GO
