/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[AXI_HQ_Project]
(
[PartitionKey] [varchar] (50) NOT NULL,
[Company] [nvarchar] (8) NOT NULL,
[MainProjectNum] [nvarchar] (50) NULL,
[ProjectNum] [nvarchar] (50) NOT NULL,
[ProjectDescription] [nvarchar] (500) NULL,
[Organisation] [nvarchar] (50) NULL,
[ProjectStatus] [nvarchar] (50) NULL,
[ProjectCategory] [nvarchar] (50) NULL,
[WBSElement] [nvarchar] (50) NULL,
[ObjectNum] [nvarchar] (50) NULL,
[Level] [nvarchar] (50) NULL,
[Currency] [nvarchar] (50) NULL,
[WarehouseCode] [nvarchar] (50) NULL,
[ProjectResponsible] [nvarchar] (50) NULL,
[Comments] [nvarchar] (500) NULL,
[StartDate] [date] NULL,
[EndDate] [date] NULL,
[EstEndDate] [date] NULL,
[ProjectCompletion] [decimal] (18, 4) NULL,
[TotalCost] [decimal] (18, 4) NULL
)
GO
