/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[AXI_HQ_Account_map_complement]
(
[Konto] [nvarchar] (50) NOT NULL,
[Beskrivning] [nvarchar] (100) NULL,
[Kontogrupp] [nvarchar] (100) NULL,
[Power_BI] [nvarchar] (100) NULL
)
GO
