/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[AXI_HQ_GeneralLedger]
(
[PartitionKey] [varchar] (50) NULL,
[Company] [nvarchar] (8) NOT NULL,
[AccountNum] [nvarchar] (50) NULL,
[CostUnitNum] [nvarchar] (50) NULL,
[CostBearerNum] [nvarchar] (50) NULL,
[JournalType] [nvarchar] (50) NULL,
[JournalDate] [date] NULL,
[JournalNum] [nvarchar] (50) NOT NULL,
[JournalLine] [nvarchar] (50) NULL,
[AccountingDate] [date] NULL,
[Description] [nvarchar] (500) NULL,
[Currency] [nvarchar] (50) NULL,
[ExchangeRate] [decimal] (18, 4) NULL,
[InvoiceAmount] [decimal] (18, 4) NULL,
[CustomerNum] [nvarchar] (50) NULL,
[SupplierNum] [nvarchar] (50) NULL,
[SalesInvoiceNum] [nvarchar] (50) NULL,
[PurchaseInvoiceNum] [nvarchar] (50) NULL,
[SupplierInvoiceNum] [nvarchar] (50) NULL,
[LinkToOriginalInvoice] [nvarchar] (500) NULL,
[DeliveryCountry] [nvarchar] (100) NULL,
[TransactionNum] [nvarchar] (50) NULL,
[VATCode] [nvarchar] (50) NULL,
[VATCodeDesc] [nvarchar] (500) NULL,
[GLRes1] [nvarchar] (100) NULL,
[GLRes2] [nvarchar] (100) NULL,
[GLRes3] [nvarchar] (100) NULL,
[InvoiceAmountLC] [decimal] (18, 4) NULL
)
GO
