/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[AXI_HQ_Account_excel]
(
[AccountNum] [nvarchar] (50) NULL,
[PartitionKey] [varchar] (50) NULL,
[AccountName] [nvarchar] (200) NULL,
[AccountName English] [nvarchar] (200) NULL,
[AccountStatus] [nvarchar] (50) NULL,
[BalanceAccount] [nvarchar] (100) NULL,
[TransactionAccount] [nvarchar] (100) NULL,
[Assets] [nvarchar] (100) NULL,
[Amortization] [nvarchar] (50) NULL,
[Costs] [nvarchar] (100) NULL,
[LiabilitiesAndEquity] [nvarchar] (100) NULL,
[Revenue] [nvarchar] (100) NULL,
[CurrentAssets] [nvarchar] (100) NULL,
[CurrentLiabilities] [nvarchar] (100) NULL,
[Deprecation] [nvarchar] (100) NULL,
[Equity] [nvarchar] (100) NULL,
[Liability] [nvarchar] (50) NULL,
[Interest] [nvarchar] (50) NULL,
[Tax] [nvarchar] (50) NULL,
[Materials] [nvarchar] (50) NULL,
[Expenses] [nvarchar] (50) NULL,
[AccountReceivables] [nvarchar] (100) NULL,
[CashAndEquivalents] [nvarchar] (100) NULL,
[AccountType] [nvarchar] (50) NULL,
[AccountType2] [nvarchar] (50) NULL,
[AccountType3] [nvarchar] (50) NULL,
[AccountType4] [nvarchar] (50) NULL,
[AccountType5] [nvarchar] (100) NULL,
[AccountType6] [nvarchar] (100) NULL,
[AccountType7] [nvarchar] (100) NULL,
[AccountType8] [nvarchar] (100) NULL,
[AccountType9] [nvarchar] (100) NULL,
[AccountType10] [nvarchar] (100) NULL,
[AccountGroupNum] [nvarchar] (50) NULL,
[AccountGroupName] [nvarchar] (200) NULL,
[AccountGroup] [nvarchar] (100) NULL,
[AccountGroup2] [nvarchar] (100) NULL,
[AccountGroup3] [nvarchar] (100) NULL,
[Statement] [nvarchar] (100) NULL,
[StatementNum] [nvarchar] (50) NULL,
[AccRes1] [nvarchar] (100) NULL,
[AccRes2] [nvarchar] (100) NULL,
[AccRes3] [nvarchar] (100) NULL
)
GO
