/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[AXI_HQ_Budget]
(
[PartitionKey] [nvarchar] (50) NULL,
[BudgetType] [nvarchar] (50) NULL,
[BudgetName] [nvarchar] (100) NULL,
[BudgetDescription] [nvarchar] (500) NULL,
[Company] [nvarchar] (8) NOT NULL,
[FiscalPeriod] [nvarchar] (100) NULL,
[FiscalPeriodDate] [date] NULL,
[PeriodType] [nvarchar] (100) NULL,
[CustomerNum] [nvarchar] (50) NULL,
[CustomerGroup] [nvarchar] (100) NULL,
[ProductGroup] [nvarchar] (50) NULL,
[PartNum] [nvarchar] (100) NULL,
[SalesPersonCode] [nvarchar] (50) NULL,
[SalesPersonName] [nvarchar] (100) NULL,
[BudgetSales] [decimal] (18, 4) NULL,
[BudgetCost] [decimal] (18, 4) NULL,
[Budget] [decimal] (18, 4) NULL,
[WarehouseCode] [nvarchar] (50) NULL,
[CostBearerNum] [nvarchar] (50) NULL,
[CostUnitNum] [nvarchar] (50) NULL,
[AccountNum] [nvarchar] (50) NULL,
[AccountGroupNum] [nvarchar] (50) NULL,
[ProjectNum] [nvarchar] (50) NULL
)
GO
