/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[BELL_SI_OLine]
(
[PartitionKey] [varchar] (50) NOT NULL,
[Company] [nvarchar] (8) NOT NULL,
[Archived] [nvarchar] (50) NULL,
[CustNum] [nvarchar] (50) NULL,
[OrderNum] [nvarchar] (50) NULL,
[OrderLine] [nvarchar] (50) NULL,
[OrderSubLine] [nvarchar] (50) NULL,
[OrderRelNum] [nvarchar] (50) NULL,
[OrderDate] [date] NULL,
[DeliveDate] [date] NULL,
[InvoiceNum] [nvarchar] (50) NULL,
[OrderQty] [decimal] (18, 4) NULL,
[DelivQty] [decimal] (18, 4) NULL,
[RemainingQty] [decimal] (18, 4) NULL,
[UnitPrice] [numeric] (18, 4) NULL,
[UnitCost] [numeric] (18, 4) NULL,
[SumUnitCost] [numeric] (18, 4) NULL,
[SumUnitPrice] [numeric] (18, 4) NULL,
[SumOutstandingAmount] [numeric] (18, 4) NULL,
[SumOutstandingAmountExclVAT] [numeric] (18, 4) NULL,
[CurrExchRate] [decimal] (18, 4) NULL,
[CurrencyCode] [nvarchar] (50) NULL,
[OpenRelease] [nvarchar] (1) NULL,
[DiscountPercent] [decimal] (18, 4) NULL,
[DiscountAmount] [numeric] (18, 4) NULL,
[PartNum] [nvarchar] (50) NULL,
[PartStatus] [nvarchar] (50) NULL,
[NeedByDate] [date] NULL,
[SalesPerson] [nvarchar] (50) NULL,
[ReturnComment] [nvarchar] (max) NULL,
[SalesReturnOrderNum] [nvarchar] (50) NULL,
[SalesReturnInvoiceNum] [nvarchar] (50) NULL,
[WarehouseCode] [nvarchar] (50) NULL,
[SalesChannel] [nvarchar] (50) NULL
)
GO
