/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[BK_SE_SalesLedger]
(
[PartitionKey] [varchar] (50) NOT NULL,
[Company] [nvarchar] (8) NULL,
[CustomerID] [nvarchar] (50) NULL,
[InvoiceID] [nvarchar] (50) NULL,
[DueDate] [date] NULL,
[LastPayment] [date] NULL
)
GO
