/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[CER_DE_Warehouse]
(
[PartitionKey] [varchar] (50) NULL,
[Company] [nvarchar] (8) NULL,
[WarehouseCode] [nvarchar] (10) NULL,
[WarehouseName] [nvarchar] (100) NULL,
[WarehouseAddress] [nvarchar] (131) NULL
)
GO
