/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[CER_NO_OLine]
(
[PartitionKey] [varchar] (50) NOT NULL,
[Company] [nvarchar] (8) NOT NULL,
[CustNum] [nvarchar] (50) NULL,
[OrderNum] [nvarchar] (50) NULL,
[OrderLine] [nvarchar] (50) NULL,
[OrderRelNum] [nvarchar] (50) NULL,
[OrderDate] [date] NULL,
[DelivDate] [date] NULL,
[InvoiceNum] [nvarchar] (50) NULL,
[OrderQty] [decimal] (18, 4) NULL,
[DelivQty] [decimal] (18, 4) NULL,
[RemainingQty] [decimal] (18, 4) NULL,
[UnitPrice] [numeric] (18, 4) NULL,
[UnitCost] [numeric] (18, 4) NULL,
[SumUnitCost] [numeric] (18, 4) NULL,
[SumUnitPrice] [numeric] (18, 4) NULL,
[CurrExchRate] [decimal] (18, 4) NULL,
[OpenRelease] [nvarchar] (10) NULL,
[DiscountPercent] [decimal] (18, 4) NULL,
[DiscountAmount] [numeric] (18, 4) NULL,
[PartNum] [nvarchar] (50) NULL,
[PartStatus] [nvarchar] (50) NULL,
[NeedbyDate] [date] NULL,
[SalesPerson] [nvarchar] (50) NULL,
[WarehouseCode] [nvarchar] (50) NULL,
[LineFlag] [nvarchar] (50) NULL
)
GO
