/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[CER_DE_StockBalance]
(
[PartitionKey] [varchar] (50) NULL,
[Company] [nvarchar] (8) NULL,
[WarehouseCode] [nvarchar] (10) NULL,
[Currency] [nvarchar] (10) NULL,
[BinNum] [int] NULL,
[BatchNum] [nvarchar] (50) NULL,
[PartNum] [nvarchar] (20) NULL,
[DelivTime] [int] NULL,
[LastStockTakeDate] [date] NULL,
[LastStdCostCalDate] [date] NULL,
[MaxStockQty] [int] NULL,
[StockBalance] [decimal] (9, 2) NULL,
[StockValue] [decimal] (9, 2) NULL,
[ReserveQty] [int] NULL,
[BackOrderQty] [decimal] (9, 2) NULL,
[OrderQty] [decimal] (9, 2) NULL,
[ReOrderLevel] [decimal] (9, 2) NULL,
[SafetyStock] [decimal] (9, 2) NULL,
[OptimalOrderQty] [int] NULL,
[AvgCost] [decimal] (9, 2) NULL,
[SBRes1] [varchar] (1) NULL,
[SBRes2] [varchar] (1) NULL,
[SBRes3] [varchar] (1) NULL
)
GO
