/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[CER_DK_Supplier]
(
[PartitionKey] [varchar] (50) NOT NULL,
[Company] [nvarchar] (8) NOT NULL,
[SupplierNum] [nvarchar] (50) NOT NULL,
[MainSupplierName] [nvarchar] (100) NULL,
[SupplierName] [nvarchar] (100) NULL,
[AddressLine1] [nvarchar] (100) NULL,
[AddressLine2] [nvarchar] (100) NULL,
[AddressLine3] [nvarchar] (100) NULL,
[TelephoneNum] [nvarchar] (50) NULL,
[Email] [nvarchar] (200) NULL,
[ZipCode] [nvarchar] (50) NULL,
[City] [nvarchar] (100) NULL,
[District] [nvarchar] (100) NULL,
[Country] [nvarchar] (10) NULL,
[CountryName] [nvarchar] (100) NULL,
[Region] [nvarchar] (50) NULL,
[SupplierCategory] [nvarchar] (100) NULL,
[SupplierResponsible] [nvarchar] (100) NULL,
[AccountNum] [nvarchar] (50) NULL,
[VATNum] [nvarchar] (50) NULL,
[InternalExternal] [nvarchar] (50) NULL,
[CodeOfConduct] [nvarchar] (500) NULL,
[SupplierScore] [nvarchar] (50) NULL,
[MinOrderQty] [decimal] (18, 4) NULL,
[MinOrderValue] [decimal] (18, 4) NULL,
[Website] [nvarchar] (500) NULL,
[Comments] [nvarchar] (500) NULL,
[SRes1] [nvarchar] (50) NULL,
[SRes2] [nvarchar] (50) NULL,
[SRes3] [nvarchar] (50) NULL,
[CountryCode] [nvarchar] (10) NULL
)
GO
