/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[CER_NO_BC_StockTransaction]
(
[PartitionKey] [nvarchar] (50) NOT NULL,
[Company] [nvarchar] (50) NOT NULL,
[IndexKey] [nvarchar] (100) NULL,
[WarehouseCode] [nvarchar] (100) NULL,
[TransactionCodeDescription] [nvarchar] (100) NULL,
[PartNum] [nvarchar] (100) NULL,
[TransactionDate] [nvarchar] (100) NULL,
[TransactionQty] [nvarchar] (100) NULL,
[TransactionValue] [nvarchar] (100) NULL,
[TransactionCode] [nvarchar] (100) NULL,
[CustomerNum] [nvarchar] (100) NULL,
[SupplierNum] [nvarchar] (100) NULL,
[CreatedTimeStamp] [datetime] NULL,
[ModifiedTimeStamp] [datetime] NULL,
[IsInternalTransaction] [nvarchar] (100) NULL,
[Currency] [nvarchar] (100) NULL,
[ExchangeRate] [nvarchar] (100) NULL,
[TransactionTime] [nvarchar] (100) NULL
)
GO
