/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[CER_NO_BC_SalesInvoice]
(
[PartitionKey] [nvarchar] (50) NOT NULL,
[Company] [nvarchar] (8) NOT NULL,
[InvoiceDate] [nvarchar] (50) NULL,
[ActualDeliveryDate] [nvarchar] (50) NULL,
[SalesPersonName] [nvarchar] (100) NULL,
[CustNum] [nvarchar] (60) NULL,
[OrderNum] [nvarchar] (60) NULL,
[OrderLine] [nvarchar] (30) NULL,
[InvoiceNum] [nvarchar] (40) NULL,
[InvoiceLine] [nvarchar] (30) NULL,
[PartNum] [nvarchar] (50) NULL,
[SalesInvoiceQty] [nvarchar] (30) NULL,
[UnitPrice] [nvarchar] (30) NULL,
[UnitCost] [nvarchar] (30) NULL,
[VAT] [nvarchar] (30) NULL,
[Currency] [nvarchar] (30) NULL,
[ExchangeRate] [nvarchar] (30) NULL,
[WarehouseCode] [nvarchar] (50) NULL,
[ReturnNum] [nvarchar] (50) NULL,
[ReturnComment] [nvarchar] (200) NULL,
[systemCreatedAt] [nvarchar] (50) NULL,
[systemModifiedAt] [nvarchar] (50) NULL,
[Type] [varchar] (25) NULL,
[Department] [nvarchar] (40) NULL,
[dueDate] [date] NULL,
[DiscountAmount] [nvarchar] (40) NULL,
[WarehouseCodeLines] [nvarchar] (20) NULL,
[Cancelled] [nvarchar] (20) NULL
)
GO
