/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[CER_NO_PurchaseLedger]
(
[PartitionKey] [varchar] (50) NOT NULL,
[Company] [nvarchar] (8) NULL,
[SupplierNum] [nvarchar] (50) NULL,
[CompanySupplier] [nvarchar] (100) NULL,
[InvoiceNum] [nvarchar] (50) NULL,
[SupplierInvoiceNum] [nvarchar] (50) NULL,
[InvoiceDate] [date] NULL,
[DueDate] [date] NULL,
[LastPaymentDate] [date] NULL,
[DaysPastDue] [int] NULL,
[FiscalYear] [nchar] (4) NULL,
[FiscalPeriod] [nchar] (2) NULL,
[AgingPeriod] [nvarchar] (50) NULL,
[AgingSort] [int] NULL,
[Currency] [nchar] (10) NULL,
[ExchangeRate] [decimal] (18, 8) NULL,
[VATCode] [nchar] (4) NULL,
[VATCodeDesc] [nvarchar] (max) NULL,
[LocalAmount] [decimal] (18, 4) NULL,
[LocalRemainingAmount] [decimal] (18, 4) NULL,
[OriginalAmount] [decimal] (18, 4) NULL,
[RemainingAmount] [decimal] (18, 4) NULL,
[LinktoOriginalInvoice] [nvarchar] (500) NULL
)
GO
