/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[CER_DE_SalesLedger]
(
[PartitionKey] [nvarchar] (40) NULL,
[Company] [nvarchar] (18) NULL,
[Currency] [nvarchar] (15) NULL,
[CustomerNum] [nvarchar] (25) NULL,
[SalesInvoiceNum] [nvarchar] (30) NULL,
[SalesInvoiceDate] [nvarchar] (40) NULL,
[SalesDueDate] [nvarchar] (40) NULL,
[SalesLastPaymentDate] [nvarchar] (40) NULL,
[InvoiceAmount] [nvarchar] (25) NULL,
[PaidInvoiceAmount] [nvarchar] (25) NULL,
[RemainingInvoiceAmount] [nvarchar] (25) NULL,
[VATAmount] [nvarchar] (25) NULL,
[VATCode] [nvarchar] (50) NULL,
[VATCodeDesc] [nvarchar] (80) NULL,
[ExchangeRate] [nvarchar] (15) NULL,
[IsInvoiceClosed] [nvarchar] (15) NULL
)
GO
