/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[CER_NO_mapSite]
(
[Company] [nvarchar] (50) NULL,
[CostUnitNum] [nvarchar] (50) NULL,
[CostUnitName] [nvarchar] (100) NULL,
[CostUnitStatus] [nvarchar] (100) NULL,
[CostUnitGroup] [nvarchar] (100) NULL
)
GO
