/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[CER_NO_BC_Part]
(
[PartitionKey] [nvarchar] (50) NOT NULL,
[Company] [nvarchar] (8) NOT NULL,
[PartNum] [nvarchar] (200) NULL,
[PartDescription] [nvarchar] (200) NULL,
[PartDescription2] [nvarchar] (200) NULL,
[ProductGroup] [nvarchar] (400) NULL,
[CommodityCode] [nvarchar] (100) NULL,
[CountryOfOrigin] [nvarchar] (200) NULL,
[NetWeight] [nvarchar] (40) NULL,
[SupplierCode] [nvarchar] (200) NULL,
[ReorderLevel] [nvarchar] (40) NULL,
[systemCreatedAt] [nvarchar] (50) NULL,
[systemModifiedAt] [nvarchar] (50) NULL,
[PartStatus] [varchar] (10) NULL,
[SourceTable] [varchar] (15) NULL,
[ProductGroup2] [nvarchar] (400) NULL,
[childcode] [nvarchar] (10) NULL,
[parentcode] [nvarchar] (10) NULL,
[PartType] [nvarchar] (50) NULL
)
GO
