/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[CER_NO_BC_Customer]
(
[PartitionKey] [nvarchar] (50) NOT NULL,
[Company] [nvarchar] (8) NOT NULL,
[CustomerNum] [nvarchar] (100) NULL,
[CustomerName] [nvarchar] (200) NULL,
[AddressLine1] [nvarchar] (200) NULL,
[AddressLine2] [nvarchar] (200) NULL,
[TelephoneNumber1] [nvarchar] (100) NULL,
[Email] [nvarchar] (200) NULL,
[City] [nvarchar] (100) NULL,
[ZIP] [nvarchar] (100) NULL,
[CountryName] [nvarchar] (100) NULL,
[CustomerGroup] [nvarchar] (100) NULL,
[CustomerSubGroup] [nvarchar] (100) NULL,
[SalesPersonCode] [nvarchar] (100) NULL,
[SalesPersonName] [nvarchar] (100) NULL,
[VATNum] [nvarchar] (100) NULL,
[systemCreatedAt] [nvarchar] (50) NULL,
[systemModifiedAt] [nvarchar] (50) NULL,
[CountryCode] [nvarchar] (15) NULL,
[genBusPostingGroup] [nvarchar] (40) NULL,
[customerPostingGroup] [nvarchar] (50) NULL,
[CustomerIndustry] [nvarchar] (50) NULL
)
GO
