/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[CER_FI_Part]
(
[PartitionKey] [varchar] (50) NOT NULL,
[Company] [nvarchar] (8) NULL,
[PartNum] [nvarchar] (50) NULL,
[PartDescription] [nvarchar] (25) NULL,
[PartDescription2] [nvarchar] (25) NULL,
[ProductGroup] [nvarchar] (50) NULL,
[ProductGroup2] [nvarchar] (50) NULL,
[CommodityCode] [nvarchar] (14) NULL,
[CountryOfOrigin] [nvarchar] (50) NULL,
[NetWeight] [decimal] (18, 8) NULL,
[SupplierCode] [nvarchar] (10) NULL,
[ReorderLevel] [decimal] (20, 8) NULL,
[EAN] [nvarchar] (50) NULL,
[ProdCategory] [nvarchar] (50) NULL,
[ProdGroup] [nvarchar] (50) NULL,
[MainSupplier] [nvarchar] (50) NULL,
[AlternativeSupplier] [nvarchar] (50) NULL
)
GO
