/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[CER_NO_BC_Supplier]
(
[PartitionKey] [nvarchar] (50) NOT NULL,
[Company] [nvarchar] (100) NOT NULL,
[SupplierName] [nvarchar] (100) NULL,
[SupplierNum] [nvarchar] (100) NULL,
[AddressLine1] [nvarchar] (100) NULL,
[AddressLine2] [nvarchar] (100) NULL,
[TelephoneNum1] [nvarchar] (100) NULL,
[TelephoneNum2] [nvarchar] (100) NULL,
[Email] [nvarchar] (100) NULL,
[ZipCode] [nvarchar] (100) NULL,
[City] [nvarchar] (100) NULL,
[CountryCode] [nvarchar] (100) NULL,
[PrimaryPurchaser] [nvarchar] (100) NULL,
[VATNum] [nvarchar] (100) NULL,
[MinOrderValueCurrency] [nvarchar] (100) NULL,
[IsActiveRecord] [nvarchar] (100) NULL,
[Website] [nvarchar] (100) NULL,
[CreatedTimeStamp] [nvarchar] (100) NULL,
[ModifiedTimeStamp] [nvarchar] (100) NULL,
[IsMaterialSupplier] [nvarchar] (100) NULL,
[CodeOfConduct] [nvarchar] (100) NULL
)
GO
