/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[CER_NO_BC_PurchaseLedger]
(
[PartitionKey] [nvarchar] (50) NOT NULL,
[Company] [nvarchar] (50) NOT NULL,
[SupplierNum] [nvarchar] (50) NULL,
[PurchaseInvoiceNum] [nvarchar] (50) NULL,
[PurchaseInvoiceDate] [nvarchar] (50) NULL,
[Currency] [nvarchar] (50) NULL,
[ExchangeRate] [nvarchar] (50) NULL,
[SupplierInvoiceNum] [nvarchar] (50) NULL,
[IsInvoiceClosed] [nvarchar] (50) NULL,
[InvoiceAmount] [nvarchar] (50) NULL,
[PurchaseDueDate] [nvarchar] (50) NULL,
[RemainingInvoiceAmount] [nvarchar] (50) NULL,
[VATAmount] [nvarchar] (50) NULL,
[PaymentTerms] [nvarchar] (50) NULL,
[PayToName] [nvarchar] (50) NULL,
[PayToCity] [nvarchar] (50) NULL,
[PayToContact] [nvarchar] (50) NULL,
[CreatedTimeStamp] [nvarchar] (50) NULL,
[ModifiedTimeStamp] [nvarchar] (50) NULL,
[AccountingDate] [nvarchar] (50) NULL
)
GO
