/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[CER_DE_Supplier]
(
[PartitionKey] [varchar] (50) NULL,
[Company] [nvarchar] (8) NULL,
[SupplierNum] [nvarchar] (20) NULL,
[MainSupplierName] [int] NULL,
[SUPPLIERNAME] [nvarchar] (100) NULL,
[AddressLine1] [nvarchar] (100) NULL,
[AddressLine2] [nvarchar] (50) NULL,
[AddressLine3] [int] NULL,
[TelephoneNum] [nvarchar] (30) NULL,
[EMAIL] [nvarchar] (80) NULL,
[ZIPCODE] [nvarchar] (20) NULL,
[CITY] [nvarchar] (30) NULL,
[DISTRICT] [int] NULL,
[COUNTRY] [nvarchar] (10) NULL,
[CountryName] [nvarchar] (100) NULL,
[Region] [varchar] (1) NULL,
[ACCOUNTNUM] [nvarchar] (20) NULL,
[VATNUM] [nvarchar] (20) NULL,
[InternalExternal] [int] NULL,
[CODEOFCONDUCT] [int] NULL,
[SUPPLIERSCORE] [int] NULL,
[MinOrderQty] [int] NULL,
[MinOrderValue] [int] NULL,
[WEBSITE] [nvarchar] (80) NULL,
[Comments] [int] NULL,
[SRes1] [int] NULL,
[SRes2] [int] NULL,
[SRes3] [int] NULL,
[searchName] [nvarchar] (80) NULL
)
GO
