/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[CER_NO_SalesLedger]
(
[PartitionKey] [varchar] (50) NOT NULL,
[Company] [nvarchar] (8) NULL,
[CustNum] [nvarchar] (50) NULL,
[CompanyCustomer] [nvarchar] (100) NULL,
[InvoiceNum] [nvarchar] (50) NULL,
[InvoiceDate] [date] NULL,
[DueDate] [date] NULL,
[LastPaymentDate] [date] NULL,
[DaysPastDue] [smallint] NULL,
[FiscalYear] [smallint] NULL,
[FiscalPeriod] [smallint] NULL,
[AgingPeriod] [nvarchar] (100) NULL,
[AgingSort] [smallint] NULL,
[Currency] [nvarchar] (50) NULL,
[ExchangeRate] [decimal] (18, 8) NULL,
[VATCode] [nvarchar] (50) NULL,
[VATCodeDesc] [nvarchar] (500) NULL,
[LocalAmount] [decimal] (18, 4) NULL,
[LocalRemainingAmount] [decimal] (18, 4) NULL,
[OriginalAmount] [decimal] (18, 4) NULL,
[RemainingAmount] [decimal] (18, 4) NULL
)
GO
