/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[CER_NO_BC_Warehouse]
(
[PartitionKey] [nvarchar] (50) NOT NULL,
[Company] [nvarchar] (8) NOT NULL,
[WarehouseCode] [nvarchar] (50) NULL,
[WarehouseName] [nvarchar] (50) NULL,
[systemCreatedAt] [nvarchar] (50) NULL,
[systemModifiedAt] [nvarchar] (50) NULL,
[WarehouseAddress] [nvarchar] (80) NULL,
[WarehouseCountryCode] [nvarchar] (10) NULL,
[WarehouseCounty] [nvarchar] (50) NULL,
[WarehousePostalCode] [nvarchar] (15) NULL,
[WarehouseCity] [nvarchar] (50) NULL
)
GO
