/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[CER_DE_SalesOrder]
(
[PartitionKey] [nvarchar] (40) NULL,
[Company] [nvarchar] (20) NULL,
[CustomerNum] [nvarchar] (30) NULL,
[SalesOrderNum] [nvarchar] (30) NULL,
[SalesOrderLine] [nvarchar] (30) NULL,
[SalesOrderDate] [nvarchar] (30) NULL,
[ReqDelivDate] [nvarchar] (30) NULL,
[ExpShipDate] [nvarchar] (30) NULL,
[ActualShipDate] [nvarchar] (30) NULL,
[CommitedDelivDate] [nvarchar] (30) NULL,
[IsOrderClosed] [nvarchar] (10) NULL,
[OrderHandler] [nvarchar] (80) NULL,
[SalesOrderQty] [nvarchar] (25) NULL,
[DelivQty] [nvarchar] (25) NULL,
[RemainingQty] [nvarchar] (25) NULL,
[UnitPrice] [nvarchar] (25) NULL,
[UoM] [nvarchar] (30) NULL,
[WarehouseCode] [nvarchar] (30) NULL,
[UnitCost] [nvarchar] (25) NULL,
[Currency] [nvarchar] (10) NULL,
[ExchangeRate] [nvarchar] (30) NULL,
[DiscountPercent] [nvarchar] (25) NULL,
[DiscountAmount] [nvarchar] (25) NULL,
[PartNum] [nvarchar] (45) NULL,
[SalesPersonName] [nvarchar] (80) NULL,
[SalesOrderCategory] [nvarchar] (50) NULL,
[SalesOrderType] [nvarchar] (50) NULL
)
GO
