/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[COC_ALL_SupplierTest]
(
[SupplierID] [bigint] NULL,
[Company] [nvarchar] (50) NULL,
[SupplierNum] [nvarchar] (50) NULL,
[SupplierName] [nvarchar] (50) NULL,
[CodeOfConductIsSigned] [nvarchar] (50) NULL
)
GO
