/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[CYE_ES_PartTranLine]
(
[PartitionKey] [varchar] (50) NULL,
[Company] [nvarchar] (8) NOT NULL,
[SysDate] [nvarchar] (50) NULL,
[TranDate] [date] NULL,
[WarehouseCode] [nvarchar] (50) NULL,
[BinNumber] [nvarchar] (50) NULL,
[LotNum] [nvarchar] (50) NULL,
[TranType] [nvarchar] (50) NULL,
[PartNum] [nvarchar] (50) NULL,
[TranQty] [decimal] (18, 4) NULL,
[AvgCost] [decimal] (18, 4) NULL,
[SysRowID] [nvarchar] (50) NULL
)
GO
