/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[CYE_ES_RLS]
(
[EmailID] [nvarchar] (100) NOT NULL,
[Company] [nvarchar] (50) NOT NULL,
[Name] [nvarchar] (50) NOT NULL,
[Email] [nvarchar] (50) NOT NULL
)
GO
