/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[DnBCustomerAndSupplier]
(
[PartitionKey] [varchar] (50) NULL,
[dw_id] [binary] (32) NULL,
[BusinessName1] [varchar] (100) NULL,
[BusinessName2] [varchar] (100) NULL,
[VisitStreetAddress] [varchar] (200) NULL,
[MailStreetAddress] [varchar] (100) NULL,
[VisitPostalCode] [varchar] (100) NULL,
[ProvinceName] [varchar] (100) NULL,
[CountryCode] [varchar] (100) NULL,
[TelephoneNumber] [varchar] (100) NULL,
[LocalRegistrationNumber] [varchar] (100) NULL,
[Email] [varchar] (100) NULL,
[is_customer] [bit] NULL,
[lastDateDetected] [varchar] (60) NULL,
[Company] [nvarchar] (15) NULL
)
GO
