/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[FOR_PL_OLine]
(
[PartitionKey] [varchar] (50) NOT NULL,
[Company] [nvarchar] (50) NOT NULL,
[CustomerNum] [nvarchar] (50) NULL,
[SalesOrderNum] [nvarchar] (50) NOT NULL,
[SalesOrderLine] [nvarchar] (50) NULL,
[SalesOrderStatus] [nvarchar] (50) NULL,
[SalesOrderLineStatus] [nvarchar] (50) NULL,
[SalesOrderDate] [date] NULL,
[NeedbyDate] [date] NULL,
[ExpDelivDate] [date] NULL,
[SalesOrderQty] [decimal] (18, 8) NULL,
[DelivQty] [decimal] (18, 8) NULL,
[RemainingQty] [decimal] (18, 8) NULL,
[UoM] [nvarchar] (50) NULL,
[UnitPrice] [decimal] (18, 8) NULL,
[UnitCost] [decimal] (18, 8) NULL,
[Currency] [nvarchar] (50) NULL,
[ExchangeRate] [decimal] (18, 8) NULL,
[DiscountPercent] [decimal] (18, 8) NULL,
[DiscountAmount] [decimal] (18, 8) NULL,
[PartNum] [nvarchar] (50) NULL,
[PartType] [nvarchar] (50) NULL,
[SalesPersonName] [nvarchar] (100) NULL,
[WarehouseCode] [nvarchar] (50) NULL,
[ProjectNum] [nvarchar] (50) NULL,
[IsCancelled] [nvarchar] (50) NULL,
[TargetType] [nvarchar] (50) NULL
)
GO
