/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[FOR_ES_SalesLedger]
(
[PartitionKey] [varchar] (50) NOT NULL,
[Company] [nvarchar] (8) NULL,
[CustomerNum] [nvarchar] (50) NULL,
[SalesInvoiceNum] [nvarchar] (50) NULL,
[SalesInvoiceDate] [datetime] NULL,
[DueDate] [datetime] NULL,
[InvoiceAmount] [decimal] (18, 8) NULL,
[RemainingInvoiceAmount] [decimal] (18, 8) NULL,
[ExchangeRate] [decimal] (18, 8) NULL,
[Currency] [nvarchar] (50) NULL,
[VATAmount] [decimal] (18, 8) NULL,
[VATCode] [nvarchar] (50) NULL,
[PaymentTerms] [nvarchar] (50) NULL,
[PayMethod] [nvarchar] (50) NULL
)
GO
