/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[FOR_ES_StockBalance]
(
[PartitionKey] [varchar] (50) NOT NULL,
[Company] [nvarchar] (8) NOT NULL,
[WarehouseCode] [nvarchar] (10) NULL,
[WarehouseName] [nvarchar] (80) NULL,
[PartNum] [nvarchar] (100) NULL,
[MaxStockQty] [decimal] (9, 2) NULL,
[StockBalance] [decimal] (9, 2) NULL,
[StockValue] [decimal] (9, 2) NULL,
[ReserveQty] [decimal] (9, 2) NULL,
[OrderQty] [decimal] (9, 2) NULL,
[SafetyStock] [decimal] (9, 2) NULL,
[AvgCost] [decimal] (9, 2) NULL
)
GO
