/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[FOR_SE_Account]
(
[PartitionKey] [nvarchar] (50) NULL,
[Company] [nvarchar] (50) NULL,
[Account] [nvarchar] (80) NULL,
[AccountNum] [nvarchar] (50) NULL,
[AccountName] [nvarchar] (50) NULL,
[AccountStatus] [nvarchar] (50) NULL,
[AccountType] [nvarchar] (50) NULL,
[AccountType2] [nvarchar] (50) NULL,
[AccountType3] [nvarchar] (50) NULL,
[AccountType4] [nvarchar] (50) NULL,
[AccountType5] [nvarchar] (50) NULL,
[AccountGroupNum] [nvarchar] (50) NULL,
[AccountGroupName] [nvarchar] (50) NULL,
[AccountGroup] [nvarchar] (50) NULL,
[Statement] [nvarchar] (50) NULL,
[StatementNum] [nvarchar] (50) NULL
)
GO
