/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[FOR_ES_Supplier]
(
[PartitionKey] [varchar] (50) NOT NULL,
[Company] [nvarchar] (8) NOT NULL,
[SupplierNum] [nvarchar] (20) NULL,
[MainSupplierName] [nvarchar] (80) NULL,
[SupplierName] [nvarchar] (100) NULL,
[AddressLine1] [nvarchar] (100) NULL,
[TelephoneNum] [nvarchar] (100) NULL,
[Email] [nvarchar] (100) NULL,
[ZipCode] [nvarchar] (100) NULL,
[City] [nvarchar] (100) NULL,
[District] [nvarchar] (100) NULL,
[CountryName] [nvarchar] (100) NULL,
[SupplierResponsible] [nvarchar] (100) NULL,
[VATNum] [nvarchar] (100) NULL,
[CodeOfConduct_Group] [nvarchar] (100) NULL,
[CodeOfConduct] [nvarchar] (100) NULL,
[Website] [nvarchar] (100) NULL,
[SupplierCategory] [nvarchar] (100) NULL,
[SupplierScore] [nvarchar] (30) NULL,
[SupplierCategoryCode] [nvarchar] (15) NULL,
[OrganizationNum] [nvarchar] (50) NULL
)
GO
