/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[FOR_PL_Customer]
(
[PartitionKey] [varchar] (50) NOT NULL,
[Company] [nvarchar] (50) NOT NULL,
[CustomerNum] [nvarchar] (50) NOT NULL,
[MainCustomerName] [nvarchar] (200) NULL,
[CustomerName] [nvarchar] (200) NULL,
[AddressLine1] [nvarchar] (200) NULL,
[TelephoneNum1] [nvarchar] (50) NULL,
[TelephoneNum2] [nvarchar] (50) NULL,
[Email] [nvarchar] (100) NULL,
[ZipCode] [nvarchar] (50) NULL,
[City] [nvarchar] (100) NULL,
[State] [nvarchar] (100) NULL,
[CountryName] [nvarchar] (100) NULL,
[CustomerIndustry] [nvarchar] (100) NULL,
[CustomerSubIndustry] [nvarchar] (100) NULL,
[CustomerGroup] [nvarchar] (100) NULL,
[CustomerSubGroup] [nvarchar] (100) NULL,
[SalesPersonCode] [nvarchar] (50) NULL,
[SalesPersonName] [nvarchar] (100) NULL,
[VATNum] [nvarchar] (50) NULL,
[AccountNum] [nvarchar] (50) NULL,
[InternalExternal] [nvarchar] (50) NULL,
[SalesDistrict] [varchar] (50) NULL,
[CRes1] [nvarchar] (100) NULL
)
GO
