/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[FOR_PL_Part]
(
[PartitionKey] [varchar] (50) NOT NULL,
[Company] [nvarchar] (50) NOT NULL,
[PartNum] [nvarchar] (50) NOT NULL,
[PartName] [nvarchar] (100) NULL,
[PartDescription3] [nvarchar] (300) NULL,
[ProductGroup] [nvarchar] (100) NULL,
[ProductGroup2] [nvarchar] (100) NULL,
[ProductGroup3] [nvarchar] (100) NULL,
[ProductGroup4] [nvarchar] (100) NULL,
[Brand] [nvarchar] (100) NULL,
[PartStatus] [nvarchar] (50) NULL,
[NetWeight] [decimal] (18, 8) NULL,
[UoM] [nvarchar] (50) NULL,
[Barcode] [nvarchar] (50) NULL,
[ReOrderLevel] [decimal] (18, 8) NULL,
[StartDate] [date] NULL,
[PARes1] [nvarchar] (50) NULL,
[GrupaGTU] [nvarchar] (50) NULL,
[PKWIU] [nvarchar] (50) NULL
)
GO
