/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[FOR_PL_StockTransaction]
(
[PartitionKey] [varchar] (50) NULL,
[Company] [varchar] (20) NULL,
[IndexKey] [varchar] (20) NULL,
[WarehouseCode] [varchar] (20) NULL,
[TransactionCode] [varchar] (20) NULL,
[TransactionCodeDescription] [nvarchar] (80) NULL,
[CustomerNum] [nvarchar] (60) NULL,
[SupplierNum] [nvarchar] (60) NULL,
[PartNum] [nvarchar] (60) NULL,
[TransactionDate] [nvarchar] (60) NULL,
[TransactionTime] [nvarchar] (60) NULL,
[TransactionQty] [nvarchar] (60) NULL,
[TransactionValue] [nvarchar] (60) NULL,
[CostPrice] [nvarchar] (60) NULL,
[Currency] [nvarchar] (60) NULL,
[ExchangeRate] [nvarchar] (60) NULL,
[Reference] [nvarchar] (60) NULL,
[CreatedTimeStamp] [nvarchar] (50) NULL,
[IsInternalTransaction] [nvarchar] (10) NULL
)
GO
