/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[FOR_PL_PurchaseOrder]
(
[PartitionKey] [varchar] (50) NULL,
[Company] [varchar] (20) NULL,
[PurchaseOrderNum] [nvarchar] (50) NULL,
[PurchaseOrderLine] [nvarchar] (50) NULL,
[PurchaseOrderDate] [nvarchar] (50) NULL,
[IsClosed] [nvarchar] (20) NULL,
[OrgReqDelivDate] [nvarchar] (50) NULL,
[OrgCommittedShipDate] [nvarchar] (50) NULL,
[CommittedDelivDate] [nvarchar] (50) NULL,
[OrgCommittedDelivDate] [nvarchar] (50) NULL,
[CommittedShipDate] [nvarchar] (50) NULL,
[ActualDelivDate] [nvarchar] (50) NULL,
[PartNum] [nvarchar] (100) NULL,
[SupplierNum] [nvarchar] (50) NULL,
[SupplierPartNum] [nvarchar] (100) NULL,
[SupplierInvoiceNum] [nvarchar] (200) NULL,
[DelivCustomerNum] [nvarchar] (50) NULL,
[PurchaseOrderQty] [nvarchar] (50) NULL,
[ReceiveQty] [nvarchar] (50) NULL,
[UoM] [nvarchar] (50) NULL,
[UnitPrice] [nvarchar] (50) NULL,
[DiscountPercent] [nvarchar] (50) NULL,
[DiscountAmount] [nvarchar] (50) NULL,
[Currency] [nvarchar] (50) NULL,
[ExchangeRate] [nvarchar] (50) NULL,
[PurchaserName] [nvarchar] (310) NULL,
[WarehouseCode] [nvarchar] (50) NULL,
[ReceivingNum] [nvarchar] (200) NULL,
[Comments] [nvarchar] (600) NULL,
[CreatedTimeStamp] [nvarchar] (50) NULL,
[ModifiedTimeStamp] [nvarchar] (50) NULL,
[PurchaseOrderType] [nvarchar] (50) NULL,
[PurchaseOrderSubLine] [nvarchar] (50) NULL,
[PurchaseOrderStatus] [nvarchar] (25) NULL
)
GO
