/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[FOR_PL_PurchaseLedger]
(
[PartitionKey] [varchar] (50) NOT NULL,
[Company] [nvarchar] (5) NULL,
[SupplierNum] [nvarchar] (15) NULL,
[PurchaseInvoiceNum] [nvarchar] (60) NULL,
[PurchaseInvoiceDate] [nvarchar] (50) NULL,
[InvoiceAmount] [nvarchar] (60) NULL,
[Currency] [nvarchar] (3) NULL,
[ExchangeRate] [nvarchar] (60) NULL,
[SupplierInvoiceNum] [nvarchar] (100) NULL,
[PurchaseDueDate] [nvarchar] (50) NULL,
[PurchaseLastPaymentDate] [nvarchar] (60) NULL,
[PaidInvoiceAmount] [nvarchar] (60) NULL,
[RemainingInvoiceAmount] [nvarchar] (60) NULL,
[VATAmount] [nvarchar] (15) NULL,
[PaymentTerms] [nvarchar] (60) NULL,
[IsInvoiceCLosed] [nvarchar] (2) NULL,
[CreatedTimeStamp] [nvarchar] (60) NULL,
[ModifiedTimeStamp] [nvarchar] (60) NULL
)
GO
