/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[FOR_SE_SOLine]
(
[PartitionKey] [varchar] (50) NOT NULL,
[Company] [nvarchar] (8) NOT NULL,
[InvoiceDate] [date] NULL,
[ActualDeliveryDate] [date] NULL,
[SalesPerson] [nvarchar] (50) NULL,
[CustNum] [nvarchar] (50) NULL,
[OrderNum] [nvarchar] (50) NULL,
[OrderLine] [nvarchar] (50) NULL,
[OrderSubLine] [nvarchar] (50) NULL,
[OrderRel] [nvarchar] (50) NULL,
[InvoiceNum] [nvarchar] (50) NULL,
[InvoiceLine] [nvarchar] (50) NULL,
[CreditMemo] [int] NULL,
[PartNum] [nvarchar] (50) NULL,
[SellingShipQty] [decimal] (28, 8) NULL,
[UnitPrice] [decimal] (28, 8) NULL,
[UnitCost] [decimal] (28, 8) NULL,
[DiscountAmount] [decimal] (38, 8) NULL,
[TotalMiscChrg] [decimal] (38, 8) NULL,
[WarehouseCode] [nvarchar] (50) NULL,
[Indexkey] [varchar] (10) NULL,
[Site] [nvarchar] (50) NULL,
[OrderType] [nvarchar] (50) NULL
)
GO
