/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[FOR_PL_Supplier]
(
[PartitionKey] [varchar] (50) NULL,
[Company] [varchar] (20) NULL,
[SupplierNum] [nvarchar] (80) NULL,
[SupplierName] [nvarchar] (200) NULL,
[AddressLine1] [nvarchar] (200) NULL,
[TelephoneNum1] [nvarchar] (80) NULL,
[Email] [nvarchar] (80) NULL,
[ZipCode] [nvarchar] (80) NULL,
[City] [nvarchar] (80) NULL,
[State] [nvarchar] (80) NULL,
[CountryCode] [nvarchar] (80) NULL,
[SupplierGroup] [nvarchar] (80) NULL,
[SupplierResponsible] [nvarchar] (80) NULL,
[VATNum] [nvarchar] (80) NULL,
[IsAxInterInternal] [nvarchar] (80) NULL,
[CodeOfConduct] [nvarchar] (80) NULL,
[CreatedTimeStamp] [nvarchar] (80) NULL,
[ModifiedTimeStamp] [nvarchar] (80) NULL,
[IsActiveRecord] [nvarchar] (80) NULL,
[Website] [nvarchar] (80) NULL,
[SRes1] [nvarchar] (80) NULL
)
GO
