/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[FOR_SE_PurchaseLedger]
(
[PartitionKey] [nvarchar] (50) NOT NULL,
[Company] [nvarchar] (8) NOT NULL,
[SupplierCode] [nvarchar] (50) NOT NULL,
[PurchaseInvoiceNum] [nvarchar] (50) NOT NULL,
[PurchaseOrderNum] [nvarchar] (50) NULL,
[SupplierInvoiceNum] [nvarchar] (50) NULL,
[InvoiceDate] [date] NULL,
[DueDate] [date] NULL,
[LastPaymentDate] [date] NULL,
[FiscalYear] [nvarchar] (50) NULL,
[FiscalPeriod] [nvarchar] (50) NULL,
[InvoiceLCYAmount] [decimal] (18, 4) NOT NULL,
[InvoiceCurrAmount] [decimal] (18, 4) NULL,
[CurrencyCode] [nvarchar] (10) NULL,
[ExchangeRate] [decimal] (18, 4) NULL,
[VATPaid] [decimal] (18, 4) NULL,
[VATcode] [nvarchar] (10) NULL,
[VATCodeDesc] [nvarchar] (50) NULL,
[PayToName] [nvarchar] (50) NULL,
[PayToCity] [nvarchar] (50) NULL,
[PayToContact] [nvarchar] (50) NULL,
[PaymentTermsCode] [nvarchar] (50) NULL,
[PrepaymentNum] [nvarchar] (50) NULL,
[LastPaymentNum] [nvarchar] (50) NULL,
[OriginalAmount] [decimal] (18, 4) NULL,
[RemainingAmount] [decimal] (18, 4) NULL,
[PurchaseInvoiceDesc] [nvarchar] (50) NULL,
[AgingPeriod] [nvarchar] (50) NULL,
[DaysPastDue] [nvarchar] (50) NULL,
[LinktoOriginalInvoice] [nvarchar] (max) NULL,
[ApplyDate] [date] NULL,
[ChangeDate] [date] NULL,
[IsOpenPayable] [bit] NULL
)
GO
