/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[FOR_SE_CostBearer]
(
[PartitionKey] [varchar] (50) NOT NULL,
[Company] [nvarchar] (8) NULL,
[CostBearerNum] [nvarchar] (50) NULL,
[CostBearerName] [nvarchar] (100) NULL,
[CostBearerStatus] [nvarchar] (50) NULL,
[CostBearerGroup] [nvarchar] (50) NULL,
[CostBearerGroup2] [nvarchar] (50) NULL,
[CostBearerGroup3] [nvarchar] (50) NULL
)
GO
