/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[FOR_ES_Part]
(
[PartitionKey] [varchar] (50) NOT NULL,
[Company] [nvarchar] (8) NOT NULL,
[PartNum] [nvarchar] (100) NOT NULL,
[PartName] [nvarchar] (200) NULL,
[ProductGroup] [nvarchar] (50) NULL,
[ProductGroup2] [nvarchar] (50) NULL,
[NetWeight] [decimal] (22, 8) NULL,
[UoM] [nvarchar] (14) NULL,
[Material] [nvarchar] (200) NULL,
[Barcode] [nvarchar] (50) NULL,
[ReOrderLevel] [decimal] (22, 8) NULL
)
GO
