/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[FOR_SE_GeneralLedger]
(
[PartitionKey] [varchar] (50) NOT NULL,
[Company] [nvarchar] (8) NULL,
[AccountNum] [nvarchar] (50) NULL,
[CostUnitNum] [nvarchar] (50) NULL,
[CostBearerNum] [nvarchar] (50) NULL,
[JournalType] [nvarchar] (50) NULL,
[TransactionNum] [nvarchar] (50) NULL,
[APInvoiceNum] [nvarchar] (50) NULL,
[ARInvoiceNum] [nvarchar] (50) NULL,
[JournalNum] [nvarchar] (50) NULL,
[JournalLine] [nvarchar] (50) NULL,
[Description] [nvarchar] (500) NULL,
[Currency] [nvarchar] (50) NULL,
[FiscalYear] [nvarchar] (50) NULL,
[FiscalPeriod] [nvarchar] (50) NULL,
[AmountSystemCurrency] [decimal] (18, 4) NULL,
[CustomerNum] [nvarchar] (50) NULL,
[SupplierNum] [nvarchar] (50) NULL,
[SupplierInvoiceNum] [nvarchar] (50) NULL,
[JournalDate] [date] NULL,
[AccountingDate] [date] NULL,
[VATCode] [nvarchar] (50) NULL,
[VATCodeDesc] [nvarchar] (max) NULL,
[LinktoOriginalInvoice] [nvarchar] (500) NULL,
[SysRowID] [nvarchar] (50) NULL,
[UserIDBooked] [nvarchar] (50) NULL,
[UserIDApproved] [nvarchar] (50) NULL
)
GO
