/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[FOR_PL_StockBalance]
(
[PartitionKey] [varchar] (50) NULL,
[Company] [varchar] (20) NULL,
[WarehouseCode] [nvarchar] (15) NULL,
[PartNum] [nvarchar] (40) NULL,
[LastStockTakeDate] [nvarchar] (50) NULL,
[MaxStockQty] [nvarchar] (25) NULL,
[StockBalance] [nvarchar] (25) NULL,
[StockValue] [nvarchar] (40) NULL,
[Currency] [nvarchar] (20) NULL,
[SalesRemainingQty] [nvarchar] (30) NULL,
[PurchaseRemainingqty] [nvarchar] (30) NULL,
[ReOrderLevel] [nvarchar] (30) NULL,
[SafetyStock] [nvarchar] (30) NULL,
[AvgCost] [nvarchar] (50) NULL,
[CreatedTimeStamp] [nvarchar] (50) NULL,
[ModifiedTimeStamp] [nvarchar] (50) NULL
)
GO
