/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[FOR_SE_Budget]
(
[Company] [nvarchar] (50) NULL,
[AccountNum] [nvarchar] (50) NULL,
[AccountGroup] [nvarchar] (50) NULL,
[CostUnitNum] [nvarchar] (50) NULL,
[CostBearerNum] [nvarchar] (50) NULL,
[Year] [nvarchar] (50) NULL,
[PeriodType] [nvarchar] (50) NULL,
[BudgetFinance] [nvarchar] (50) NULL,
[Currency] [nvarchar] (50) NULL,
[ExchangeRate] [nvarchar] (50) NULL,
[BudgetType] [nvarchar] (50) NULL,
[BudgetName] [nvarchar] (50) NULL,
[BudgetDescription] [nvarchar] (50) NULL,
[CreatedTimeStamp] [nvarchar] (50) NULL,
[ModifiedTimeStamp] [nvarchar] (50) NULL,
[IsRecordActive] [nvarchar] (50) NULL
)
GO
