/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[FOR_PL_SOLine]
(
[PartitionKey] [varchar] (50) NOT NULL,
[Company] [nvarchar] (50) NOT NULL,
[InvoiceHandler] [nvarchar] (200) NULL,
[Seller] [nvarchar] (200) NULL,
[CustomerCode] [nvarchar] (50) NULL,
[CustomerName] [nvarchar] (100) NULL,
[PartNum] [nvarchar] (50) NULL,
[PartType] [nvarchar] (50) NULL,
[SalesOrderNumber] [nvarchar] (50) NULL,
[SalesOrderEntry] [nvarchar] (50) NULL,
[SalesOrderLine] [nvarchar] (50) NULL,
[SalesOrderObjectType] [nvarchar] (50) NULL,
[DeliveryNoteType] [nvarchar] (50) NULL,
[DeliveryNoteEntry] [nvarchar] (50) NULL,
[DeliveryNoteLine] [nvarchar] (50) NULL,
[DeliveryNoteDate] [date] NULL,
[SalesInvoiceBase] [nvarchar] (50) NULL,
[SalesInvoiceBaseTYPE] [nvarchar] (50) NULL,
[SalesInvoiceNum] [nvarchar] (50) NOT NULL,
[SalesInvoiceLine] [nvarchar] (50) NULL,
[SalesInvoiceType] [nvarchar] (50) NULL,
[SalesInvoiceDate] [date] NOT NULL,
[SalesInvoiceLineDate] [date] NULL,
[ActualDelivDate] [date] NULL,
[SalesInvoiceQty] [nvarchar] (50) NULL,
[UoM] [nvarchar] (50) NULL,
[UnitPrice] [decimal] (18, 4) NULL,
[UnitDiscount] [decimal] (18, 4) NULL,
[UnitPriceFinal] [decimal] (18, 4) NULL,
[UnitCost] [decimal] (18, 4) NULL,
[DiscountPercent] [decimal] (18, 4) NULL,
[DiscountAmount] [decimal] (18, 4) NULL,
[VATAmount] [decimal] (18, 4) NULL,
[DocumentCurrency] [nvarchar] (50) NULL,
[DocumentExchangeRate] [decimal] (18, 4) NULL,
[CreditMemo] [nvarchar] (50) NULL,
[Warehouse] [nvarchar] (50) NULL,
[ReturnComment] [nvarchar] (50) NULL,
[SalesInvoiceStatus] [nvarchar] (50) NULL,
[IsCreditInvoice] [nvarchar] (50) NULL,
[Is/ToVerify] [nvarchar] (50) NULL,
[ObjType] [int] NULL,
[AccountCode] [nvarchar] (50) NULL,
[VATCode] [nvarchar] (50) NULL
)
GO
