/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[FOR_PL_PurchaseInvoice]
(
[PartitionKey] [varchar] (50) NULL,
[Company] [varchar] (20) NULL,
[PIRes1] [nvarchar] (40) NULL,
[PurchaseInvoiceNum] [nvarchar] (80) NULL,
[PurchaseInvoiceLine] [nvarchar] (80) NULL,
[PurchaseOrderNum] [nvarchar] (80) NULL,
[PurchaseOrderLine] [nvarchar] (80) NULL,
[PurchaseInvoiceType] [nvarchar] (80) NULL,
[PurchaseInvoiceDate] [nvarchar] (80) NULL,
[ActualShipDate] [nvarchar] (80) NULL,
[ActualRecieveDate] [nvarchar] (80) NULL,
[IsInvoiceClosed] [nvarchar] (80) NULL,
[SupplierNum] [nvarchar] (80) NULL,
[PartNum] [nvarchar] (80) NULL,
[PurchaseInvoiceQty] [nvarchar] (80) NULL,
[UoM] [nvarchar] (80) NULL,
[UnitPrice] [nvarchar] (80) NULL,
[DiscountPercent] [nvarchar] (80) NULL,
[DiscountAmount] [nvarchar] (80) NULL,
[TotalMiscChrg] [nvarchar] (80) NULL,
[ExchangeRate] [nvarchar] (80) NULL,
[Currency] [nvarchar] (80) NULL,
[IsCreditMemo] [nvarchar] (80) NULL,
[PurchaserName] [nvarchar] (80) NULL,
[WarehouseCode] [nvarchar] (80) NULL,
[Comment] [nvarchar] (300) NULL,
[CreatedTimeStamp] [varchar] (50) NULL,
[ModifiedTimeStamp] [varchar] (50) NULL,
[PurchaseOrderSubLine] [nvarchar] (25) NULL
)
GO
