/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[FOR_PL_mapProductGroup]
(
[Cat 2] [nvarchar] (255) NULL,
[Cat 1 symb] [nvarchar] (255) NULL,
[Cat 2 symb] [nvarchar] (255) NULL,
[grupa2] [nvarchar] (255) NULL
)
GO
