/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[FOR_SE_Supplier]
(
[PartitionKey] [varchar] (50) NOT NULL,
[Company] [nvarchar] (8) NOT NULL,
[SupplierNum] [nvarchar] (50) NOT NULL,
[SupplierName] [nvarchar] (100) NULL,
[Addressline1] [nvarchar] (100) NULL,
[Addressline2] [nvarchar] (100) NULL,
[Addressline3] [nvarchar] (100) NULL,
[City] [nvarchar] (50) NULL,
[ZIP] [nvarchar] (50) NULL,
[Region] [nvarchar] (50) NULL,
[CountryCode] [nvarchar] (50) NULL,
[CountryName] [nvarchar] (100) NULL,
[SupplierCategory] [nvarchar] (50) NULL,
[Reference] [nvarchar] (100) NULL,
[BankAccountNum] [nvarchar] (50) NULL,
[VATNum] [nvarchar] (50) NULL,
[TelephoneNum] [nvarchar] (20) NULL,
[Email] [nvarchar] (100) NULL,
[Website] [nvarchar] (100) NULL,
[CodeOfConduct] [nvarchar] (2) NULL,
[MinOrderQty] [decimal] (18, 4) NULL,
[Comment] [nvarchar] (max) NULL,
[InternalExternal] [nvarchar] (100) NULL,
[SupplierABC] [nvarchar] (50) NULL,
[CustomerCode] [nvarchar] (50) NULL,
[Buyer] [nvarchar] (100) NULL,
[OrganisationNum] [nvarchar] (50) NULL
)
GO
