/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[FOR_FR_Quotation]
(
[PartitionKey] [nvarchar] (50) NOT NULL,
[Company] [nvarchar] (8) NOT NULL,
[CustomerNum] [nvarchar] (50) NULL,
[QuotationNum] [nvarchar] (50) NULL,
[QuotationLine] [nvarchar] (50) NULL,
[LogIndex] [nvarchar] (50) NULL,
[LogDate] [nvarchar] (50) NULL,
[LogTme] [nvarchar] (50) NULL,
[ProspectNum] [nvarchar] (50) NULL,
[ProspectName] [nvarchar] (50) NULL,
[QuotationDescription] [nvarchar] (500) NULL,
[QuotationType] [nvarchar] (50) NULL,
[QuotationStatus] [nvarchar] (50) NULL,
[QuotationInitiator] [nvarchar] (50) NULL,
[QuotationChannel] [nvarchar] (50) NULL,
[RelationalStatus] [nvarchar] (50) NULL,
[CustomerReference] [nvarchar] (50) NULL,
[PartNum] [nvarchar] (50) NULL,
[Quantity] [nvarchar] (50) NULL,
[UnitPrice] [nvarchar] (50) NULL,
[DiscountPercent] [nvarchar] (50) NULL,
[DiscountAmount] [nvarchar] (50) NULL,
[QuotationHandler] [nvarchar] (50) NULL,
[QuotationResponsible] [nvarchar] (50) NULL,
[QuotationDate] [nvarchar] (50) NULL,
[StartDate] [nvarchar] (50) NULL,
[EndDate] [nvarchar] (50) NULL,
[QRes1] [nvarchar] (50) NULL,
[QRes2] [nvarchar] (50) NULL,
[QRes3] [nvarchar] (50) NULL
)
GO
