/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[Jen_SE_StockTransactionOB20200101]
(
[Artikelnummer] [nvarchar] (255) NULL,
[Saldo] [decimal] (18, 4) NULL,
[Lagervärde] [decimal] (18, 4) NULL,
[Belopp] [decimal] (18, 4) NULL
)
GO
