/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[JEN_DK_Supplier]
(
[PartitionKey] [varchar] (50) NOT NULL,
[Company] [nvarchar] (8) NOT NULL,
[SupplierNum] [nvarchar] (50) NOT NULL,
[Name] [nvarchar] (100) NULL,
[CustomerCode] [nvarchar] (50) NULL,
[Addressline1] [nvarchar] (50) NULL,
[Addressline2] [nvarchar] (50) NULL,
[Addressline3] [nvarchar] (50) NULL,
[City] [nvarchar] (50) NULL,
[ZIP] [nvarchar] (50) NULL,
[CountryName] [nvarchar] (50) NULL,
[Region] [nvarchar] (50) NULL,
[SupplierCategory] [nvarchar] (50) NULL,
[Reference] [nvarchar] (50) NULL,
[BankAccountNum] [nvarchar] (50) NULL,
[VATNum] [nvarchar] (50) NULL,
[ABCCode] [nvarchar] (50) NULL,
[TelephoneNum] [nvarchar] (50) NULL,
[Email] [nvarchar] (100) NULL,
[CodeOfConduct] [nvarchar] (500) NULL,
[MinOrderQty] [nvarchar] (50) NULL,
[InternalName] [nvarchar] (100) NULL,
[CountryCode] [nvarchar] (10) NULL
)
GO
