/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[JEN_SE_StockTransaction]
(
[PartitionKey] [nvarchar] (50) NOT NULL,
[Company] [nvarchar] (50) NOT NULL,
[SysRowID] [nvarchar] (50) NOT NULL,
[PartNum] [nvarchar] (50) NULL,
[OrderNum] [nvarchar] (50) NULL,
[InvoiceNum] [nvarchar] (50) NULL,
[WarehouseCode] [nvarchar] (50) NULL,
[BinNumber] [nvarchar] (50) NULL,
[BatchID] [nvarchar] (50) NULL,
[FIFOBatchID] [nvarchar] (50) NULL,
[SupplierBatchID] [nvarchar] (50) NULL,
[TranDate] [date] NULL,
[CreateDate] [date] NULL,
[CreateTime] [nvarchar] (50) NULL,
[TranDT] [nvarchar] (50) NULL,
[TranType] [nvarchar] (50) NULL,
[TranTypeDesc] [nvarchar] (200) NULL,
[TranSource] [nvarchar] (50) NULL,
[Reference] [nvarchar] (30) NULL,
[TranQty] [decimal] (18, 4) NULL,
[PartStatus] [nvarchar] (50) NULL,
[IssuerReceiverCode] [nvarchar] (50) NULL,
[CostPrice] [decimal] (18, 4) NULL,
[SellingPrice] [decimal] (18, 4) NULL,
[CurrencyCode] [nvarchar] (50) NULL,
[ExchangeRate] [decimal] (18, 4) NULL,
[TranValue] [decimal] (18, 4) NULL
)
GO
