/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[Jen_NO_StocktransactionOB]
(
[StockTransactionID] [binary] (32) NOT NULL,
[Company] [nvarchar] (8) NOT NULL,
[WarehouseCode] [nvarchar] (50) NULL,
[TransactionCode] [nvarchar] (50) NULL,
[TransactionDescription] [nvarchar] (max) NULL,
[IssuerReceiverNum] [nvarchar] (50) NULL,
[OrderNum] [nvarchar] (50) NULL,
[OrderLine] [nvarchar] (50) NULL,
[InvoiceNum] [nvarchar] (50) NULL,
[InvoiceLine] [nvarchar] (50) NULL,
[PartNum] [nvarchar] (50) NOT NULL,
[BinNum] [nvarchar] (50) NULL,
[BatchNum] [nvarchar] (50) NULL,
[TransactionDate] [date] NULL,
[TransactionTime] [nvarchar] (10) NULL,
[TransactionQty] [decimal] (18, 4) NULL,
[TransactionValue] [decimal] (18, 4) NULL,
[CostPrice] [decimal] (18, 4) NULL,
[SalesUnitPrice] [decimal] (18, 4) NULL,
[Currency] [nvarchar] (10) NULL,
[Reference] [nvarchar] (50) NULL,
[AdjustmentDate] [date] NULL,
[STRes1] [nvarchar] (100) NULL,
[STRes2] [nvarchar] (100) NULL,
[STRes3] [nvarchar] (100) NULL,
[CompanyID] [binary] (32) NULL,
[PartID] [binary] (32) NULL,
[WarehouseID] [binary] (32) NULL,
[PurchaseInvoiceID] [binary] (32) NULL,
[PurchaseOrderNumID] [binary] (32) NULL,
[SalesOrderNumID] [binary] (32) NULL,
[SalesInvoiceID] [binary] (32) NULL,
[CustomerID] [binary] (32) NULL,
[SupplierID] [binary] (32) NULL,
[CurrencyID] [binary] (32) NULL,
[PartitionKey] [nvarchar] (50) NOT NULL,
[IndexKey] [nvarchar] (50) NULL,
[InternalExternal] [nvarchar] (50) NULL
)
GO
