/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[MAK_NL_SOLine]
(
[PartitionKey] [varchar] (50) NOT NULL,
[Company] [nvarchar] (8) NOT NULL,
[SalesInvoiceNum] [nvarchar] (50) NULL,
[SalesInvoiceDate] [date] NULL,
[SalesPersonName] [nvarchar] (100) NULL,
[CustomerNum] [nvarchar] (50) NULL,
[CustomerGroup] [nvarchar] (50) NULL,
[PartNum] [nvarchar] (50) NULL,
[MainItem] [nvarchar] (50) NULL,
[Mainitem2] [nvarchar] (50) NULL,
[SalesOrderNum] [nvarchar] (50) NULL,
[SalesOrderLine] [nvarchar] (50) NULL,
[SalesOrderType] [nvarchar] (50) NULL,
[SalesInvoiceType] [nvarchar] (50) NULL,
[SalesInvoiceQty] [decimal] (18, 4) NULL,
[UoM] [nvarchar] (50) NULL,
[UnitPrice] [decimal] (18, 4) NULL,
[UnitCost] [decimal] (18, 4) NULL,
[TotalMiscChrg] [decimal] (18, 4) NULL,
[VATAmount] [decimal] (18, 4) NULL,
[Currency] [nvarchar] (50) NULL,
[ProjectNum] [nvarchar] (50) NULL,
[WarehouseCode] [nvarchar] (50) NULL,
[ActualDelivDate] [date] NULL,
[InvoiceLine] [nvarchar] (50) NULL,
[ExchangeRate] [decimal] (18, 4) NULL,
[DiscountAmount] [decimal] (18, 4) NULL,
[IndexKey] [int] NULL,
[testNetLineAmount] [decimal] (18, 4) NULL,
[testCostLineAmount] [nvarchar] (50) NULL
)
GO
