/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[MAK_NL_Budget]
(
[PartitionKey] [nvarchar] (60) NULL,
[Company] [nvarchar] (60) NULL,
[BudgetPeriodDate] [nvarchar] (60) NULL,
[PeriodType] [nvarchar] (60) NULL,
[BudgetSales] [nvarchar] (60) NULL,
[BudgetCost] [nvarchar] (60) NULL,
[GrossProfitInvoiced] [nvarchar] (60) NULL,
[GrossMarginInvoicedPercent] [nvarchar] (60) NULL,
[Currency] [nvarchar] (60) NULL
)
GO
