/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[MatchComponents]
(
[customerReference] [nvarchar] (60) NOT NULL,
[matchCandidates.matchQualityInformation.matchGradeComponents.componentType] [nvarchar] (20) NULL,
[matchCandidates.matchQualityInformation.matchGradeComponents.componentRating] [nvarchar] (40) NULL
)
GO
