/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[MEN_NL_StockBalance]
(
[PartitionKey] [varchar] (50) NOT NULL,
[Company] [nvarchar] (50) NOT NULL,
[PartNum] [nvarchar] (50) NULL,
[WareHouseCode] [nvarchar] (50) NULL,
[LotNum] [nvarchar] (50) NULL,
[TranDate] [date] NULL,
[QtyDec12.5] [nvarchar] (50) NULL,
[QtyFloat] [float] NULL,
[ProductKey] [nvarchar] (50) NOT NULL,
[DW_TimeStamp] [date] NULL
)
GO
