/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[MEN_NL_Budget]
(
[PartitionKey] [nvarchar] (20) NULL,
[Company] [nvarchar] (12) NULL,
[AccountNum] [nvarchar] (80) NULL,
[BudgetPeriod] [nvarchar] (80) NULL,
[BudgetPeriodDate] [nvarchar] (80) NULL,
[PeriodType] [nvarchar] (80) NULL,
[CustomerNum] [nvarchar] (80) NULL,
[ProjectNum] [nvarchar] (80) NULL,
[CustomerGroup] [nvarchar] (80) NULL,
[ProductGroup] [nvarchar] (80) NULL,
[SalesPersonCode] [nvarchar] (80) NULL,
[SalesPersonName] [nvarchar] (80) NULL,
[BudgetDescription] [nvarchar] (80) NULL,
[Currency] [nvarchar] (80) NULL,
[ExchangeRate] [nvarchar] (80) NULL,
[BudgetSales] [nvarchar] (80) NULL,
[BudgetCost] [nvarchar] (80) NULL,
[BudgetGrossProfit] [nvarchar] (80) NULL,
[BudgetGrossMargin] [nvarchar] (80) NULL,
[BudgetType] [nvarchar] (80) NULL,
[Department] [nvarchar] (80) NULL,
[Bres3] [nvarchar] (80) NULL
)
GO
