/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[MEN_NL_OLine]
(
[PartitionKey] [varchar] (50) NOT NULL,
[Company] [nvarchar] (50) NOT NULL,
[CustomerNum] [nvarchar] (50) NULL,
[SalesOrderNum] [nvarchar] (50) NOT NULL,
[SalesOrderLine] [nvarchar] (50) NULL,
[SalesOrderSubLine] [nvarchar] (50) NULL,
[SalesOrderType] [nvarchar] (50) NULL,
[SalesOrderCategory] [nvarchar] (100) NULL,
[SalesOrderStatus] [nvarchar] (50) NULL,
[SalesOrderDate] [date] NULL,
[NeedbyDate] [date] NULL,
[ExpDelivDate] [date] NULL,
[ActualDelivDate] [date] NULL,
[SalesInvoiceNum] [nvarchar] (50) NULL,
[SalesOrderQty] [decimal] (18, 8) NULL,
[DelivQty] [decimal] (18, 8) NULL,
[RemainingQTY] [decimal] (18, 8) NULL,
[UoM] [nvarchar] (50) NULL,
[UnitPrice] [decimal] (18, 8) NULL,
[UnitCost] [decimal] (18, 8) NULL,
[Currency] [nvarchar] (50) NULL,
[ExchangeRate] [decimal] (18, 8) NULL,
[DiscountPercent] [decimal] (18, 8) NULL,
[DiscountAmount] [decimal] (18, 8) NULL,
[PartNum] [nvarchar] (50) NULL,
[PartType] [nvarchar] (50) NULL,
[PartStatus] [nvarchar] (50) NULL,
[SalesPersonName] [nvarchar] (50) NULL,
[WarehouseCode] [nvarchar] (50) NULL,
[SalesChanel] [nvarchar] (50) NULL,
[Department] [nvarchar] (100) NULL,
[ProjectNum] [nvarchar] (50) NULL,
[Cancellation] [nvarchar] (50) NULL,
[IndexKey] [nvarchar] (50) NULL,
[SORes1] [nvarchar] (50) NULL,
[SORes2] [nvarchar] (50) NULL,
[SORes3] [nvarchar] (50) NULL,
[DebiteurKey] [nvarchar] (50) NULL,
[ProductKey] [nvarchar] (50) NULL,
[DW_TimeStamp] [date] NULL,
[SalesAmount] [decimal] (18, 8) NULL,
[CustomerNumPayer] [nvarchar] (50) NULL,
[SalesOrderQty_2] [decimal] (18, 8) NULL,
[InternalSalesIdentifier] [bit] NULL
)
GO
