/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[MEN_NL_Part]
(
[PartitionKey] [varchar] (50) NOT NULL,
[Company] [nvarchar] (50) NOT NULL,
[PartNum] [nvarchar] (50) NOT NULL,
[PartDescription] [nvarchar] (300) NULL,
[PartDescription2] [nvarchar] (300) NULL,
[PartDescription3] [nvarchar] (300) NULL,
[ProductGroup] [nvarchar] (100) NULL,
[ProductGroup2] [nvarchar] (100) NULL,
[ProductGroup3] [nvarchar] (100) NULL,
[ProductGroup4] [nvarchar] (100) NULL,
[Brand] [nvarchar] (100) NULL,
[CommodityCode] [nvarchar] (50) NULL,
[PartReplacementNum] [nvarchar] (50) NULL,
[PartStatus] [nvarchar] (50) NULL,
[CountryOfOrigin] [nvarchar] (100) NULL,
[NetWeight] [decimal] (18, 8) NULL,
[UoM] [nvarchar] (50) NULL,
[Material] [nvarchar] (50) NULL,
[Barcode] [nvarchar] (50) NULL,
[ReorderLevel] [decimal] (18, 8) NULL,
[PartResponsible] [nvarchar] (50) NULL,
[MainSupplier] [nvarchar] (100) NULL,
[AlternativeSupplier] [nvarchar] (50) NULL,
[StartDate] [date] NULL,
[EndDate] [date] NULL,
[PARes1] [nvarchar] (50) NULL,
[PARes2] [nvarchar] (50) NULL,
[PARes3] [nvarchar] (50) NULL,
[ProductKey] [nvarchar] (50) NULL,
[DW_TimeStamp] [date] NULL,
[ProductCOOCode] [nvarchar] (50) NULL,
[ProductIsAssembly] [bit] NULL
)
GO
