/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[MEN_NL_Supplier]
(
[PartitionKey] [varchar] (50) NOT NULL,
[Company] [nvarchar] (50) NOT NULL,
[SupplierCode] [nvarchar] (50) NOT NULL,
[Name] [nvarchar] (50) NULL,
[Adress] [nvarchar] (200) NULL,
[PostalCode] [nvarchar] (50) NULL,
[City] [nvarchar] (200) NULL,
[Country] [nvarchar] (100) NULL,
[Telephone] [nvarchar] (50) NULL,
[VatNumber] [nvarchar] (50) NULL,
[CurrencyCode] [nvarchar] (50) NULL,
[Created] [date] NULL,
[Changed] [date] NULL,
[CrediteurKey] [nvarchar] (50) NULL,
[DW_TimeStamp] [date] NULL,
[IsAxInterInternal] [nvarchar] (50) NULL,
[OrganizationNum] [nvarchar] (80) NULL,
[IsMaterialSupplier] [nvarchar] (10) NULL
)
GO
