/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[MEN_NL_PurchaseInvoice]
(
[PartitionKey] [varchar] (50) NOT NULL,
[Company] [nvarchar] (50) NOT NULL,
[ID] [nvarchar] (50) NULL,
[Period] [nvarchar] (50) NULL,
[SysDate] [date] NULL,
[SysTime] [time] NULL,
[SupplierCode] [nvarchar] (50) NULL,
[InvoiceNumber] [nvarchar] (50) NOT NULL,
[InvoiceLine] [nvarchar] (50) NULL,
[InvoiceDate] [date] NULL,
[PurchaseOrderNumber] [nvarchar] (50) NULL,
[PurchaseOrderLine] [nvarchar] (50) NULL,
[PartNum] [nvarchar] (50) NULL,
[Quantity] [decimal] (18, 8) NULL,
[CurrencyCode] [nvarchar] (50) NULL,
[Price] [decimal] (18, 8) NULL,
[Amount] [decimal] (18, 8) NULL,
[CrediteurKey] [nvarchar] (50) NULL,
[ProductKey] [nvarchar] (50) NULL,
[DW_TimeStamp] [date] NULL
)
GO
