/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[MEN_NL_countrycode_map]
(
[PartitionKey] [varchar] (50) NULL,
[CountryCode] [nvarchar] (50) NULL,
[CountryDescription] [nvarchar] (50) NULL,
[EGInternal] [nvarchar] (50) NULL,
[CBSCountryCode] [nvarchar] (50) NULL,
[ISOCountryCode] [nvarchar] (50) NULL,
[CBSCountryCodeInt] [nvarchar] (50) NULL,
[CBSCountryDescription] [nvarchar] (200) NULL,
[CBSCountryAbbreviation] [nvarchar] (50) NULL
)
GO
