/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[NOM_Budget]
(
[Company] [nvarchar] (50) NOT NULL,
[Period] [nvarchar] (50) NOT NULL,
[CustomerNum] [nvarchar] (50) NULL,
[CustomerGroup] [nvarchar] (50) NULL,
[SalesRepCode] [nvarchar] (50) NULL,
[ProductGroup2] [nvarchar] (50) NULL,
[Sales] [decimal] (18, 10) NULL,
[Cost] [decimal] (18, 10) NULL
)
GO
