/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[Nom_All_PartBudget]
(
[﻿Company] [nvarchar] (50) NULL,
[PartNum] [nvarchar] (50) NULL,
[PartDescription] [nvarchar] (50) NULL,
[PartDescription2] [nvarchar] (50) NULL,
[PartDescription3] [nvarchar] (50) NULL,
[ProductGroup] [nvarchar] (50) NULL,
[ProductGroup2] [nvarchar] (50) NULL,
[ProductGroup3] [nvarchar] (50) NULL,
[ProductGroup4] [nvarchar] (50) NULL,
[CommodityCode] [nvarchar] (50) NULL,
[CountryOfOrigin] [nvarchar] (50) NULL,
[NetWeight] [nvarchar] (50) NULL,
[PartResponsible] [nvarchar] (50) NULL,
[ParentSupplier] [nvarchar] (50) NULL,
[ReorderLevel] [nvarchar] (50) NULL,
[DiscountGroup] [nvarchar] (50) NULL
)
GO
