/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[NOM_RLS]
(
[EmailID] [nvarchar] (200) NULL,
[Company] [nvarchar] (50) NULL,
[Name] [nvarchar] (200) NULL,
[Email] [nvarchar] (200) NULL
)
GO
