/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[NOM_SE_Part]
(
[PartitionKey] [varchar] (50) NOT NULL,
[Company] [nvarchar] (8) NOT NULL,
[PartNum] [nvarchar] (50) NOT NULL,
[PartDescription] [nvarchar] (max) NULL,
[PartDescription2] [nvarchar] (max) NULL,
[ProductGroup] [nvarchar] (100) NULL,
[ProductGroup2] [nvarchar] (100) NULL,
[ProductGroup3] [nvarchar] (100) NULL,
[ProductGroup4] [nvarchar] (100) NULL,
[CommodityCode] [nvarchar] (50) NULL,
[CountryOfOrigin] [nvarchar] (50) NULL,
[PartResponsible] [nvarchar] (50) NULL,
[NetWeight] [decimal] (18, 8) NULL,
[SupplierCode] [nvarchar] (50) NULL,
[ParentSupplier] [nvarchar] (50) NULL,
[ReorderLevel] [decimal] (18, 8) NULL,
[DiscountGroup] [nvarchar] (50) NULL
)
GO
