/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[OCS_SE_Account]
(
[PartitionKey] [nvarchar] (50) NULL,
[Company] [nvarchar] (50) NULL,
[AccountNum] [nvarchar] (50) NULL,
[AccountName] [nvarchar] (200) NULL,
[AccountGroupNum] [nvarchar] (50) NULL,
[AccountGroup] [nvarchar] (50) NULL,
[Statement] [nvarchar] (50) NULL,
[StatementNum] [nvarchar] (50) NULL,
[AccountType2Num] [nvarchar] (50) NULL,
[AccountType2] [nvarchar] (50) NULL,
[AccountIsActive] [nvarchar] (50) NULL,
[AccountIsBalanceAccount] [nvarchar] (50) NULL,
[Revenue] [nvarchar] (50) NULL,
[Costs] [nvarchar] (50) NULL,
[CreatedTimeStamp] [nvarchar] (50) NULL,
[ModifiedTimeStamp] [nvarchar] (50) NULL
)
GO
