/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[OCS_SE_SalesLedger]
(
[PartitionKey] [varchar] (50) NOT NULL,
[Company] [nvarchar] (8) NULL,
[CustomerNum] [nvarchar] (50) NULL,
[SalesOrderNum] [nvarchar] (50) NULL,
[SalesInvoiceNum] [nvarchar] (50) NULL,
[InvoiceAmount] [decimal] (18, 8) NULL,
[InvoiceAmountSEK] [nvarchar] (50) NULL,
[PaidInvoiceAmount] [decimal] (18, 8) NULL,
[PaidInvoiceAmountSEK] [nvarchar] (50) NULL,
[RemainingInvoiceAmountSEK] [nvarchar] (50) NULL,
[RemainingInvoiceAmount] [decimal] (18, 8) NULL,
[AccountingDate] [nvarchar] (50) NULL,
[SalesInvoiceDate] [nvarchar] (50) NULL,
[SalesInvoiceDueDate] [nvarchar] (50) NULL,
[SalesInvoiceLastPaymentDate] [nvarchar] (50) NULL,
[IsInvoiceClosed] [nvarchar] (8) NULL,
[Currency] [nvarchar] (50) NULL,
[ExchangeRate] [nvarchar] (50) NULL,
[VATAmount] [decimal] (18, 8) NULL,
[VATCode] [nvarchar] (50) NULL,
[VATCodeDesc] [nvarchar] (50) NULL,
[PaymentEvents] [nvarchar] (50) NULL,
[ProjectNum] [nvarchar] (50) NULL,
[CreatedTimeStamp] [nvarchar] (50) NULL,
[ModifiedTimeStamp] [nvarchar] (50) NULL,
[LinktoOriginalInvoice] [nvarchar] (50) NULL
)
GO
