/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[OCS_SE_StockBalance]
(
[PartitionKey] [nvarchar] (50) NOT NULL,
[Company] [nvarchar] (50) NOT NULL,
[WarehousCode] [nvarchar] (50) NOT NULL,
[BinNum] [nvarchar] (50) NULL,
[SupplierNum] [nvarchar] (50) NULL,
[PartNum] [nvarchar] (50) NULL,
[DelivTime] [nvarchar] (50) NULL,
[LastStockTakeDate] [nvarchar] (50) NULL,
[StockTakeDiff] [nvarchar] (50) NULL,
[LastStdCostCalDate] [nvarchar] (50) NULL,
[MaxStockQty] [nvarchar] (50) NULL,
[StockBalance] [nvarchar] (50) NULL,
[StockValue] [nvarchar] (50) NULL,
[SalesRemainingQty] [nvarchar] (50) NULL,
[PurchaseRemainingQty] [nvarchar] (50) NULL,
[ProductionRemainingQty] [nvarchar] (50) NULL,
[ForProductionRemainingQty] [nvarchar] (50) NULL,
[ReOrderLevel] [nvarchar] (50) NULL,
[SafetyStock] [nvarchar] (50) NULL,
[OptimalOrderQty] [nvarchar] (50) NULL,
[AvgCost] [nvarchar] (50) NULL,
[CreatedTimeStamp] [nvarchar] (50) NULL,
[ModifiedTimeStamp] [nvarchar] (50) NULL,
[PhysicalStockBalance] [nvarchar] (50) NULL,
[PhysicalStockValue] [nvarchar] (50) NULL,
[AvailableStock] [nvarchar] (50) NULL
)
GO
