/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[OCS_SE_GeneralLedgerTimeCost]
(
[Projekt] [nvarchar] (50) NULL,
[Konto] [nvarchar] (50) NULL,
[Timmar] [nvarchar] (50) NULL,
[Belopp] [nvarchar] (50) NULL
)
GO
