/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[PAS_PL_Customer]
(
[PartitionKey] [varchar] (50) NOT NULL,
[company] [nvarchar] (8) NOT NULL,
[customernum] [nvarchar] (50) NOT NULL,
[maincustomername] [nvarchar] (300) NULL,
[customername] [nvarchar] (300) NULL,
[addressline1] [nvarchar] (50) NULL,
[addressline2] [nvarchar] (50) NULL,
[addressline3] [nvarchar] (50) NULL,
[telephonenum1] [nvarchar] (50) NULL,
[telephonenum2] [nvarchar] (50) NULL,
[email] [nvarchar] (100) NULL,
[customerabc] [nvarchar] (50) NULL,
[city] [nvarchar] (50) NULL,
[zipcode] [nvarchar] (50) NULL,
[state] [nvarchar] (50) NULL,
[countrycode] [nvarchar] (50) NULL,
[countryname] [nvarchar] (50) NULL,
[division] [nvarchar] (50) NULL,
[customergroup] [nvarchar] (50) NULL,
[customersubgroup] [nvarchar] (50) NULL,
[salesrepcode] [nvarchar] (50) NULL,
[vatregnr] [nvarchar] (50) NULL,
[accountstring] [nvarchar] (50) NULL,
[district] [nvarchar] (50) NULL,
[internalexternal] [nvarchar] (50) NULL,
[salespersonresponsible] [nvarchar] (50) NULL,
[salespersonname] [nvarchar] (100) NULL,
[customertype] [nvarchar] (50) NULL,
[customercode] [nvarchar] (50) NULL,
[res1] [nvarchar] (50) NULL,
[res2] [nvarchar] (50) NULL,
[res3] [nvarchar] (50) NULL
)
GO
