/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[PAS_PL_SOLine]
(
[PartitionKey] [varchar] (50) NOT NULL,
[company] [nvarchar] (8) NOT NULL,
[idpozycji] [nvarchar] (50) NULL,
[salesperson] [nvarchar] (150) NULL,
[custnum] [nvarchar] (50) NULL,
[partnum] [nvarchar] (50) NULL,
[ordernum] [nvarchar] (50) NULL,
[orderline] [nvarchar] (50) NULL,
[ordersubline] [nvarchar] (50) NULL,
[orderrelnum] [nvarchar] (50) NULL,
[ordertype] [nvarchar] (50) NULL,
[invoicenum] [nvarchar] (50) NULL,
[invoiceline] [nvarchar] (50) NULL,
[invoicetype] [nvarchar] (50) NULL,
[invoicedate] [date] NULL,
[actualdeliverydate] [nvarchar] (50) NULL,
[sellingshipqty] [decimal] (18, 4) NULL,
[unitprice] [decimal] (18, 4) NULL,
[unitcost] [decimal] (18, 4) NULL,
[discountamount] [decimal] (18, 4) NULL,
[totalmiscchrg] [decimal] (18, 4) NULL,
[site] [nvarchar] (50) NULL,
[creditmemo] [nvarchar] (100) NULL,
[indexkey] [nvarchar] (50) NULL,
[warehouseid] [nvarchar] (50) NULL,
[res1] [nvarchar] (100) NULL,
[res2] [nvarchar] (100) NULL,
[res3] [nvarchar] (100) NULL,
[vat] [nvarchar] (50) NULL,
[currency] [nvarchar] (50) NULL,
[exchangerate] [decimal] (18, 4) NULL
)
GO
