/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[PAS_PL_Warehouse]
(
[PartitionKey] [varchar] (50) NOT NULL,
[company] [nvarchar] (8) NOT NULL,
[warehouseid] [nvarchar] (50) NULL,
[warehousecode] [nvarchar] (50) NOT NULL,
[warehousename] [nvarchar] (100) NULL,
[warehousedistrict] [nvarchar] (50) NULL,
[warehouseaddress] [nvarchar] (100) NULL,
[warehousedescription] [nvarchar] (max) NULL,
[warehousetype] [nvarchar] (50) NULL,
[warehousecountry] [nvarchar] (50) NULL
)
GO
