/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[PAS_PL_OLine]
(
[PartitionKey] [varchar] (50) NOT NULL,
[company] [nvarchar] (8) NOT NULL,
[custnum] [nvarchar] (50) NULL,
[ordernum] [nvarchar] (50) NULL,
[orderline] [nvarchar] (50) NULL,
[ordersubline] [nvarchar] (50) NULL,
[ordertype] [nvarchar] (50) NULL,
[orderrelnum] [nvarchar] (50) NULL,
[orderdate] [nvarchar] (50) NULL,
[needbydate] [nvarchar] (50) NULL,
[delivdate] [nvarchar] (50) NULL,
[invoicenum] [nvarchar] (50) NULL,
[orderqty] [nvarchar] (50) NULL,
[delivqty] [nvarchar] (50) NULL,
[remainingqty] [nvarchar] (50) NULL,
[unitprice] [nvarchar] (50) NULL,
[unitcost] [nvarchar] (50) NULL,
[currency] [nvarchar] (50) NULL,
[currexchrate] [nvarchar] (50) NULL,
[openrelease] [nvarchar] (1) NULL,
[discountpercent] [nvarchar] (50) NULL,
[discountamount] [nvarchar] (50) NULL,
[partnum] [nvarchar] (50) NULL,
[partstatus] [nvarchar] (50) NULL,
[salesperson] [nvarchar] (150) NULL,
[returncomment] [nvarchar] (50) NULL,
[salesreturnordernum] [nvarchar] (50) NULL,
[salesreturninvoicenum] [nvarchar] (50) NULL,
[warehousecode] [nvarchar] (50) NULL,
[saleschannel] [nvarchar] (50) NULL,
[businesschain] [nvarchar] (50) NULL,
[res1] [nvarchar] (200) NULL,
[res2] [nvarchar] (100) NULL,
[res3] [nvarchar] (100) NULL
)
GO
