/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[PIM_ALL_Product]
(
[ProductID] [nvarchar] (50) NULL,
[PartitionKey] [nvarchar] (50) NULL,
[Manufacturer_Id] [nvarchar] (50) NULL,
[Brand] [nvarchar] (50) NULL,
[Heading] [nvarchar] (500) NULL,
[Original_Description] [nvarchar] (max) NULL,
[Last_category_name] [nvarchar] (500) NULL,
[Category_name] [nvarchar] (500) NULL,
[Category_name2] [nvarchar] (500) NULL,
[Category_name3] [nvarchar] (500) NULL,
[Category_name4] [nvarchar] (500) NULL,
[Category_name5] [nvarchar] (500) NULL,
[Category_name6] [nvarchar] (500) NULL,
[Item_no_Acorn] [nvarchar] (50) NULL,
[Item_no_Arkov] [nvarchar] (50) NULL,
[Item_no_Bell] [nvarchar] (50) NULL,
[Item_no_GMMIT] [nvarchar] (50) NULL,
[Item_no_Jens_SDK] [nvarchar] (50) NULL,
[Item_no_Jens_SNO] [nvarchar] (50) NULL,
[Item_no_Jens_SSE] [nvarchar] (50) NULL,
[Item_no_KTT] [nvarchar] (50) NULL,
[Item_no_MAK] [nvarchar] (50) NULL,
[Item_no_NOMODK] [nvarchar] (50) NULL,
[Item_no_NOMOFI] [nvarchar] (50) NULL,
[Item_no_NOMONO] [nvarchar] (50) NULL,
[Item_no_NOMOSE] [nvarchar] (50) NULL,
[Item_no_Jens_SNB] [nvarchar] (50) NULL,
[Item_no_Passerotti] [nvarchar] (50) NULL,
[Item_no_SKS] [nvarchar] (50) NULL,
[Item_no_Jens_SSK] [nvarchar] (50) NULL,
[Item_no_Spruit] [nvarchar] (50) NULL,
[Item_no_Sverull] [nvarchar] (50) NULL,
[Item_no_TNXSI] [nvarchar] (50) NULL,
[Item_no_TPNNO] [nvarchar] (50) NULL
)
GO
