/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[RLS]
(
[Modify_datetime] [datetime] NULL CONSTRAINT [DF__RLS__Modify_date__064DE20A] DEFAULT (getdate()),
[Company] [nvarchar] (30) NULL,
[Email] [nvarchar] (50) NULL,
[RLSTable] [nvarchar] (40) NULL,
[RLSField] [nvarchar] (40) NULL,
[RLSValue] [nvarchar] (40) NULL,
[AccessType] [nvarchar] (50) NULL,
[SourceList] [nvarchar] (100) NULL,
[Author] [nvarchar] (50) NULL
)
GO
