/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[ROR_SE_StockTransactionOB20180101]
(
[﻿PartitionKey] [nvarchar] (50) NULL,
[Company] [nvarchar] (50) NULL,
[WarehouseCode] [nvarchar] (50) NULL,
[TransactionCode] [nvarchar] (50) NULL,
[TransactionCodeDescription] [nvarchar] (50) NULL,
[IsInternalTransaction] [nvarchar] (50) NULL,
[TransactionDate] [nvarchar] (50) NULL,
[PartNum] [nvarchar] (50) NULL,
[TransactionQty] [nvarchar] (50) NULL,
[TransactionValue] [nvarchar] (50) NULL,
[Currency] [nvarchar] (50) NULL,
[ExchangeRate] [nvarchar] (50) NULL,
[Reference] [nvarchar] (50) NULL
)
GO
