/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[ROR_SE_OLine]
(
[PartitionKey] [nvarchar] (50) NULL,
[Company] [nvarchar] (8) NULL,
[CustomerNum] [nvarchar] (50) NULL,
[SalesOrderNum] [nvarchar] (50) NULL,
[SalesOrderLine] [nvarchar] (50) NULL,
[SalesOrderSubLine] [nvarchar] (max) NULL,
[SalesOrderType] [nvarchar] (max) NULL,
[SalesOrderCategory] [nvarchar] (50) NULL,
[SalesOrderDate] [nvarchar] (50) NULL,
[NeedbyDate] [nvarchar] (50) NULL,
[ExpDelivDate] [nvarchar] (50) NULL,
[ActualDelivDate] [nvarchar] (50) NULL,
[SalesInvoiceNum] [nvarchar] (50) NULL,
[SalesOrderQty] [decimal] (18, 4) NULL,
[DelivQty] [decimal] (18, 4) NULL,
[RemainingQty] [decimal] (18, 4) NULL,
[UoM] [nvarchar] (50) NULL,
[UnitPrice] [decimal] (18, 4) NULL,
[UnitCost] [decimal] (18, 4) NULL,
[Currency] [nvarchar] (50) NULL,
[ExchangeRate] [decimal] (18, 4) NULL,
[OpenRelease] [nvarchar] (50) NULL,
[DiscountPercent] [decimal] (18, 4) NULL,
[DiscountAmount] [decimal] (18, 4) NULL,
[PartNum] [nvarchar] (50) NULL,
[PartType] [nvarchar] (max) NULL,
[PartStatus] [nvarchar] (max) NULL,
[SalesPersonName] [nvarchar] (50) NULL,
[WarehouseCode] [nvarchar] (50) NULL,
[Cancellation] [nvarchar] (50) NULL,
[SalesOrderStatus] [nvarchar] (50) NULL,
[SalesChannel] [nvarchar] (50) NULL
)
GO
