/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[ROR_SE_PurchaseLedger]
(
[PartitionKey] [nvarchar] (50) NOT NULL,
[Company] [nvarchar] (8) NULL,
[Currency] [nvarchar] (50) NULL,
[ExchangeRate] [nvarchar] (50) NULL,
[SupplierNum] [nvarchar] (50) NULL,
[PurchaseOrderNum] [nvarchar] (50) NULL,
[PurchaseInvoiceNum] [nvarchar] (50) NULL,
[CreatedTimeStamp] [nvarchar] (50) NULL,
[ModifiedTimeStamp] [nvarchar] (50) NULL,
[IsActiveRecord] [nvarchar] (50) NULL,
[PurchaseInvoiceDate] [nvarchar] (50) NULL,
[IsInvoiceClosed] [nvarchar] (50) NULL,
[VATAmount] [nvarchar] (50) NULL,
[InvoiceAmount] [nvarchar] (50) NULL,
[SupplierInvoiceNum] [nvarchar] (50) NULL,
[PurchaseDueDate] [nvarchar] (50) NULL,
[PurchaseLastPaymentDate] [nvarchar] (50) NULL,
[PaidInvoiceAmount] [nvarchar] (50) NULL,
[RemainingInvoiceAmount] [nvarchar] (50) NULL,
[AccountingDate] [nvarchar] (50) NULL,
[PaymentTerms] [nvarchar] (50) NULL,
[LinktoOriginalInvoice] [nvarchar] (50) NULL,
[VATCode] [nvarchar] (50) NULL,
[VATCodeDesc] [nvarchar] (max) NULL,
[CostUnitNum] [nvarchar] (50) NULL,
[PayToName] [nvarchar] (50) NULL,
[PayToCity] [nvarchar] (50) NULL,
[PayToContact] [nvarchar] (50) NULL,
[PaymentEvents] [nvarchar] (50) NULL,
[PLRes1] [nvarchar] (100) NULL,
[PLRes2] [nvarchar] (100) NULL
)
GO
