/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[ROR_SE_Supplier]
(
[PartitionKey] [nvarchar] (50) NULL,
[Company] [nvarchar] (8) NULL,
[SupplierNum] [nvarchar] (50) NULL,
[SupplierName] [nvarchar] (50) NULL,
[ParentSupplierName] [nvarchar] (500) NULL,
[AddressLine1] [nvarchar] (50) NULL,
[AddressLine2] [nvarchar] (50) NULL,
[AddressLine3] [nvarchar] (50) NULL,
[TelephoneNum1] [nvarchar] (50) NULL,
[ZipCode] [nvarchar] (50) NULL,
[City] [nvarchar] (50) NULL,
[CountryName] [nvarchar] (50) NULL,
[VATNum] [nvarchar] (50) NULL,
[TelephoneNum2] [nvarchar] (50) NULL,
[Email] [nvarchar] (50) NULL,
[State] [nvarchar] (50) NULL,
[AccountNum] [nvarchar] (50) NULL,
[CountryCode] [nvarchar] (50) NULL,
[SupplierGroup] [nvarchar] (50) NULL,
[SupplierSubGroup] [nvarchar] (50) NULL,
[SupplierIndustry] [nvarchar] (50) NULL,
[SupplierSubIndustry] [nvarchar] (50) NULL,
[PurchaserPers] [nvarchar] (50) NULL,
[PurchaserPersonName] [nvarchar] (500) NULL,
[SupplierResponsible] [nvarchar] (50) NULL,
[OrgNum] [nvarchar] (50) NULL,
[IsAxInterInternal] [nvarchar] (50) NULL,
[IsBusinessAreaInternal] [nvarchar] (50) NULL,
[IsCompanyGroupInternal] [nvarchar] (50) NULL,
[CodeOfConduct] [nvarchar] (50) NULL,
[SupplierScore] [nvarchar] (50) NULL,
[SupplierType] [nvarchar] (50) NULL,
[MinOrderQty] [nvarchar] (50) NULL,
[MinOrderValue] [nvarchar] (50) NULL,
[MinOrderValueCurrency] [nvarchar] (50) NULL,
[CreatedTimeStamp] [nvarchar] (50) NULL,
[ModifiedTimeStamp] [nvarchar] (50) NULL,
[IsActiveRecord] [nvarchar] (50) NULL,
[Website] [nvarchar] (500) NULL,
[Comments] [nvarchar] (max) NULL
)
GO
