/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[ROR_SE_SalesLedger]
(
[PartitionKey] [varchar] (50) NULL,
[Company] [nvarchar] (8) NULL,
[CustomerNum] [nvarchar] (50) NULL,
[SalesInvoiceNum] [nvarchar] (50) NULL,
[SalesInvoiceDate] [date] NULL,
[SalesDueDate] [date] NULL,
[SalesLastPaymentDate] [date] NULL,
[AccountingDate] [date] NULL,
[InvoiceAmount] [decimal] (18, 4) NULL,
[PaidInvoiceAmount] [decimal] (18, 4) NULL,
[RemainingInvoiceAmount] [decimal] (18, 4) NULL,
[ExchangeRate] [nvarchar] (max) NULL,
[Currency] [nvarchar] (50) NULL,
[VATAmount] [decimal] (18, 4) NULL,
[VATCode] [nvarchar] (50) NULL,
[PayToName] [nvarchar] (50) NULL,
[PayToCity] [nvarchar] (50) NULL,
[PayToContact] [nvarchar] (50) NULL,
[PaymentTerms] [nvarchar] (50) NULL
)
GO
