/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[SCM_FI_Warehouse]
(
[PartitionKey] [nvarchar] (50) NULL,
[Company] [nvarchar] (50) NULL,
[WarehouseID] [nvarchar] (50) NULL,
[WarehouseCode] [nvarchar] (50) NULL,
[WarehouseName] [nvarchar] (50) NULL,
[WarehouseDistrict] [nvarchar] (50) NULL,
[WarehouseAddress] [nvarchar] (50) NULL,
[WarehouseDescription] [nvarchar] (50) NULL,
[WarehouseType] [nvarchar] (50) NULL,
[WarehouseCountry] [nvarchar] (50) NULL,
[WarehouseSite] [nvarchar] (50) NULL
)
GO
