/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[SCM_FI_Budget]
(
[PartitionKey] [nvarchar] (50) NULL,
[Company] [nvarchar] (8) NULL,
[BudgetPeriod] [nvarchar] (20) NULL,
[PeriodType] [nvarchar] (20) NULL,
[CustomerNum] [nvarchar] (20) NULL,
[CustomerGroup] [nvarchar] (20) NULL,
[SalesPerson] [nvarchar] (20) NULL,
[ProductGroup] [nvarchar] (20) NULL,
[BudgetSales] [decimal] (18, 4) NULL,
[BudgetCost] [decimal] (18, 4) NULL
)
GO
