/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[SKS_Merx MT-selailu]
(
[Asiakas] [nvarchar] (50) NULL,
[Company] [nvarchar] (50) NULL,
[Asiakas1] [nvarchar] (4000) NULL,
[Projekti] [nvarchar] (50) NULL,
[As_tilausnro] [nvarchar] (4000) NULL,
[Tilauspvm] [nvarchar] (50) NULL,
[Til_tyyppi] [nvarchar] (50) NULL,
[MT] [nvarchar] (50) NULL,
[MT_rivi] [nvarchar] (50) NULL,
[Tila] [nvarchar] (50) NULL,
[Tuote] [nvarchar] (50) NULL,
[Kuvaus] [nvarchar] (4000) NULL,
[Tilattu_määrä] [decimal] (18, 8) NULL,
[Laskutettu_määrä] [decimal] (18, 8) NULL,
[Myyntiyks] [nvarchar] (50) NULL,
[Rivin_arvo] [decimal] (18, 8) NULL,
[Rivi_KEHH] [decimal] (18, 8) NULL,
[Kate] [decimal] (18, 8) NULL,
[RowText] [varchar] (max) NULL,
[OriginalFile] [varchar] (50) NULL
)
GO
