/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[SKS_FI_PurchaseOrder]
(
[PartitionKey] [varchar] (50) NOT NULL,
[EKORG] [nvarchar] (8) NOT NULL,
[PURCHASEORDERNUM] [varchar] (50) NULL,
[PURCHASEORDERLINE] [nvarchar] (50) NULL,
[PURCHASEORDERSUBLINE] [nvarchar] (50) NULL,
[ORDERTYPE] [nvarchar] (50) NULL,
[PURCHASEORDERDATE] [nvarchar] (50) NULL,
[ORGREQDELIVDATE] [nvarchar] (50) NULL,
[COMMITEDDELIVDATE] [nvarchar] (50) NULL,
[DELIVDATE] [nvarchar] (50) NULL,
[REQDELIVDATE] [nvarchar] (50) NULL,
[INVOICENUM] [nvarchar] (50) NULL,
[PARTNUM] [nvarchar] (50) NULL,
[SUPPLIERNUM] [nvarchar] (50) NULL,
[DELIVCUSTNUM] [nvarchar] (50) NULL,
[ITEMSTATUS] [nvarchar] (50) NULL,
[ORDEREDQTY] [decimal] (18, 4) NULL,
[RECEIVEDQTY] [decimal] (18, 4) NULL,
[INVOICEDQTY] [decimal] (18, 4) NULL,
[UNIT] [nvarchar] (50) NULL,
[UNITPRICE] [decimal] (18, 4) NULL,
[DISCOUNTPERCENT] [decimal] (18, 4) NULL,
[DISCOUNTAMOUNT] [decimal] (18, 4) NULL,
[EXCHANGERATE] [decimal] (18, 4) NULL,
[CURRENCY] [nvarchar] (50) NULL,
[PURCHASERNAME] [nvarchar] (50) NULL,
[WAREHOUSECODE] [nvarchar] (50) NULL,
[RECIEVINGNUM] [nvarchar] (50) NULL,
[LEADTIME] [nvarchar] (50) NULL,
[PURCHASECHANNEL] [nvarchar] (50) NULL,
[COMMENTS] [nvarchar] (50) NULL,
[PORES1] [nvarchar] (50) NULL,
[PORES2] [nvarchar] (50) NULL,
[PORES3] [nvarchar] (50) NULL,
[MANDT] [nvarchar] (50) NULL,
[BUKRS] [nvarchar] (50) NULL,
[SURCHARGEAMOUNT] [decimal] (18, 4) NULL,
[ETENR] [nvarchar] (50) NULL,
[ZZSHIPDT] [nvarchar] (50) NULL,
[EINDT] [nvarchar] (50) NULL,
[COMMITEDDATESKS] [nvarchar] (50) NULL
)
GO
