/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[SKS_FI_Budget]
(
[PartitionKey] [varchar] (50) NULL,
[MANDT] [nvarchar] (50) NULL,
[PBUKR] [nvarchar] (50) NULL,
[PSPNR] [nvarchar] (50) NULL,
[COMPANY] [nvarchar] (50) NULL,
[ERDAT] [nvarchar] (50) NULL,
[KUNNR] [nvarchar] (50) NULL,
[POSKI] [nvarchar] (50) NULL,
[KDGRP] [nvarchar] (50) NULL,
[PRDGRP] [nvarchar] (50) NULL,
[SALESMEN] [nvarchar] (50) NULL,
[POST1] [nvarchar] (200) NULL,
[POSID] [nvarchar] (50) NULL,
[PWPOS] [nvarchar] (50) NULL,
[BUDJ_SALES] [decimal] (18, 8) NULL,
[BUDJ_COST] [decimal] (18, 8) NULL
)
GO
