/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[SKS_Customer_complement]
(
[Company] [nvarchar] (50) NULL,
[CustomerNum] [nvarchar] (50) NULL,
[MainCustomerName] [nvarchar] (50) NULL,
[CustomerName] [nvarchar] (50) NULL,
[Customer] [nvarchar] (50) NULL,
[AddressLine1] [nvarchar] (100) NULL,
[AddressLine2] [nvarchar] (100) NULL,
[AddressLine3] [nvarchar] (100) NULL,
[TelephoneNum1] [nvarchar] (50) NULL,
[TelephoneNum2] [nvarchar] (50) NULL,
[Email] [nvarchar] (50) NULL,
[ZipCode] [nvarchar] (50) NULL,
[City] [nvarchar] (50) NULL,
[State] [nvarchar] (50) NULL,
[SalesDistrict] [nvarchar] (50) NULL,
[CountryName] [nvarchar] (50) NULL,
[Division] [nvarchar] (50) NULL,
[CustomerIndustry] [nvarchar] (50) NULL,
[CustomerSubIndustry] [nvarchar] (50) NULL,
[AddressLine] [nvarchar] (200) NULL,
[FullAddressLine] [nvarchar] (300) NULL,
[CustomerGroup] [nvarchar] (max) NULL,
[CustomerSubGroup] [nvarchar] (50) NULL,
[SalesPersonCode] [nvarchar] (50) NULL,
[SalesPersonName] [nvarchar] (50) NULL,
[SalesPersonResponsible] [nvarchar] (50) NULL,
[VATNum] [nvarchar] (50) NULL,
[AccountNum] [nvarchar] (50) NULL,
[InternalExternal] [nvarchar] (50) NULL,
[CustomerScore] [nvarchar] (50) NULL,
[CustomerType] [nvarchar] (50) NULL
)
GO
