/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[SKS_FI_SalesLedger]
(
[PartitionKey] [varchar] (50) NOT NULL,
[MANDT] [nvarchar] (3) NOT NULL,
[VKORG] [nvarchar] (4) NULL,
[INVOICENUM] [nvarchar] (50) NULL,
[COMPANY] [nvarchar] (8) NOT NULL,
[CUSTOMERNUM] [nvarchar] (50) NULL,
[DUEDATE] [nvarchar] (8) NULL,
[LASTPAYMENTDATE] [nvarchar] (8) NULL,
[INVOICEDATE] [nvarchar] (8) NULL
)
GO
