/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[SKS_Merx OT-selailu]
(
[Company] [nvarchar] (50) NULL,
[Toimittaja] [nvarchar] (50) NULL,
[Toimittaja1] [nvarchar] (4000) NULL,
[Projekti] [nvarchar] (50) NULL,
[Tilauspvm] [nvarchar] (50) NULL,
[Tilaustyyppi] [nvarchar] (50) NULL,
[Ostotilaus] [nvarchar] (50) NULL,
[Ostotilausrivi] [nvarchar] (50) NULL,
[Tuote] [nvarchar] (50) NULL,
[Kuvaus] [nvarchar] (4000) NULL,
[Tuotteen_myyntiyksikkö] [nvarchar] (50) NULL,
[Tilattu_määrä] [decimal] (18, 8) NULL,
[Tullut_määrä] [decimal] (18, 8) NULL,
[Tilattu] [decimal] (18, 8) NULL,
[Hankintahinta] [decimal] (18, 8) NULL,
[Hankintahinta_val] [decimal] (18, 8) NULL,
[Valuutta] [nvarchar] (50) NULL,
[Ale_1] [decimal] (18, 8) NULL,
[Ale_2] [decimal] (18, 8) NULL,
[Ale_3] [decimal] (18, 8) NULL,
[Kulukerroin] [decimal] (18, 8) NULL,
[Ostoyksikkö] [nvarchar] (50) NULL,
[Muuntokerroin] [decimal] (18, 8) NULL,
[RowText] [varchar] (max) NULL,
[OriginalFile] [varchar] (50) NULL
)
GO
