/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[SKS_FI_PurchaseInvoice]
(
[PartitionKey] [varchar] (50) NOT NULL,
[BUKRS] [nvarchar] (8) NULL,
[EKORG] [nvarchar] (50) NULL,
[PURCHASEORDERNUM] [nvarchar] (50) NULL,
[PURCHASEORDERLINE] [nvarchar] (50) NULL,
[ORDERTYPE] [nvarchar] (50) NULL,
[PURCHASEINVOICENUM] [nvarchar] (50) NULL,
[INVOICELINE] [nvarchar] (50) NULL,
[INVOICETYPE] [nvarchar] (50) NULL,
[INVOICEDATE] [nvarchar] (50) NULL,
[ACTUALDELIVDATE] [nvarchar] (50) NULL,
[SUPPLIERNUM] [nvarchar] (50) NULL,
[PARTNUM] [nvarchar] (50) NULL,
[PURCHASESHIPQTY] [decimal] (18, 4) NULL,
[UNIT] [nvarchar] (50) NULL,
[UNITPRICE] [decimal] (18, 4) NULL,
[DISCOUNTAMOUNT] [decimal] (18, 4) NULL,
[TOTALMISCCHRG] [nvarchar] (50) NULL,
[VAT] [nvarchar] (50) NULL,
[CURRENCY] [nvarchar] (50) NULL,
[EXCHANGERATE] [decimal] (18, 4) NULL,
[CREDITMEMO] [nvarchar] (50) NULL,
[PURCHASERNAME] [nvarchar] (100) NULL,
[WAREHOUSECODE] [nvarchar] (50) NULL,
[PURCHASECHANNEL] [nvarchar] (50) NULL,
[MANDT] [nvarchar] (50) NULL,
[GJAHR] [nvarchar] (50) NULL,
[ORDERDELIVLINENUM] [nvarchar] (50) NULL,
[DUEDATE] [nvarchar] (50) NULL,
[PIRES1] [nvarchar] (50) NULL,
[PIRES2] [nvarchar] (50) NULL,
[PIRES3] [nvarchar] (50) NULL
)
GO
