/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[SKS_FI_Customer]
(
[PartitionKey] [varchar] (50) NOT NULL,
[MANDT] [nvarchar] (50) NOT NULL,
[VKORG] [nvarchar] (50) NOT NULL,
[COMPANY] [nvarchar] (8) NOT NULL,
[CUSTNUM] [nvarchar] (50) NOT NULL,
[CUSTOMERNAME] [nvarchar] (100) NULL,
[ADDRESSLINE1] [nvarchar] (150) NULL,
[ABCCODE] [nchar] (20) NULL,
[CITY] [nvarchar] (50) NULL,
[ZIP] [nvarchar] (10) NULL,
[STATE] [nvarchar] (50) NULL,
[COUNTRYNAME] [nvarchar] (50) NULL,
[CUSTOMERGROUP] [nvarchar] (50) NULL,
[CUSTOMERGROUPTEXT] [nvarchar] (50) NULL,
[SALESREPCODE] [nvarchar] (50) NULL,
[VATREGNR] [nvarchar] (20) NULL,
[VKGRP] [nvarchar] (10) NULL,
[SALESPERSONNAME] [nvarchar] (150) NULL,
[TELEPHONE1] [nvarchar] (30) NULL,
[TELEPHONE2] [nvarchar] (30) NULL,
[EMAIL] [nvarchar] (300) NULL,
[ADDRESSLINE2] [nvarchar] (50) NULL,
[ADDRESSLINE3] [nvarchar] (50) NULL,
[DISTRICT] [nvarchar] (50) NULL,
[DIVISION] [nvarchar] (50) NULL,
[CUSTOMERSUBGROUP] [nvarchar] (50) NULL,
[SALESPERSONRESPONSIBLE] [nvarchar] (50) NULL,
[ACCOUNTSTRING] [nvarchar] (50) NULL,
[INTERNALEXTERNAL] [nvarchar] (2) NULL,
[CUSTOMERABC] [nvarchar] (50) NULL,
[CUSTOMERTYPE] [nvarchar] (50) NULL,
[SALESPERSON] [nvarchar] (50) NULL,
[SALESDISTRICT] [nvarchar] (50) NULL,
[INTCA] [nvarchar] (12) NULL
)
GO
