/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[SKS_FI_PlanValues]
(
[PartitionKey] [varchar] (50) NULL,
[MANDT] [nvarchar] (50) NULL,
[COMPANY] [nvarchar] (50) NULL,
[LEDNR] [nvarchar] (50) NULL,
[BZOBJ] [nvarchar] (50) NULL,
[KALNR] [nvarchar] (50) NULL,
[KALKA] [nvarchar] (50) NULL,
[KADKY] [nvarchar] (50) NULL,
[TVERS] [nvarchar] (50) NULL,
[BWVAR] [nvarchar] (50) NULL,
[KKZMA] [nvarchar] (50) NULL,
[POSNR] [nvarchar] (50) NULL,
[KSTAR] [nvarchar] (50) NULL,
[PSPNR] [nvarchar] (50) NULL,
[WERTN] [decimal] (18, 8) NULL,
[WRTFW_POS] [decimal] (18, 8) NULL,
[FWAER] [nvarchar] (50) NULL,
[WERKS] [nvarchar] (50) NULL,
[BUKRS] [nvarchar] (50) NULL
)
GO
