/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[SKS_FI_Claim]
(
[PartitionKey] [varchar] (50) NULL,
[MANDT] [nvarchar] (50) NULL,
[QMNUM] [nvarchar] (50) NULL,
[QMART] [nvarchar] (50) NULL,
[QMTXT] [nvarchar] (200) NULL,
[PRIOK] [nvarchar] (50) NULL,
[ERNAM] [nvarchar] (50) NULL,
[ERDAT] [nvarchar] (50) NULL,
[MZEIT] [nvarchar] (50) NULL,
[QMDAT] [nvarchar] (50) NULL,
[STRUR] [nvarchar] (50) NULL,
[MATNR] [nvarchar] (50) NULL,
[MATKL] [nvarchar] (50) NULL,
[PRDHA] [nvarchar] (50) NULL,
[KUNUM] [nvarchar] (50) NULL,
[BEZDT] [nvarchar] (50) NULL,
[BEZUR] [nvarchar] (50) NULL,
[LIFNUM] [nvarchar] (50) NULL,
[VBELN] [nvarchar] (50) NULL,
[BSTNK] [nvarchar] (50) NULL,
[VKORG] [nvarchar] (50) NULL,
[QMGRP] [nvarchar] (50) NULL,
[QMCOD] [nvarchar] (50) NULL,
[ZDESCRIPTION] [nvarchar] (200) NULL,
[ZPARTNER] [nvarchar] (50) NULL
)
GO
