/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[SKS_FI_Project]
(
[PartitionKey] [varchar] (50) NOT NULL,
[COMPANY] [nvarchar] (8) NULL,
[MANDT] [nvarchar] (50) NULL,
[PBUKR] [nvarchar] (50) NULL,
[PSPNR] [nvarchar] (50) NULL,
[POSKI] [nvarchar] (50) NULL,
[POST1] [nvarchar] (max) NULL,
[PKOKR] [nvarchar] (50) NULL,
[POSID] [nvarchar] (50) NULL,
[OBJNR] [nvarchar] (50) NULL,
[PRCTR] [nvarchar] (50) NULL,
[KVEWE] [nvarchar] (50) NULL,
[KAPPL] [nvarchar] (50) NULL,
[STUFE] [nvarchar] (50) NULL,
[PWPOS] [nvarchar] (50) NULL,
[WERKS] [nvarchar] (50) NULL,
[ERDAT] [nvarchar] (50) NULL,
[TOT_COST] [nvarchar] (50) NULL
)
GO
