/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[SKS_CustomerOldDev]
(
[CustomerID] [nvarchar] (100) NULL,
[CustomerCode] [nvarchar] (50) NULL,
[CompanyID] [nvarchar] (100) NULL,
[PartitionKey] [varchar] (50) NULL,
[Company] [nvarchar] (100) NULL,
[CustomerNum] [nvarchar] (100) NULL,
[MainCustomerName] [nvarchar] (100) NULL,
[CustomerName] [nvarchar] (100) NULL,
[AddressLine1] [nvarchar] (100) NULL,
[AddressLine2] [nvarchar] (100) NULL,
[AddressLine3] [nvarchar] (100) NULL,
[TelephoneNumber1] [nvarchar] (100) NULL,
[TelephoneNumber2] [nvarchar] (100) NULL,
[Email] [nvarchar] (100) NULL,
[ZipCode] [nvarchar] (100) NULL,
[City] [nvarchar] (100) NULL,
[State] [nvarchar] (100) NULL,
[District] [nvarchar] (100) NULL,
[CountryName] [nvarchar] (100) NULL,
[Division] [nvarchar] (100) NULL,
[CustomerIndustry] [nvarchar] (100) NULL,
[CustomerSubIndustry] [nvarchar] (100) NULL,
[AddressLine] [nvarchar] (300) NULL,
[FullAddressLine] [nvarchar] (300) NULL,
[CustomerGroup] [nvarchar] (100) NULL,
[CustomerSubGroup] [nvarchar] (100) NULL,
[SalesRepCode] [nvarchar] (100) NULL,
[SalesPersonName] [nvarchar] (100) NULL,
[SalesPersonResponsible] [nvarchar] (100) NULL,
[VATRegNr] [nvarchar] (100) NULL,
[AccountString] [nvarchar] (100) NULL,
[InternalExternal] [nvarchar] (100) NULL,
[CustomerABC] [nvarchar] (100) NULL,
[CustomerType] [nvarchar] (100) NULL
)
GO
