/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[SKS_FI_mapStockTranCode]
(
[TransactionCode] [nvarchar] (50) NOT NULL,
[TransactionDescription] [nvarchar] (200) NULL,
[Internal_External] [nvarchar] (50) NULL,
[Description] [nvarchar] (200) NULL,
[Comment] [nvarchar] (200) NULL
)
GO
