/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[SKS_FI_PurchaseLedger]
(
[PartitionKey] [nvarchar] (50) NOT NULL,
[BUKRS] [nvarchar] (8) NOT NULL,
[EKORG] [nvarchar] (50) NULL,
[SUPPLIERNUM] [nvarchar] (50) NULL,
[PURCHASEORDERNUM] [nvarchar] (50) NULL,
[PURCHASEINVOICENUM] [nvarchar] (50) NULL,
[INVOICEDATE] [nvarchar] (50) NULL,
[DUEDATE] [nvarchar] (50) NULL,
[LASTPAYMENTDATE] [nvarchar] (50) NULL,
[INVOICELCYAMOUNT] [decimal] (18, 4) NULL,
[INVOICECURRAMOUNT] [decimal] (18, 4) NULL,
[EXCHANGERATE] [decimal] (18, 4) NULL,
[CURRENCY] [nvarchar] (50) NULL,
[VATPAID] [decimal] (18, 4) NULL,
[VATCODE] [nvarchar] (50) NULL,
[PAYTONAME] [nvarchar] (50) NULL,
[PAYTOCITY] [nvarchar] (50) NULL,
[PAYTOCONTACT] [nvarchar] (50) NULL,
[PAYMENTTERMSCODE] [nvarchar] (50) NULL,
[PREPAYMENTNUM] [nvarchar] (50) NULL,
[LASTPAYMENTNUM] [nvarchar] (50) NULL,
[GJAHR] [nvarchar] (50) NULL,
[MANDT] [nvarchar] (50) NULL,
[PLRES1] [nvarchar] (50) NULL,
[PLRES2] [nvarchar] (50) NULL,
[PLRES3] [nvarchar] (50) NULL
)
GO
