/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[SKS_FI_StockTransaction]
(
[PartitionKey] [nvarchar] (50) NOT NULL,
[MANDT] [nvarchar] (8) NULL,
[SYSROWID] [nvarchar] (50) NOT NULL,
[COMPANY] [nvarchar] (8) NOT NULL,
[WAREHOUSECODE] [nvarchar] (50) NULL,
[TRANSTYPE] [nvarchar] (50) NULL,
[TRANSTYPEDESC] [nvarchar] (max) NULL,
[PARTNUM] [nvarchar] (50) NULL,
[TRANQTY] [nvarchar] (50) NULL,
[BINNUM] [nvarchar] (50) NULL,
[BARTCHNUM] [nvarchar] (50) NULL,
[TRANSACTIONDATE] [nvarchar] (50) NULL,
[CREATEDATE] [nvarchar] (50) NULL,
[TRANSACTIONTIME] [nvarchar] (20) NULL,
[ORDERNUM] [nvarchar] (50) NULL,
[INVOICENUM] [nvarchar] (50) NULL,
[COSTPRICE] [nvarchar] (50) NULL,
[SELLINGPRICE] [nvarchar] (50) NULL,
[CURRENCY] [nvarchar] (50) NULL,
[ISSUERRECEIVERCODE] [nvarchar] (50) NULL,
[TRANSOURCE] [nvarchar] (50) NULL,
[TRANVALUE] [nvarchar] (50) NULL,
[REFERENCE] [nvarchar] (50) NULL,
[SRES1] [nvarchar] (50) NULL,
[SRES2] [nvarchar] (50) NULL,
[SRES3] [nvarchar] (50) NULL
)
GO
