/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[SPR_NL_SOLine]
(
[PartitionKey] [varchar] (50) NULL,
[Company] [nvarchar] (50) NOT NULL,
[CustomerNum] [nvarchar] (50) NOT NULL,
[SalesOrderNum] [nvarchar] (50) NULL,
[SalesOrderSubLine] [nvarchar] (50) NULL,
[SalesOrderType] [varchar] (50) NULL,
[ActualDelivDate] [varchar] (50) NULL,
[SalesInvoiceNum] [nvarchar] (50) NULL,
[SalesInvoiceLine] [nvarchar] (50) NULL,
[UoM] [varchar] (50) NULL,
[UnitPrice] [varchar] (50) NULL,
[UnitCost] [varchar] (50) NULL,
[Currency] [varchar] (50) NULL,
[ExchangeRate] [varchar] (50) NULL,
[DiscountPercent] [varchar] (50) NULL,
[DiscountAmount] [varchar] (50) NULL,
[PartNum] [nvarchar] (50) NULL,
[PartType] [varchar] (50) NULL,
[WarehouseCode] [varchar] (50) NULL,
[SalesChannel] [varchar] (50) NULL,
[Department] [varchar] (50) NULL,
[ProjectNum] [varchar] (50) NULL,
[IndexKey] [varchar] (50) NULL,
[ctSalesO] [varchar] (50) NULL,
[SalesOrderLine] [varchar] (50) NULL,
[SalesInvoiceType] [varchar] (50) NULL,
[SalesInvoiceDate] [varchar] (50) NULL,
[SalesInvoiceQty] [varchar] (50) NULL,
[CashDiscountOffered] [varchar] (50) NULL,
[CashDiscountUsed] [varchar] (50) NULL,
[TotalMiscChrg] [varchar] (50) NULL,
[VATAmount] [varchar] (50) NULL,
[CreditMemo] [varchar] (50) NULL,
[CostBearerNum] [varchar] (50) NULL,
[CostUnitNum] [varchar] (50) NULL,
[ReturnComment] [varchar] (50) NULL,
[ReturnNum] [varchar] (50) NULL,
[ZipCode] [varchar] (50) NULL,
[City] [varchar] (50) NULL,
[Country] [varchar] (50) NULL,
[SIRes1] [varchar] (50) NULL,
[SIRes2] [varchar] (50) NULL,
[SIRes3] [varchar] (50) NULL
)
GO
