/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[SPR_NL_Budget]
(
[PartitionKey] [nvarchar] (25) NULL,
[Company] [nvarchar] (12) NULL,
[BudgetPeriodDate] [nvarchar] (15) NULL,
[PeriodType] [nvarchar] (15) NULL,
[Currency] [nvarchar] (10) NULL,
[BudgetSales] [nvarchar] (15) NULL
)
GO
