/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[SPR_NL_SalesLedger]
(
[PartitionKey] [varchar] (50) NULL,
[Company] [nvarchar] (8) NULL,
[CustomerNum] [nvarchar] (50) NULL,
[SalesInvoiceNum] [nvarchar] (50) NULL,
[SalesInvoiceDate] [nvarchar] (50) NULL,
[SalesDueDate] [nvarchar] (50) NULL,
[SalesLastPaymentDate] [nvarchar] (50) NULL,
[AccountingDate] [nvarchar] (50) NULL,
[ExchangeRate] [nvarchar] (50) NULL,
[Currency] [nvarchar] (50) NULL,
[InvoiceAmount] [nvarchar] (50) NULL,
[RemainingInvoiceAmount] [nvarchar] (50) NULL,
[PaidInvoiceAmount] [nvarchar] (50) NULL,
[VATAmount] [nvarchar] (50) NULL,
[VATCode] [nvarchar] (50) NULL,
[PayToName] [nvarchar] (50) NULL,
[PayToCity] [nvarchar] (50) NULL,
[PayToContact] [nvarchar] (50) NULL,
[AgingPeriod] [nvarchar] (50) NULL,
[PaymentTerms] [nvarchar] (50) NULL,
[SLRes1] [nvarchar] (50) NULL,
[SLRes2] [nvarchar] (50) NULL,
[SLRes3] [nvarchar] (50) NULL
)
GO
