/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[SPR_NL_ZipCode]
(
[Postcode] [varchar] (50) NULL,
[DorpPlaats] [varchar] (50) NULL,
[Gemeente] [varchar] (50) NULL,
[Provincie] [varchar] (50) NULL
)
GO
