/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[STE_SE_Customer]
(
[PartitionKey] [varchar] (50) NOT NULL,
[Company] [nvarchar] (100) NOT NULL,
[CustomerNum] [nvarchar] (100) NULL,
[CustomerName] [nvarchar] (max) NULL,
[AddressLine1] [nvarchar] (100) NULL,
[AddressLine2] [nvarchar] (100) NULL,
[ZipCode] [nvarchar] (100) NULL,
[City] [nvarchar] (100) NULL,
[CountryName] [nvarchar] (100) NULL,
[CountryCode] [nvarchar] (100) NULL,
[TelephoneNumber1] [nvarchar] (100) NULL,
[Email] [nvarchar] (100) NULL,
[VATNum] [nvarchar] (100) NULL,
[ModifiedTimeStamp] [nvarchar] (100) NULL,
[CustomerGroup] [nvarchar] (100) NULL,
[CustomerSubGroup] [nvarchar] (100) NULL,
[SalesPerson] [nvarchar] (100) NULL,
[CreditLimit] [nvarchar] (100) NULL,
[Currency Code] [nvarchar] (100) NULL,
[PaymentTerms] [nvarchar] (100) NULL,
[IsAxInterInternal] [nvarchar] (100) NULL,
[TEST_FIELD] [nvarchar] (100) NULL
)
GO
