/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[STE_SE_Part]
(
[PartitionKey] [varchar] (50) NOT NULL,
[Company] [nvarchar] (100) NOT NULL,
[PartNum] [nvarchar] (100) NULL,
[PartDescription] [nvarchar] (100) NULL,
[PartDescription2] [nvarchar] (100) NULL,
[ProductGroup] [nvarchar] (100) NULL,
[ProductGroup2] [nvarchar] (100) NULL,
[CountryOfOriginCode] [nvarchar] (100) NULL,
[ModifiedTimeStamp] [nvarchar] (100) NULL,
[UoM] [nvarchar] (100) NULL,
[PrimarySupplier] [nvarchar] (100) NULL,
[CommodityCode] [nvarchar] (100) NULL,
[NetWeight] [nvarchar] (100) NULL,
[ReOrderLevel] [nvarchar] (100) NULL,
[CountryOfOriginname] [nvarchar] (100) NULL,
[Barcode] [nvarchar] (100) NULL,
[PartResponsible] [nvarchar] (100) NULL,
[PartStatus] [nvarchar] (100) NULL,
[PartStatusIsActiveRecord] [nvarchar] (100) NULL
)
GO
