/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[STE_SE_Salesledger]
(
[PartitionKey] [varchar] (50) NOT NULL,
[Company] [nvarchar] (500) NULL,
[InvoiceNum] [nvarchar] (500) NULL,
[CustNum] [nvarchar] (500) NULL,
[InvoiceDate] [nvarchar] (500) NULL,
[DueDate] [nvarchar] (500) NULL,
[LastPaymentDate] [nvarchar] (500) NULL,
[IsInvoiceClosed] [nvarchar] (500) NULL,
[InvoiceAmount] [nvarchar] (500) NULL,
[PaidInvoiceAmount] [nvarchar] (500) NULL,
[RemainingInvoiceAmount] [nvarchar] (500) NULL,
[Currency] [nvarchar] (500) NULL,
[ExchangeRate] [nvarchar] (500) NULL,
[PaymentTerms] [nvarchar] (500) NULL
)
GO
