/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[STE_SE_SOLine]
(
[PartitionKey] [varchar] (50) NOT NULL,
[Company] [nvarchar] (500) NOT NULL,
[SalesInvoiceNum] [nvarchar] (500) NULL,
[SalesInvoiceLine] [nvarchar] (500) NULL,
[SalesInvoiceType] [nvarchar] (500) NULL,
[InvoiceDate] [nvarchar] (500) NULL,
[CustomerNum] [nvarchar] (500) NULL,
[PartNum] [nvarchar] (500) NULL,
[PartType] [nvarchar] (500) NULL,
[SalesOrderNum] [nvarchar] (500) NULL,
[SalesOrderLine] [nvarchar] (500) NULL,
[SalesOrderType] [nvarchar] (500) NULL,
[IsInvoiceClosed] [nvarchar] (500) NULL,
[ActualDelivDate] [nvarchar] (500) NULL,
[SalesInvoiceQty] [nvarchar] (500) NULL,
[UoM] [nvarchar] (500) NULL,
[UnitPrice] [nvarchar] (500) NULL,
[PrePostUnitCost] [nvarchar] (500) NULL,
[UnitCost] [nvarchar] (500) NULL,
[DiscountPercent] [nvarchar] (500) NULL,
[DiscountAmount] [nvarchar] (500) NULL,
[VATAmount] [nvarchar] (500) NULL,
[Sales Channel] [nvarchar] (500) NULL,
[WarehouseCode] [nvarchar] (500) NULL,
[ReturnNum] [nvarchar] (500) NULL,
[ReturnComment] [nvarchar] (500) NULL,
[CostUnitNum] [nvarchar] (500) NULL,
[IsCreditMemo] [nvarchar] (500) NULL,
[SalesPerson] [nvarchar] (500) NULL,
[DeliveryAddressLine] [nvarchar] (500) NULL,
[DeliveryZipCode] [nvarchar] (500) NULL,
[DeliveryCity] [nvarchar] (500) NULL,
[DeliveryCountry] [nvarchar] (500) NULL,
[Currency] [nvarchar] (500) NULL,
[CurrExchRate] [nvarchar] (500) NULL
)
GO
