/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[SUM_UK_SOLine]
(
[PartitionKey] [varchar] (50) NOT NULL,
[Company] [nvarchar] (8) NOT NULL,
[SalesPerson] [nvarchar] (100) NULL,
[CustNum] [nvarchar] (50) NULL,
[PartNum] [nvarchar] (50) NULL,
[OrderNum] [nvarchar] (50) NULL,
[OrderLine] [nvarchar] (50) NULL,
[OrderType] [nvarchar] (50) NULL,
[InvoiceNum] [nvarchar] (50) NULL,
[InvoiceLine] [nvarchar] (50) NULL,
[InvoiceType] [nvarchar] (50) NULL,
[InvoiceDate] [date] NULL,
[ActualDeliveryDate] [date] NULL,
[SellingShipQty] [decimal] (18, 4) NULL,
[Unit] [nvarchar] (50) NULL,
[UnitPrice] [decimal] (18, 4) NULL,
[UnitCost] [decimal] (18, 4) NULL,
[DiscountAmount] [decimal] (18, 4) NULL,
[TotalMiscChrg] [decimal] (18, 4) NULL,
[VAT] [decimal] (18, 4) NULL,
[Currency] [nvarchar] (50) NULL,
[ExchangeRate] [decimal] (18, 4) NULL,
[CreditMemo] [nvarchar] (50) NULL,
[SalesChannel] [nvarchar] (50) NULL,
[BusinessChain] [nvarchar] (50) NULL,
[WarehouseCode] [nvarchar] (50) NULL,
[Res1] [varchar] (100) NULL,
[Res2] [varchar] (100) NULL,
[Res3] [varchar] (100) NULL
)
GO
