/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[SUM_UK_Warehouse]
(
[PartitionKey] [varchar] (50) NOT NULL,
[Company] [nvarchar] (12) NOT NULL,
[WarehouseCode] [nvarchar] (50) NOT NULL,
[WarehouseName] [nvarchar] (100) NULL,
[WarehouseDistrict] [nvarchar] (100) NULL,
[WarehouseAddress] [nvarchar] (100) NULL,
[WarehouseDescription] [nvarchar] (100) NULL,
[WarehouseType] [nvarchar] (100) NULL,
[WarehouseCountry] [nvarchar] (100) NULL,
[Site] [nvarchar] (100) NULL,
[PartNum] [nvarchar] (50) NULL,
[PartDescription] [nvarchar] (50) NULL,
[PartDescription2] [nvarchar] (50) NULL,
[ProductGroup] [nvarchar] (50) NULL,
[ProductGroup2] [nvarchar] (50) NULL,
[CountryOfOriginCode] [nvarchar] (50) NULL
)
GO
