/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[SUM_UK_Part]
(
[PartitionKey] [varchar] (50) NOT NULL,
[Company] [nvarchar] (500) NULL,
[PartNum] [nvarchar] (500) NULL,
[PartName] [nvarchar] (500) NULL,
[PartDescription] [nvarchar] (500) NULL,
[PartDescription2] [nvarchar] (500) NULL,
[PartDescription3] [nvarchar] (500) NULL,
[ProductGroup] [nvarchar] (500) NULL,
[ProductGroup2] [nvarchar] (500) NULL,
[ProductGroup3] [nvarchar] (500) NULL,
[ProductGroup4] [nvarchar] (500) NULL,
[CountryOfOrigin] [nvarchar] (500) NULL,
[Brand] [nvarchar] (500) NULL,
[CommodityCode] [nvarchar] (500) NULL,
[PartNumReplacement] [nvarchar] (500) NULL,
[NetWeight] [nvarchar] (500) NULL,
[Volume] [nvarchar] (500) NULL,
[Material] [nvarchar] (500) NULL,
[Site] [nvarchar] (500) NULL,
[Barcode] [nvarchar] (500) NULL,
[ReorderLevel] [nvarchar] (500) NULL,
[MinOrderQty] [nvarchar] (500) NULL,
[StartDate] [nvarchar] (500) NULL,
[EndDate] [nvarchar] (500) NULL,
[ItemStatus] [nvarchar] (500) NULL,
[Res1] [nvarchar] (500) NULL,
[Res2] [nvarchar] (500) NULL,
[Res3] [nvarchar] (500) NULL
)
GO
