/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[SVE_SE_StockTransactionOB20230621]
(
[Company] [nvarchar] (8) NULL,
[WarehouseCode] [nvarchar] (50) NULL,
[SupplierNum] [nvarchar] (50) NULL,
[PartNum] [nvarchar] (50) NULL,
[StockBalance] [decimal] (18, 4) NULL,
[StockValue] [decimal] (18, 4) NULL,
[SalesRemainingQty] [decimal] (18, 4) NULL,
[AvgCost] [decimal] (18, 4) NULL,
[Currency] [nvarchar] (10) NULL,
[ExchangeRate] [decimal] (18, 4) NULL
)
GO
