/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[SVE_SE_Supplier]
(
[Company] [nvarchar] (8) NULL,
[PartitionKey] [nvarchar] (50) NULL,
[SupplierNum] [nvarchar] (500) NULL,
[SuplierName] [nvarchar] (500) NULL,
[AddressLine1] [nvarchar] (500) NULL,
[AddresLine2] [nvarchar] (500) NULL,
[TelephoneNum1] [nvarchar] (50) NULL,
[TelephoneNum2] [nvarchar] (50) NULL,
[Email] [nvarchar] (100) NULL,
[ZipCode] [nvarchar] (50) NULL,
[City] [nvarchar] (200) NULL,
[CountryCode] [nvarchar] (50) NULL,
[CountryName] [nvarchar] (50) NULL,
[SupplierIndustry] [nvarchar] (50) NULL,
[VATNum] [nvarchar] (50) NULL,
[OrgNum] [nvarchar] (50) NULL,
[AcountNum] [nvarchar] (50) NULL,
[IsAxInterInternal] [nvarchar] (50) NULL,
[CodeOfConduct] [nvarchar] (50) NULL,
[CreatedTimeStamp] [nvarchar] (50) NULL,
[ModifiedTimeSTamp] [nvarchar] (50) NULL,
[IsActiveRecord] [nvarchar] (50) NULL,
[Website] [nvarchar] (100) NULL,
[SRes1] [nvarchar] (100) NULL
)
GO
