/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[SVE_SE_StockBalance]
(
[PartitionKey] [varchar] (50) NULL,
[Company] [nvarchar] (50) NOT NULL,
[WarehouseCode] [nvarchar] (500) NULL,
[BinNum] [nvarchar] (500) NULL,
[BatchNum] [nvarchar] (500) NULL,
[SupplierNum] [nvarchar] (500) NULL,
[PartNum] [nvarchar] (500) NULL,
[DelivTime] [nvarchar] (50) NULL,
[LastStockTakeDate] [nvarchar] (50) NULL,
[MaxStockQty] [nvarchar] (500) NULL,
[StockBalance] [nvarchar] (500) NULL,
[StockValue] [nvarchar] (500) NULL,
[ReOrderLevel] [nvarchar] (500) NULL,
[SafetyStock] [nvarchar] (500) NULL,
[OptimalOrderQty] [nvarchar] (500) NULL,
[SalesRemainingQty] [nvarchar] (500) NULL,
[PurchaseRemainingQty] [nvarchar] (500) NULL,
[AvgCost] [nvarchar] (500) NULL,
[Currency] [nvarchar] (500) NULL,
[ExchangeRate] [nvarchar] (500) NULL,
[CreatedTimeStamp] [nvarchar] (50) NULL,
[ModifiedTimeStamp] [nvarchar] (50) NULL,
[IsActiveRecord] [nvarchar] (50) NULL
)
GO
