/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[TMT_FI_Supplier]
(
[Company] [nvarchar] (8) NULL,
[PartitionKey] [nvarchar] (50) NULL,
[SupplierNum] [nvarchar] (50) NULL,
[MainSupplierName] [nvarchar] (50) NULL,
[SupplierName] [nvarchar] (50) NULL,
[CountryCode] [nvarchar] (50) NULL,
[CountryName] [nvarchar] (50) NULL,
[SupplierCategory] [nvarchar] (50) NULL,
[AddressLine1] [nvarchar] (200) NULL,
[AddressLine2] [nvarchar] (200) NULL,
[AddressLine3] [nchar] (10) NULL,
[ZipCode] [nvarchar] (50) NULL,
[City] [nvarchar] (200) NULL,
[TelephoneNum] [nvarchar] (50) NULL,
[Email] [nvarchar] (100) NULL,
[Website] [nvarchar] (100) NULL,
[VATNum] [nvarchar] (50) NULL,
[AccountNum] [nvarchar] (50) NULL,
[InternalExternal] [nvarchar] (50) NULL,
[SupplierScore] [nvarchar] (50) NULL,
[SupplierResponsible] [nvarchar] (50) NULL,
[Comments] [nvarchar] (max) NULL,
[CodeOfConduct] [nvarchar] (50) NULL
)
GO
