/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[TRA_SE_PurchaseLedger]
(
[PartitionKey] [nvarchar] (25) NULL,
[Company] [nvarchar] (8) NULL,
[SupplierNum] [nvarchar] (20) NULL,
[PurchaseInvoiceNum] [nvarchar] (25) NULL,
[PurchaseInvoiceDate] [nvarchar] (60) NULL,
[InvoiceAmount] [nvarchar] (60) NULL,
[Currency] [nvarchar] (3) NULL,
[ExchangeRate] [nvarchar] (60) NULL,
[PurchaseOrderNum] [nvarchar] (60) NULL,
[PurchaseDueDate] [nvarchar] (60) NULL,
[PurchaseLastPaymentDate] [nvarchar] (60) NULL,
[PaidInvoiceAmount] [nvarchar] (60) NULL,
[RemainingInvoiceAmount] [nvarchar] (60) NULL,
[AccountingDate] [nvarchar] (60) NULL,
[VATAmount] [nvarchar] (60) NULL,
[PaymentTerms] [nvarchar] (2) NULL,
[IsInvoiceClosed] [nvarchar] (1) NULL,
[CreatedTimeStamp] [nvarchar] (60) NULL,
[ModifiedTimeStamp] [nvarchar] (60) NULL,
[IsActiveRecord] [nvarchar] (1) NULL,
[journal] [nvarchar] (10) NULL
)
GO
