/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[TRA_SE_Supplier]
(
[PartitionKey] [nvarchar] (25) NULL,
[Company] [nvarchar] (8) NULL,
[SupplierNum] [nvarchar] (20) NULL,
[SupplierName] [nvarchar] (100) NULL,
[ParentSupplierName] [nvarchar] (100) NULL,
[AddressLine1] [nvarchar] (36) NULL,
[AddressLine2] [nvarchar] (36) NULL,
[TelephoneNum1] [nvarchar] (200) NULL,
[Email] [nvarchar] (100) NULL,
[ZipCode] [nvarchar] (10) NULL,
[City] [nvarchar] (36) NULL,
[State] [nvarchar] (5) NULL,
[CountryCode] [nvarchar] (3) NULL,
[CountryName] [nvarchar] (50) NULL,
[SupplierCategory] [nvarchar] (50) NULL,
[VATNum] [nvarchar] (20) NULL,
[OrgNum] [nvarchar] (18) NULL,
[IsAxInterInternal] [nvarchar] (1) NULL,
[IsBusinessGroupInternal] [nvarchar] (1) NULL,
[IsCompanyGroupInternal] [nvarchar] (1) NULL,
[CreatedTimeStamp] [nvarchar] (60) NULL,
[ModifiedTimeStamp] [nvarchar] (60) NULL,
[RecordIsActive] [nvarchar] (1) NULL,
[Website] [nvarchar] (100) NULL
)
GO
