/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[TRA_FR_StockBalance]
(
[PartitionKey] [nvarchar] (50) NOT NULL,
[Company] [nvarchar] (50) NOT NULL,
[PartNum] [nvarchar] (50) NOT NULL,
[DelivTime] [nvarchar] (50) NULL,
[WarehouseCode] [nvarchar] (50) NULL,
[StockBalance] [nvarchar] (50) NULL,
[StockValue] [nvarchar] (50) NULL,
[ReservedQty] [nvarchar] (50) NULL,
[BackOrderQty] [nvarchar] (50) NULL,
[OrderQty] [nvarchar] (50) NULL,
[StockTakeDiff] [nvarchar] (50) NULL,
[ReOrderLevel] [nvarchar] (50) NULL,
[OptimalOrderQty] [nvarchar] (50) NULL,
[BinNum] [nvarchar] (50) NULL,
[SupplierNum] [nvarchar] (50) NULL,
[LastStockTakeDate] [date] NULL,
[LastStdCostCalDat] [date] NULL,
[BatchNum] [nvarchar] (50) NULL,
[AvgCost] [nvarchar] (50) NULL,
[MaxStockQty] [nvarchar] (50) NULL,
[ReserveQty] [nvarchar] (50) NULL,
[Currency] [nvarchar] (10) NULL,
[SafetyStock] [nvarchar] (50) NULL,
[SBRes1] [nvarchar] (50) NULL,
[SBRes2] [nvarchar] (50) NULL,
[SBRes3] [nvarchar] (50) NULL
)
GO
