/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[TRA_FR_SalesLedger]
(
[PartitionKey] [nvarchar] (50) NULL,
[Company] [nvarchar] (8) NOT NULL,
[CustomerNum] [nvarchar] (100) NULL,
[SalesInvoiceNum] [nvarchar] (50) NULL,
[SalesInvoiceDate] [nvarchar] (50) NULL,
[DueDate] [nvarchar] (50) NULL,
[LastPaymentDate] [nvarchar] (50) NULL,
[InvoiceAmount] [decimal] (18, 4) NULL,
[RemainingInvoiceAmount] [decimal] (18, 4) NULL,
[ExchangeRate] [decimal] (18, 4) NULL,
[Currency] [nvarchar] (50) NULL,
[VATAmount] [nvarchar] (50) NULL,
[VATCode] [nvarchar] (50) NULL,
[PayToName] [nvarchar] (50) NULL,
[PayToCity] [nvarchar] (50) NULL,
[PayToContact] [nvarchar] (50) NULL,
[PaymentTerms] [nvarchar] (50) NULL
)
GO
