/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[TRA_SE_SalesLedger]
(
[PartitionKey] [varchar] (50) NULL,
[Company] [nvarchar] (10) NULL,
[CustomerNum] [nvarchar] (50) NULL,
[SalesInvoiceNum] [nvarchar] (50) NULL,
[SalesInvoiceDate] [date] NULL,
[DueDate] [date] NULL,
[LastPaymentDate] [date] NULL,
[InvoiceAmount] [decimal] (18, 4) NULL,
[RemainingInvoiceAmount] [decimal] (18, 4) NULL,
[ExchangeRate] [decimal] (18, 4) NULL,
[Currency] [nvarchar] (50) NULL,
[VATAmount] [decimal] (18, 4) NULL,
[VATCode] [nvarchar] (50) NULL,
[momsbeskrivning] [nvarchar] (50) NULL,
[PaymentTerms] [nvarchar] (50) NULL
)
GO
