/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[TRA_SE_Part]
(
[PartitionKey] [nvarchar] (50) NULL,
[Company] [nvarchar] (50) NULL,
[PartNum] [nvarchar] (50) NULL,
[PartName] [nvarchar] (max) NULL,
[PartDescription] [nvarchar] (max) NULL,
[ProductGroup] [nvarchar] (100) NULL,
[ProductGroup2] [nvarchar] (100) NULL,
[CommodityCode] [nvarchar] (50) NULL,
[PartReplacementNum] [nvarchar] (max) NULL,
[PartStatus] [nvarchar] (50) NULL,
[CountryOfOrigin] [nvarchar] (max) NULL,
[NetWeight] [nvarchar] (50) NULL,
[UoM] [nvarchar] (50) NULL,
[ReOrderLevel] [nvarchar] (50) NULL,
[StartDate] [nvarchar] (50) NULL,
[MainSupplier] [nvarchar] (max) NULL,
[AlternativeSupplier] [nvarchar] (100) NULL
)
GO
