/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[TRA_SE_PurchaseOrder]
(
[PartitionKey] [nvarchar] (25) NULL,
[Company] [nvarchar] (8) NULL,
[PurchaseOrderNum] [nvarchar] (60) NULL,
[PurchaseOrderLine] [nvarchar] (60) NULL,
[PurchaseOrderType] [nvarchar] (50) NULL,
[PurchaseOrderDate] [nvarchar] (60) NULL,
[PurchaseOrderStatus] [nvarchar] (50) NULL,
[IsOrderClosed] [nvarchar] (6) NULL,
[OrgReqDelivDate] [nvarchar] (60) NULL,
[ReqDelivDate] [nvarchar] (60) NULL,
[OrgCommittedDelivDate] [nvarchar] (60) NULL,
[CommittedDelivDate] [nvarchar] (60) NULL,
[ActualDelivDate] [nvarchar] (60) NULL,
[PartNum] [nvarchar] (30) NULL,
[SupplierNum] [nvarchar] (20) NULL,
[SupplierPartNum] [nvarchar] (30) NULL,
[SupplierInvoiceNum] [nvarchar] (25) NULL,
[PurchaseOrderQty] [nvarchar] (60) NULL,
[PurchaseReceiveQty] [nvarchar] (60) NULL,
[PurchaseInvoiceQty] [nvarchar] (60) NULL,
[UoM] [nvarchar] (4) NULL,
[UnitPrice] [nvarchar] (60) NULL,
[DiscountPercent] [nvarchar] (60) NULL,
[DiscountAmount] [nvarchar] (60) NULL,
[Currency] [nvarchar] (60) NULL,
[PurchaserName] [nvarchar] (50) NULL,
[WarehouseCode] [nvarchar] (8) NULL,
[CreatedTimeStamp] [nvarchar] (60) NULL,
[ModifiedTimeStamp] [nvarchar] (60) NULL,
[IsActiveRecord] [nvarchar] (1) NULL
)
GO
