/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[TRA_SE_StockBalance]
(
[PartitionKey] [nvarchar] (25) NULL,
[Company] [nvarchar] (8) NULL,
[WarehouseCode] [nvarchar] (8) NULL,
[BinNum] [nvarchar] (20) NULL,
[SupplierNum] [nvarchar] (20) NULL,
[PartNum] [nvarchar] (30) NULL,
[DelivTime] [nvarchar] (60) NULL,
[LastStockTakeDate] [nvarchar] (60) NULL,
[LastStdCostCalDate] [nvarchar] (60) NULL,
[StockBalance] [nvarchar] (60) NULL,
[StockValue] [nvarchar] (60) NULL,
[Currency] [nvarchar] (3) NULL,
[SalesRemainingQty] [nvarchar] (60) NULL,
[PurchaseRemainingqty] [nvarchar] (60) NULL,
[SafetyStock] [nvarchar] (60) NULL,
[OptimalOrderQty] [nvarchar] (60) NULL,
[AvgCost] [nvarchar] (60) NULL,
[CreatedTimeStamp] [nvarchar] (60) NULL,
[ModifiedTimeStamp] [nvarchar] (60) NULL,
[IsActiveRecord] [nvarchar] (1) NULL
)
GO
