/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[WID_FI_PricePurchase]
(
[PartitionKey] [varchar] (50) NOT NULL,
[Company] [nvarchar] (8) NULL,
[SupplierNum] [nvarchar] (50) NULL,
[PartNum] [nvarchar] (50) NULL,
[TargetMargin] [nvarchar] (50) NULL,
[Currency] [nvarchar] (50) NULL,
[Price] [decimal] (18, 4) NULL,
[DiscountPercent] [decimal] (18, 4) NULL,
[ValidFrom] [date] NULL,
[ValidTo] [date] NULL,
[DelivTime] [nvarchar] (50) NULL,
[DelivTimeUnit] [nvarchar] (50) NULL,
[Qty1] [decimal] (18, 4) NULL,
[Discount1] [decimal] (18, 4) NULL,
[Price1] [decimal] (18, 4) NULL,
[Qty2] [decimal] (18, 4) NULL,
[Discount2] [decimal] (18, 4) NULL,
[Price2] [decimal] (18, 4) NULL,
[Qty3] [decimal] (18, 4) NULL,
[Discount3] [decimal] (18, 4) NULL,
[Price3] [decimal] (18, 4) NULL,
[Qty4] [decimal] (18, 4) NULL,
[Discount4] [decimal] (18, 4) NULL,
[Price4] [decimal] (18, 4) NULL,
[Qty5] [decimal] (18, 4) NULL,
[Discount5] [decimal] (18, 4) NULL,
[Price5] [decimal] (18, 4) NULL,
[Type] [nvarchar] (50) NULL
)
GO
