/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[WID_EE_PurchaseOrder]
(
[PartitionKey] [varchar] (50) NOT NULL,
[Company] [nvarchar] (8) NOT NULL,
[PurchaseOrderNum] [varchar] (50) NULL,
[PurchaseOrderLine] [nvarchar] (50) NULL,
[PurchaseOrderSubLine] [nvarchar] (50) NULL,
[LineType] [nvarchar] (50) NULL,
[SupplierCode] [nvarchar] (50) NULL,
[InvoiceSupplierCode] [nvarchar] (50) NULL,
[DelivCustCode] [nvarchar] (50) NULL,
[InvoiceNum] [nvarchar] (50) NULL,
[PartNum] [nvarchar] (50) NULL,
[OrderType] [nvarchar] (50) NULL,
[UnitPrice] [decimal] (18, 4) NULL,
[ItemType] [int] NULL,
[DiscountPercent] [decimal] (18, 4) NULL,
[DiscountAmount] [decimal] (18, 4) NULL,
[OrderedQty] [decimal] (18, 4) NULL,
[ReceivedQty] [decimal] (18, 4) NULL,
[InvoicedQty] [decimal] (18, 4) NULL,
[TotalMiscChrg] [decimal] (18, 4) NULL,
[ExchangeRate] [decimal] (18, 4) NULL,
[Currency] [nvarchar] (50) NULL,
[OrderDate] [date] NULL,
[CommittedDelivDate] [date] NULL,
[ActualDelivDate] [date] NULL,
[ReqDelivDate] [date] NULL,
[DelivDate] [date] NULL,
[OrgReqDelivDate] [date] NULL,
[PurchaserName] [nvarchar] (50) NULL,
[RecievingNumber] [nvarchar] (50) NULL,
[LeadTime] [nvarchar] (50) NULL,
[Comments] [nvarchar] (max) NULL,
[WarehouseCode] [nvarchar] (50) NULL
)
GO
