/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [stage].[WID_EE_StockBalance]
(
[PartitionKey] [nvarchar] (50) NOT NULL,
[Company] [nvarchar] (50) NOT NULL,
[PartNum] [nvarchar] (70) NOT NULL,
[WarehouseCode] [nvarchar] (50) NOT NULL,
[StockBalance] [decimal] (18, 4) NULL,
[ReservedQty] [decimal] (18, 4) NULL,
[BackOrderQty] [decimal] (18, 4) NULL,
[QtyOrdered] [decimal] (18, 4) NULL,
[FIFOValue] [decimal] (18, 4) NULL,
[StockTakDiff] [decimal] (18, 4) NULL,
[DelivTime] [int] NULL,
[DelivTimeUnit] [int] NULL,
[DelivTimeDesc] [nvarchar] (50) NULL,
[ReOrderLevel] [decimal] (18, 4) NULL,
[OptimalOrderQty] [decimal] (18, 4) NULL,
[BinNum] [nvarchar] (12) NULL,
[SupplierNum] [nvarchar] (50) NULL,
[LastStockTakeDate] [date] NULL,
[LastStdCostCalDate] [date] NULL,
[DelivDateSupplier] [date] NULL,
[DelivDateCust] [date] NULL,
[OrderDateSupplier] [date] NULL,
[BatchNum] [nvarchar] (50) NULL,
[AvgCost] [decimal] (18, 4) NULL,
[MaxStockQty] [decimal] (18, 4) NULL,
[Currency] [nvarchar] (10) NULL
)
GO
